### PR TITLE
[14849] Only allow dragging inside bottom sheet when no handle is shown

### LINKED ISSUE #14781: Can't scroll photo gallery on Android
# Bug Report

## Problem 

You can only scroll through the gallery with two fingers on the screen. 

https://user-images.githubusercontent.com/67952253/212388773-cf92191a-c7d4-496a-92dc-9affe3db8af1.mp4

### Reproduction

1. Open a chat on Android
2. Open a photo gallery
3. Try to scroll it

### Additional Information

- Status version: nightly 13/01
- Operating System: Android

[comment]: # (Please, add logs/notes if necessary)

### LINKED ISSUE #14849: Make bottom-sheet drag gesture only on work on handle
# Bug Report

## Problem 
This issue is to prevent the bottom sheet from being draggle on all of it's view (Ideally we want it to be draggable only from it's top handle) this will fix the issue of photo selector not scrolling and it should've been this way from the start.

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #14849, #14781

### Summary
The current bottom sheet implementation allows to drag the bottom sheet down to dismiss it in any part of it, If a flat-list or any scrollable component exists nested inside it, it won't be able to scroll in it .. So a solution that @flexsurfer suggested was to only drag it down from it's handle .. This PR does the proposed solution

status: ready

### CODE REVIEW

File: src/status_im2/common/bottom_sheet/view.cljs [hunk 1]
```diff
@@ -247,9 +211,54 @@
                {:style (reanimated/apply-animations-to-style
                         {:opacity bg-opacity}
                         styles/backdrop)}]]
+             ;; VVVVVVV
+             ;; This is repeated because gesture-handler doesn't play nicely when it's conditionally
```
Comment (ilmotta) [inline src/status_im2/common/bottom_sheet/view.cljs]: It's hard for me to accept this @ibrkhalil. There must be a way to not simply copy and paste the whole thing. We should be able to extract the common logic into a separate function and remove the duplication.

Extracting to a separate function would have the added benefit of helping the bottom sheet component *not grow* any longer. This component is crying to be broken down into smaller chunks, really hard to read IMO.

File: src/status_im2/common/bottom_sheet/view.cljs [hunk 2]
```diff
@@ -247,9 +211,54 @@
...
+                    [rn/view
+                     {:style     (styles/content-style insets)
+                      :on-layout (when-not (and
+                                            (some? @content-height)
+                                            (> @content-height 0))
+                                   on-content-layout)}
+                     children]]
+
+                   [handle-comp window-width]]]]]
+               #_[gesture/gesture-detector {:gesture bottom-sheet-gesture}
```
Comment (ilmotta) [inline src/status_im2/common/bottom_sheet/view.cljs]: Why keep the zombie code here? Note that zombie code is worse than dead code, it gently attacks developers every now and then, confuses them, and drags them into unnecessary discussions ;)

Seriously, if there's a need to keep the zombie code, please, always add a comment explaining why. But preferably, just remove them and we can rely on git for going back in history.

Comment (ibrkhalil) [reply src/status_im2/common/bottom_sheet/view.cljs]: My bad Icaro, This is a mistake

File: src/status_im2/common/bottom_sheet/view.cljs (hunk 1 above)
Comment (ibrkhalil) [reply src/status_im2/common/bottom_sheet/view.cljs]: Alright, I'll investigate more on ways to refactor it and not repeat myself

File: src/status_im2/common/bottom_sheet/view.cljs (hunk 2 above)
Comment (ilmotta) [reply src/status_im2/common/bottom_sheet/view.cljs]: No worries :mechanical_arm:

File: src/status_im2/common/bottom_sheet/view.cljs (hunk 1 above)
Comment (ibrkhalil) [reply src/status_im2/common/bottom_sheet/view.cljs]: Can you please check the current approach Icaro ?

File: src/status_im2/common/bottom_sheet/view.cljs (hunk 2 above)
Comment (ibrkhalil) [reply src/status_im2/common/bottom_sheet/view.cljs]: Done

File: src/status_im2/common/bottom_sheet/view.cljs [hunk 3]
```diff
@@ -200,28 +213,27 @@
...
+                          [rn/view {:style (styles/selected-background)}
+                           [selected-item]])
+                        [rn/view {:style (styles/background)}
+                         [rn/keyboard-avoiding-view
+                          {:behaviour (if platform/ios? :padding :height)
+                           :style     {:flex 1}}
+                          [rn/view
+                           {:style     (styles/content-style insets)
+                            :on-layout (when-not (and
+                                                  (some? @content-height)
```
Comment (cammellos) [inline src/status_im2/common/bottom_sheet/view.cljs:231]: This looks like it can be simplified, I think
at least `(when-not (pos? @content-height) ...)`, you are just checking if it's `0` or `nil?` right?

File: src/status_im2/common/bottom_sheet/view.cljs (hunk 1 above)
Comment (ilmotta) [reply src/status_im2/common/bottom_sheet/view.cljs]: Much better!

File: src/status_im2/common/bottom_sheet/view.cljs (hunk 3 above)
Comment (ilmotta) [reply src/status_im2/common/bottom_sheet/view.cljs:231]: I usually prefer to avoid inverse logic, also `some?` is usually not needed in Clojure, because Clojure has *truthiness* (non-nil is true).

```clojure
(when (and @content-height (<= @content-height 0))
  on-content-layout)
```

Or if we are sure the content height can't be negative:

```clojure
(when (and @content-height (zero? @content-height))
  on-content-layout)
```

**Review by ilmotta — APPROVED** [review]

File: src/status_im2/common/bottom_sheet/view.cljs [hunk 4]
```diff
@@ -83,6 +83,17 @@
...
+  [window-width]
+  [rn/view
+   {:style {:width            window-width
+            :position         :absolute
+            :background-color :transparent
+            :top              0
+            :height           20}}
+   [rn/view {:style (styles/handle)}]])
+
+
```
Comment (ilmotta) [inline src/status_im2/common/bottom_sheet/view.cljs]: Extra line

**Review by alwx — APPROVED** [review]

**Comment by VolodLytvynenko** [comment]
Hi @ibrkhalil Thank you for your work.  The PR is tested and ready to be merged!
