### PR TITLE
[#11408] User sees status in timeline of account which added him in contacts 

### LINKED ISSUE #11408: User sees status in timeline of account which added him in contacts
# Bug Report

## Problem

When UserA has been added by UserB in UserB's contacts then UserA sees all status updates in timeline UserB makes. 
After UserA re-logins then UserB's status disappears on his end, but all subsequent UserB's statuses appear again. 
Please see steps to reproduce.

#### Expected behavior

I see no status updates from any user I have not in my contact list

#### Actual behavior

I see status updates of users who added me in contact

### Reproduction

- Create two new accounts: UserA and UserB
- UserA navigates to Timeline view
- UserB adds UserA in contacts
- UserB creates new status in timeline
- UserA checks timeline on his end
Actual result: UserA sees UserB status update
Expected result: No any statuses UserA sees
- UserA relogins
- UserA opens timeline again 
Expected result = Actual result: No any statuses on UserA side
- But when UserB creates new status in timeline again then...
Actual result: UserA sees UserB status update
Expected result: No any statuses UserA sees

### Additional Information

- Status version: develop 
- Operating System: Android and iOS

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #11408

### CODE REVIEW

**Comment by Serhy** [comment]
Tested with iOS14 and Android 9.
Can not reproduce initial issue anymore. Statuses are visible only from contacts who added in contact list. Once contact removed from contacts (OR blocked) list then all statuses disappear. 
Thanks @flexsurfer !

File: src/status_im/chat/models.cljs [hunk 1]
```diff
@@ -271,7 +271,7 @@
               (transport.filters/load-chat chat-id)
               (navigate-to-chat chat-id))))
 
-(def timeline-chat-id "@timeline")
+(def timeline-chat-id "@timeline70bd746ddcc12beb96b2c9d572d0784ab137ffc774f5383e50585a932080b57cca0484b259e61cecbaa33a4c98a300a")
```
Comment (Ferossgp) [inline src/status_im/chat/models.cljs:274]: Would be nice to add a comment/document it for future references

**Review by Ferossgp — APPROVED** [review]

**Comment by flexsurfer** [comment]
@Serhy have you tested synced contacts ?
