### PR TITLE
[8556] fix - Last message jumps up after chat is opened

### LINKED ISSUE #8556: Last message jumps up after chat is opened
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: after chat screen is opened input filed overlaps with last message, so message is half-visible. After  this last message "jumps up", so it's fully visible. It happens in each chat type.

when chat opened:
Screenshot_20190710-173857

a second later after chat is opened
Screenshot_20190710-173907

jump

#### Expected behavior

Chat screen shows all messages and nothing is moving on the screen if no new messages received
#### Actual behavior
last message jumps up after chat screen is opened

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- join public chat with message and open it
- look at last message in the chat and if it moves on the  screen 

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly july 10
- Operating System: Android and iOS

### PR DESCRIPTION
**Pull request by bitsikka**
fixes #8556 

This bothered me so much that I kept thinking about it and looking for solution, even though, I'd committed to work on other issues 😛.

I may have found the solution (maybe could be better). Please review/test and see if it is acceptable.

Solution was achieved still using native animation introduced in #8498, and not by reverting to old non-native solution before #8498.

### Testing Notes:
- This affects `home` and `chat` screens
- This affects `mobile` and may affect `desktop`

Tested only on iOS-Simulator so far (all below were done in iOS-Simulator)
- In `home` and `chat` screen checked turning on/off network
   - In my network when I turn off Wifi and turning it back on - `wallet offline` message shows and does not go away; But I think it is not related to this PR.
  - checked by re-login(network bar shows up), then quickly navigating to a chat while the network bar is still doing its thing until it goes away
- In `home` screen checked triggering/focusing/entering text/cancelling with `chat search`
- In `home` screen added more chats than fits the height of screen, checked scrolling, navigating to different chats
- In `home` screen deleted chats

In some manual tests above, problems were found and resolved

----------
status: ready for review

### CODE REVIEW

**Comment by bitsikka** [comment]
please bare with me.. got too excited
1. desktop issues to look into
2. add to contact issue (sounds like should be moved to different component nesting.. but has problem if we do that.. so leaving it as it was)

**Comment by bitsikka** [comment]
> please bare with me.. got too excited
> 
> 1. desktop issues to look into
> 2. add to contact issue (sounds like should be moved to different component nesting.. but has problem if we do that.. so leaving it as it was)

#2 is fixed.. at some point though.. structure of components in chat view probably needs refactoring

#1 made test pass by doing this
https://github.com/status-im/status-react/blob/709f50cb1ec7cbf8681daad7553ca0b80ce10b6a/src/status_im/ui/screens/desktop/main/chat/views.cljs#L257
but need to look more

**Comment by bitsikka** [comment]
for #1 looks like doing this https://github.com/status-im/status-react/blob/709f50cb1ec7cbf8681daad7553ca0b80ce10b6a/src/status_im/ui/screens/desktop/main/chat/views.cljs#L257

should still work

All builds have passed, so, going to call it ready for review

**Comment by bitsikka** [comment]
found and fixed(in the last force push) an issue in home screen where if you deleted a chat with long-press chat search field would show up after deletion.

**Review by flexsurfer — APPROVED** [review]

**Comment by bitsikka** [comment]
Please still bare with me on this!

In the current solution I have been quite unsatisfied with the weird hacky trick I discovered and used (where, a non-animatable property :margin-bottom is being animated). Use of convolutedly-passing-around-padding-value, and use of listening-and-using-anim-actual-value wasn't sparking joy either.

It feels like it makes the revealing and hiding of connectivity bar not so smooth, or something subtly wrong.

So I couldn't help looking for better solution.

I think I found it! a solution where hacky tricks are not(or minimally) needed.

With some more testing and cleaning up I will update the PR soon.

**Comment by bitsikka** [comment]
@flexsurfer 
In this update, implementation has changed significantly, previous review is obsolete.
In this, I had to fundamentally re-implement how native animation for `connectivity-view` works. I have put copious amount of comment in code(to be removed, when finalized).

@annadanchenko / test team
I have tested this in Android-avd as well as iOS-simulator all the stuff I mentioned in the **Testing Notes** section in issue description above https://github.com/status-im/status-react/pull/8589#issue-298473468.

MacOS build failed and I suspect there are things that may be broken in desktops. I don't know how much of a priority this is, but I have stayed away from dev building/testing desktop so far. Anyway, this should be fairly easy to fix on desktop when required/needed.

**Comment by bitsikka** [comment]
> found and fixed(in the last force push) an issue in home screen where if you deleted a chat with long-press chat search field would show up after deletion.

This issue which is fixed in this PR is actually a search-bar bug that happens in Nightly also. Similar appearance of bug identified by @asemiankevich in https://github.com/status-im/status-react/pull/8599#issuecomment-514082412

File: src/status_im/ui/components/connectivity/view.cljs [hunk 1]
```diff
@@ -62,68 +66,71 @@
...
                                                                                colors/green
                                                                                colors/gray)
+                                                           ;;TODO how does this affect desktop?
+                                                           :transform      neg-anim-translate-y
                                                            :opacity anim-opacity
                                                            :modal? (= view-id :chat-modal)))
                               :accessibility-label :connection-status-text}
          (when connecting?
-           [react/activity-indicator {:animated     true
+           [react/activity-indicator {:animating    true
```
Comment (flexsurfer) [inline src/status_im/ui/components/connectivity/view.cljs]: could you please elaborate? does this mean it was not animated before?

File: src/status_im/ui/screens/home/styles.cljs [hunk 2]
```diff
@@ -185,13 +185,15 @@
    :margin-horizontal 32
    :color             colors/gray})
 
-(def action-button-container
+(defn action-button-container [home-width]
```
Comment (flexsurfer) [inline src/status_im/ui/screens/home/styles.cljs:188]: could you elaborate on changes in this function? why do we need z-index and left?

File: src/status_im/ui/components/connectivity/view.cljs (hunk 1 above)
Comment (yenda) [reply src/status_im/ui/components/connectivity/view.cljs]: it can be removed because default is true

https://facebook.github.io/react-native/docs/0.59/activityindicator

**Review by yenda — APPROVED** [review]
I wouldn't prefix neg before all those symbols but other than that nothing to complain about. Good job and thank you for another deeply thought out fix to an annoying issue!

File: src/status_im/ui/screens/home/styles.cljs (hunk 2 above)
Comment (bitsikka) [reply src/status_im/ui/screens/home/styles.cljs:188]: yes.. the + action-button was centered using `:align-items :center` of the parent which required all the children of the parent to have `:align-items :stretch` which seemed cumbersome and error prone(was puzzled at first when an element did not render without stretch), So, instead centered it using calculation.

I put a border around `connectivity-view-wrapper` for testing and previous method of centering would cause the whole content area to be briefly rendered squeezed(not stretched) when landing on home screen as well - which I thought was weird.

File: src/status_im/ui/components/connectivity/view.cljs (hunk 1 above)
Comment (bitsikka) [reply src/status_im/ui/components/connectivity/view.cljs]: cool.. going to remove it

@flexsurfer turns out correct property for `activityIndicator` is `:animating` not `animated`. Weird that it is inconsistent in react-native with some other component in which opposite is true.

Anyway, I was dealing with the problem of `connecting/fetching` indicator and couldn't figure out where in code dealt with that. I was confused about what it would be called and poked around/searhed-docs thinking maybe it was called `activity-indicator` :)

**Comment by bitsikka** [comment]
> I wouldn't prefix neg before all those symbols but other than that nothing to complain about. Good job and thank you for another deeply thought out fix to an annoying issue!

@yenda Thank you!
It did bake my noodle a bit, but I enjoyed it ;)

I was contemplating solutions and in one of the track of various ideas I was thinking maybe to animate the connectivity bar going down while the content was going up at the same time to stay-in-place/not-be-pushed-down. Later realized didn't need to have the opposite direction animation.

Anyway, I'll rename it back to kind of like how it was.

File: src/status_im/ui/screens/home/styles.cljs (hunk 2 above)
Comment (bitsikka) [reply src/status_im/ui/screens/home/styles.cljs:188]: critical part of how the new implementation works is by layering of sibling components using z-index and defying natural layering of bottom siblings being rendered on top of one above. So, in order for the action button to be above content, it required higher z-index.

**Comment by bitsikka** [comment]
@yenda 
I have omitted `neg-` prefix for animated value where it does not make sense anymore, but kept it for connectivity bar height to clarify the relation to the height when reading code. Not sure if that is necessary, or if it is better in terms of performance to use literal value directly instead.

I have also kept most of the comments for now.

Let me know if it is wiser to strip them out and make it leaner.

Other than that, I think it good to go for testing. cc @annadanchenko

**Comment by bitsikka** [comment]
Note: After cherry pick merging in release branch, which this may cause conflicts(will look into if it does), need to test if this PR fixes this issue as well https://github.com/status-im/status-react/pull/8599#issuecomment-514082412 (will look into if it does not).

**Comment by asemiankevich** [comment]
@Serhy @yevh-berdnyk looks something wrong with framework here?

**Comment by asemiankevich** [comment]
@bitsikka in desktop build ( Mac OS) when i join public chat:

image

steps:
- open status desktop
- login with recovery phrase since creating new account is not working (known bug)
- tap + -> join Status channel

I can't reproduce it in nightly. Please take a look

**Comment by bitsikka** [comment]
> @bitsikka in desktop build ( Mac OS) when i join public chat:
> 
> IMAGE
> 
> steps:
> 
> * open status desktop
> * login with recovery phrase since creating new account is not working (known bug)
> * tap + -> join Status channel
> 
> I can't reproduce it in nightly. Please take a look

Got it!
Jumping now into desktop dev to troubleshoot.

**Comment by bitsikka** [comment]
@PombeirP @vkjr I have been unable to setup dev build for desktop following instructions in https://status.im/build_status/desktop.html

I twiddled and fiddled trying to bypass various errors without luck for a while, giving up finally.

The documentation I linked itself seems to be needing update. It talks of doing `make startdev-desktop` and there's no mention of `make watch-desktop`. I mainly had trouble doing `make desktop-server` with following error
```
[nix-shell:~/Projects/status-react]$ make desktop-server
make[1]: Entering directory '/Users/___/Projects/status-react'
node ubuntu-server.js
outerRealmConstructor: undefined
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/Users/___/Projects/status-react/node_modules/realm/compiled/node-v64_darwin_x64/realm.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/___/Projects/status-react/node_modules/realm/lib/index.js:112:28)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
make[1]: Leaving directory '/Users/___/Projects/status-react'
make[1]: *** [Makefile:189: desktop-server] Error 1

```
But even before that there were other problems I tried to resolve, like trying to get `realm.node` module where it was expected.

help!

@asemiankevich I'm afraid I cannot troubleshoot the problem without being able to have dev build setup.

**Comment by bitsikka** [comment]
Help!

In the process of trying to get dev build of desktop going I tried starting over with `nix-collect-garbage -d`
then failed and gave up.

Now I cannot get iOS dev build setup with following error.

```
...
copying path '/nix/store/c32rzhsfgsrlg7c80m8vskgq4wmy78fj-libidn2-2.0.5' from 'https://nix-cache.status.im'...
copying path '/nix/store/92za8h94nrkwzb2052b44y7518brym48-libusb-1.0.22' from 'https://nix-cache.status.im'...
copying path '/nix/store/cxwms1sg4ss472kfhglzkgvdbdlxrh6l-libutil-osx-10.11.6' from 'https://nix-cache.status.im'...
hash mismatch importing path '/nix/store/cxwms1sg4ss472kfhglzkgvdbdlxrh6l-libutil-osx-10.11.6';
  wanted: sha256:185h9r8i9bjrqakdpznz3j1jcykpdpizbylgn2pzik9s3vpz2qqz
  got:    sha256:134k0vidc7f0p4zxhjv5qq1609m14pvvbiwn421cg4yx261752i4
copying path '/nix/store/kpw5wqmcczld01kcgvznsrvr9jjw2vm4-libyaml-0.2.1' from 'https://nix-cache.status.im'...
error: build of '/nix/store/2j1kdh49d83ax37z42fq5gqjdj6nxh75-stdenv-darwin.drv', '/nix/store/800l2ps3lb5dblbzf6jz2q89f89xha5k-unzip-6.0.drv', '/nix/store/9dlbv23rxb3lbr0n4k0b3xc49bxp4a67-curl-7.64.0.drv', '/nix/store/a0aix5lvz46rd50sc11ixm8cqhnx09vn-jq-1.6.drv', '/nix/store/f2xc8zp7znaannj9q9byy3zksrwg37rj-git-2.19.2.drv', '/nix/store/f458d7k73p245c2zmq55ys0z2aa4i8fj-leiningen-2.8.3.drv', '/nix/store/fwxlb9x9ghfh3gh1876sjxwg082y6m66-clojure-1.10.0.411.drv', '/nix/store/h4hx8b16pk3fvk2afr9dg28kd5ma2xij-ruby-2.5.3.drv', '/nix/store/jn392n514d78n7y6if4gphkxxgjkpdvz-xcode-wrapper-10.2.1.drv', '/nix/store/m7s9yfma68lmxqslyllaqq1hn8q7rhn3-ps-1003.1-2008.drv', '/nix/store/n02kb7qpjblh0ccb917xra9j8v0j8dkc-bundler-1.17.2.drv', '/nix/store/q80181rmc5zsa9iv9jhmp05l4hxp020y-status-go-v0.30.0-beta.3-9a0502f-ios.drv', '/nix/store/r91yssj1panwy2wwj3sgg28qpyci27h4-cocoapods-1.5.3.drv', '/nix/store/scqbidqr61njcfv4qzj4gw3pjpd0jy2q-apache-maven-3.6.0.drv', '/nix/store/sn9zxjphg1x7231yv4n4x42mc5g02hav-yarn-1.13.0.drv', '/nix/store/x4r8g7s3jlp0x7f7rz4awspngk3g1f64-procps-1003.1-2008.drv', '/nix/store/x6cn2pzrjkcbnbln04vmsihk5mmmjayg-wget-1.20.1.drv', '/nix/store/x9w7zd9lb2fnk9vgf7dkmyf10m4xx4r4-lsof-4.91.drv', '/nix/store/xnsbzmvxqadjm1w7qgis8dl17r7y25xb-ncurses-6.1-20181027.drv', '/nix/store/zc915s5af2cnmqcr613363g9wvjqd6qy-bash-interactive-4.4-p23.drv' failed
make: *** [shell] Error 1
```

for those continuing with their setups from while ago, things probably continue to work, but for starting/re-starting from fresh folks setting up build environment seems to have become broken except maybe for Android.

cc @PombeirP @jakubgs

**Comment by annadanchenko** [comment]
based on discussion with @rachelhamlin @flexsurfer @yenda we will not block mobile app release because of the desktop issue in this PR. 

Reasons: 
- desktop nightly is already broken
- soon we will have mobile ui desktop
- links to nightlies will be removed from the website

So, moving this PR back to TO TEST and we focus only on mobile platforms while testing it

**Comment by bitsikka** [comment]
> based on discussion with @rachelhamlin @flexsurfer @yenda we will not block mobile app release because of the desktop issue in this PR.
> 
> Reasons:
> 
> * desktop nightly is already broken
> * soon we will have mobile ui desktop
> * links to nightlies will be removed from the website
> 
> So, moving this PR back to TO TEST and we focus only on mobile platforms while testing it

Great! I thought so too. Wise to focus on mobile for now.

I will be contributing to desktop for sure when the time comes, as I was initially more interested, still equally interested, about desktop.

Thanks!

**Comment by asemiankevich** [comment]
i logged https://github.com/status-im/status-react/issues/8636 for desktop issue. Mobile builds look good to me, message is not jumping anymore (1x1, public , group chat). Also, search problem on Home seems to be fixed here as well .

**Comment by rachelhamlin** [comment]
Thanks @asemiankevich!

**Comment by bitsikka** [comment]
🎉 

thanks everyone!

**Comment by pedropombeiro** [comment]
@bitsikka sorry you're running into issues with setting up the environment. Regarding `make watch-*`, that is invoked inside `make startdev-*`already. I will try reproducing with a new environment.

**Comment by pedropombeiro** [comment]
OK, I already found an issue in https://github.com/status-im/status-react/blob/develop/nix/shell.sh#L48, please try adding `|darwin|macos` to that list.

**Comment by pedropombeiro** [comment]
I'm now seeing a yarn build issue with the Detox dependency, my guess is that this was introduced by the latest RN Desktop upgrade. cc @vkjr

**Comment by bitsikka** [comment]
@PombeirP
Thanks!

I managed to get a dev build environment for iOS by turning off `nix-cache.status.im` without which, first `make shell` after `make clean`, with `$TARGET_OS` set to `ios` started compiling everything (took a loong time 😅) pulling stuff from cache.nixos.org

I will wait until your latest PRs and issues you have found to be fixed/merged, cache be populated(or something), before I rebase anything else new, and to `make clean` and stuff.

I'm good to continue working on issues for now.

Note(not priority): `make nix-clean` as you know wipes out /nix. For those who are also using Nix package manager for system's package management needs - it is less than practical to do that. Maybe there's a way to separate system Nix store and project specific nix store or something.

Going to NOT run `nix-add-gcroots` and run `nix-collect-garbage -d` as a way to accomplish the intent of `make nix-clean` for now. Only rarely if needed.

**Comment by PombeirP** [comment]
Yeah, `make nix-clean` was added at the beginning as a way to test things, not really meant to be used outside of that scope (unless you know what you are doing). It was left there for the time being until we saw that it isn't needed anymore (personally I haven't seen the need recently, so I'm for removing it).

**Comment by jakubgs** [comment]
>I managed to get a dev build environment for iOS by turning off nix-cache.status.im without which, first make shell after make clean, with $TARGET_OS set to ios started compiling everything (took a loong time sweat_smile) pulling stuff from cache.nixos.org

Why was this necessary?

>make nix-clean as you know wipes out /nix.

Wrong, now `nix-clean` just runs `nix/clean.sh` which only removes `status-react` related stuff from `/nix/store`. The old behavior is now under the `nix-purge` target.

**Comment by bitsikka** [comment]
> > I managed to get a dev build environment for iOS by turning off nix-cache.status.im without which, first make shell after make clean, with $TARGET_OS set to ios started compiling everything (took a loong time sweat_smile) pulling stuff from cache.nixos.org
> 
> Why was this necessary?

I didn't know anything better. I ran regular setup after clean and ran into either
```
hash mismatch importing path '/nix/store/cxwms1sg4ss472kfhglzkgvdbdlxrh6l-libutil-osx-10.11.6';
```
or something else

so I tried different things, and ended up with long thingy that ended up giving me result I needed.

> > make nix-clean as you know wipes out /nix.
> 
> Wrong, now `nix-clean` just runs `nix/clean.sh` which only removes `status-react` related stuff from `/nix/store`. The old behavior is now under the `nix-purge` target.

That is wonderful!

Did not know that.. I just assumed the old behavior.. having done that couple of times before. :(

I manually cleaned /nix and re-installed system stuff, having gotten the list of system installed packages first. I was thinking maybe there was something in /nix/* that was dirty or something.

Thanks! @jakubgs @PombeirP
