### PR TITLE
Integrate keycard interaction animation with keycard flows

### LINKED ISSUE #9334: Access key with Keycard – Bug after entering the pairing code
_Part of #9277 Access a key with Keycard epic (mark as checked there, when closing this issue)_

After entering the pairing code, when user types enter, an error message (connection lost) is shown, where what we should have is an indication to tap the card.

Image:
Screen Shot 2019-11-04 at 14 56 41

Figma:
https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=4540%3A11552

### LINKED ISSUE #9365: Keycard -> Device interaction flow
**What's the problem?**
The way the flow has been designed does not take into account several edge-cases, which were discovered after testing it. 
- The connection with the Keycard often is pretty had to establish (due to the fact that NFC readers are weak on many devices) and easy to interrupt; 
- Sometimes after a successful connection, it might take up to 15 sec to process the data transfer, which is not supported by the UI and for the user it might feel like it's stuck;
- We never explicitly mention that during onboarding the user does not have to keep the card connected all the time, which makes the experience much worse, the user will instinctively maintain the connection during the whole process;
- The flow is on iOS-ready. On iOS the NFC interactions are handled by a native popup;

**States**

- **Initial state.** Screen indicates that it's ready to accept connections;
- **No NFC.** Screen indicates that NFC if switched off on the device and has to be switched on to continue;
- **No connection for 10 seconds.** The screen indicates that the device is still looking for the card and the user most likely should move the card to find the NFC reader on the device;
- **Connection established.** The screen indicates that the connection has been successfully established and the user should hold the card still not to interrupt it. Replaced by "Processing" after 2 sec;
- **Processing...** Screen indicates that a data transfer is in progress. Sometimes it takes up to ~15sec so it's important to indicate that everything is ok, the user just has to hold the card still and wait;
- **Connection interrupted** An error appears to indicate that the connection has been lost and the user should put the card back where it was and hold it still;

**Video**  
https://dribbble.com/shots/8379578-NFC-card-interaction

Figma: https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=5358%3A146
Screen Shot 2020-02-04 at 14 10 04

### LINKED ISSUE #9626: App stucks on "Accessing key" if connection with card was lost during recover account after entering wrong PIN
# Bug Report

## Problem
App stucks on "Accessing key" step after entering wrong PIN during recovering account

#### Expected behavior

[comment]: # (Describe what you expected to happen. Please include designs if possible.)

#### Actual behavior

[comment]: # (Describe what actually happened. Please include screenshots if possible.)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)
**Prerequisites:** have keycard initialized and personalized.

- Open Status
- Access Key > Recover with Keycard
- Enter pairing code
- Put card away from NFC reader of your device
- Enter wrong PIN 
- Hold card to the NFC reader of your device

If "2 retries are left" screen is shown, enter wrong PIN  again. 

### Additional Information

- Status version: nightly 09/12/2109
- Operating System: Android

#### Logs
[accessing-key.log](https://github.com/status-im/status-react/files/3940969/accessing-key.log)

### LINKED ISSUE #9660: Its not possible to cancel signing transaction with keycard after entering PIN
# Bug Report

## Problem

1) Its not possible to cancel signing transaction with keycard

2) There is warning popup after signing transaction

#### Expected behavior

1) Its possible to cancel signing transaction
2) There is no warning popup after sign or cancel transaction

#### Actual behavior

Sign transaction with keycard
Touch device with keycard for 1 second
Remove keycard 
Warning popup appears under signing sheet
Loading indicator is showed on signing sheet
Press cancel on signing sheet
Warning popup is still there
Close popup and try to sign another transaction
There is pincode screen with loading indicator
Not possible to continue

### LINKED ISSUE #9664: Endless spinner after entering wrong PIN code at attempt to change it
# Bug Report

## Problem
At attempt to change PIN code error  "This card does not correspond your account" is shown and on tapping cancel you are redirected to change PIN screen with endless spinner.

#### Expected behavior
Wrong PIN code error

#### Actual behavior
Endless spinner
photo_2019-12-16 14 27 09

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create account with KeyCard
- Relogin
- Go to Profile > Settings > Keycard
- Tap on change 6-digit passcode
- Enter wrong passcode
- Tap card to the NFC reader
- After error "This card does not correspond your account" tap on "Cancel"

### Additional Information

- Status version: nightly 16/12/2019
- Operating System: Android 

#### Logs

[endless-spinner-wrong-pin.log](https://github.com/status-im/status-react/files/3968232/endless-spinner-wrong-pin.log)

### LINKED ISSUE #9676: Empty 'Seed phrase' on screen when generate new account from keycard starting from 'Recover from keycard'
# Bug Report

## Problem

There are two paths to generate new account from keycard now: starting from `Get started` -> `Generate new key` OR `Access key` -> `Recover with keycard`

If to follow `Access key` -> `Recover with keycard` way at the point of when we display `Seed phrase` to remember - there are no words for seed phrase.

#### Expected behavior

Seed phrase displayed when generating new account with keycard via `Access key` -> `Recover with keycard` flow
#### Actual behavior
No seed phrase displayed when generating new account with keycard via `Access key` -> `Recover with keycard` flow

### Reproduction

- Open Status
- Tap `Access key` -> `Recover with keycard` -> `Begin recovery`
- Hold keycard to the back of you device
Result: `There is nothing to recover here`  view with `Generate an new key` button
- Tap `Generate an new key` -> `Begin setup` and hold card to the back of phone
- Enter 6-digit PIN
- Confirm 6-digit PIN
- Tap Next on PUK/Pair codes screen
**Actual result:** 
Screenshot 2019-12-17 at 16 52 33

### Additional Information

- Status version: develop 2019121702
- Operating System: Android

### LINKED ISSUE #9702: App stuck in "Pairing card"  when enter wrong pairing code after cancelling account setup (card is initialized)
# Bug Report

## Problem
When start over generating a new key on keycard from the state of Keycard `Installed: true, Initialized: true` -> if make a mistake in pairing code -> can't proceed and need to start process again.

#### Expected behavior
wrong pairing code

#### Actual behavior
app stuck on "Pairing card" step

### Reproduction

- Open Status
- Get Started -> Generate Key -> Next -> Keycard -> enter and confirm PIN code
- on "Pairing code and PUK" screen cancel setup
- Get Started -> Generate Key -> Next -> Keycard -> On screen when entering Pairing code is required, enter wrong Pairing code
- Hold card to the NFC reader

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 19/12/2019
- Operating System: Android 

#### Logs

[Endless-spinner-pairing.log](https://github.com/status-im/status-react/files/3983086/Endless-spinner-pairing.log)
Card info:
```
Installed: true
Initialized: true
Key Initialized: false
InstanceUID: 0xd8aa1d7203207211cd903f526c255d01
SecureChannelPublicKey: 0x04816ba10bc533551239a3216fc3cbf46402d51c52b9ff6159b707967e9a0bfe20dbd3831661f3a4d0e540e7041ea6bf31cf55e79ef06896a1d8ab4e2396bfc191
Version: 0x0300
AvailableSlots: 0x05
KeyUID: 0x
Capabilities:
  Secure channel:true
  Key management:true
  Credentials Management:true
  NDEF:true
```

### LINKED ISSUE #9704: Redirect to 1 step from 3 if put card to NFC on Backup seed phrase during pairing (no key on card)
# Bug Report

## Problem
Workflow is broken (app redirects to enter PIN code after "Back up seed phrase" step) if put card to and from NFC reader on  "Backup seed phrase" screen when paiting card after cancelling initial create multiaccount flow.

#### Expected behavior
Step 3 -> Backup seed phrase -> finishing up

#### Actual behavior
Step 3, then step 1.

telegram-cloud-document-4-6041711533002589704

### Reproduction

- Open Status
- Get Started -> Generate Key -> Next -> Keycard -> enter and confirm PIN code
- on "Pairing code and PUK" screen cancel setup
- Get Started -> Generate Key -> Next -> Keycard -> enter valid Pairing code
- Hold card to the NFC reader
- on "Backup seed phrase" screen put card back and forth to NFC reader

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 19/12/2019
- Operating System: Android 

#### Logs

[broken-flow.log](https://github.com/status-im/status-react/files/3983216/broken-flow.log)

Card info:
```
Installed: true
Initialized: true
Key Initialized: false
InstanceUID: 0xd8aa1d7203207211cd903f526c255d01
SecureChannelPublicKey: 0x04816ba10bc533551239a3216fc3cbf46402d51c52b9ff6159b707967e9a0bfe20dbd3831661f3a4d0e540e7041ea6bf31cf55e79ef06896a1d8ab4e2396bfc191
Version: 0x0300
AvailableSlots: 0x05
KeyUID: 0x
Capabilities:
  Secure channel:true
  Key management:true
  Credentials Management:true
  NDEF:true
```

### PR DESCRIPTION
**Pull request by Ferossgp**
This PR replaces all screens which were related to keycard connection with a bottom sheet. Before when interaction with the card was required we used to navigate to a screen which says to connect card, during errors and lost of the connection we navigate to other screens. Now all that is handled in the same sheet by animating to different states. 
Fixes #9365
Fixes #9704
Fixes #9676
Fixes #9660
Fixes #9664
Fixes #9626
Fixes #9702
Fixes #9334 

To be checked: #9451 #10023 #10032

### CODE REVIEW

**Comment by Serhy** [comment]
I know it's very WIP, builds just failed on unit tests

**Comment by hesterbruikman** [comment]
Tested with Galaxy s10e. Encountered no issues. Great work!

File: src/status_im/ui/screens/routing/intro_login_stack.cljs [hunk 1]
```diff
@@ -68,10 +59,8 @@
 
               config/hardwallet-enabled?
               (concat [:hardwallet-authentication-method
-                       :hardwallet-connect
                        :keycard-login-pin
                        :keycard-login-connect-card
```
Comment (Ferossgp) [inline src/status_im/ui/screens/routing/intro_login_stack.cljs]: Remove this screen also

File: src/status_im/ui/screens/events.cljs [hunk 2]
```diff
@@ -201,20 +201,16 @@
...
-                :enter-pin-modal (hardwallet/enter-pin-screen-did-load %)
-                :keycard-login-pin (hardwallet/enter-pin-screen-did-load %)
-                :add-new-account-pin (hardwallet/enter-pin-screen-did-load %)
-                :hardwallet-connect (hardwallet/hardwallet-connect-screen-did-load %)
-                :hardwallet-connect-sign (hardwallet/hardwallet-connect-screen-did-load %)
-                :hardwallet-connect-settings (hardwallet/hardwallet-connect-screen-did-load %)
-                :hardwallet-connect-modal (hardwallet/hardwallet-connect-screen-did-load %)
+                :chat                             (chat.loading/load-messages cofx)
+                :home                             (chat.loading/offload-all-messages cofx)
+                :keycard-settings                 (hardwallet/settings-screen-did-load %)
```
Comment (Ferossgp) [inline src/status_im/ui/screens/events.cljs:206]: Remove all on-will-focus events for keycard

File: src/status_im/hardwallet/change_pin.cljs [hunk 3]
```diff
@@ -0,0 +1,107 @@
...
+                (navigation/navigate-to-cofx :multiaccounts nil)
+                (navigation/navigate-to-cofx :keycard-settings nil))
+              (when (:multiaccounts/login db)
+                (common/get-keys-from-keycard)))))
+
+(fx/defn on-change-pin-error
+  {:events [:hardwallet.callback/on-change-pin-error]}
+  [{:keys [db] :as cofx} error]
+  (log/debug "[hardwallet] change pin error" error)
+  (let [tag-was-lost? (= "Tag was lost." (:error error))
```
Comment (rasom) [inline src/status_im/hardwallet/change_pin.cljs:88]: `"Tag was lost."` magic value could be moved to constant

File: src/status_im/hardwallet/common.cljs [hunk 4]
```diff
@@ -0,0 +1,431 @@
...
+
+(fx/defn dispatch-event
+  [_ event]
+  {:dispatch [event]})
+
+(defn vector->string
+  "Converts numbers stored in vector into string,
+  e.g. [1 2 3 4 5 6] -> \"123456\""
+  [v]
+  (apply str v))
```
Comment (rasom) [inline src/status_im/hardwallet/common.cljs]: `clojure.string/join`

File: src/status_im/hardwallet/common.cljs [hunk 5]
```diff
@@ -0,0 +1,431 @@
...
+            (clear-on-card-connected)
+            (navigation/navigate-to-cofx :keycard-settings nil)))
+
+(fx/defn navigate-to-enter-pin-screen
+  {:events [:hardwallet/navigate-to-enter-pin-screen]}
+  [{:keys [db] :as cofx}]
+  (let [key-uid               (get-in db [:hardwallet :application-info :key-uid])
+        multiaccount-key-uid  (get-in db [:multiaccount :key-uid])
+        keycard-multiaccount? (boolean (get-in db [:multiaccount :keycard-pairing]))]
+    ;; TODO: WHY we check key-uid? If last oepration was with wrong card
```
Comment (rasom) [inline src/status_im/hardwallet/common.cljs]: is that a new comment? if so can you please elaborate?

File: src/status_im/hardwallet/common.cljs [hunk 6]
```diff
@@ -0,0 +1,431 @@
...
+                 (= key-uid multiaccount-key-uid)))
+      (fx/merge cofx
+                {:db (assoc-in db [:hardwallet :pin :current] [])}
+                (navigation/navigate-to-cofx :enter-pin-settings nil))
+      (unauthorized-operation cofx))))
+
+(defn- tag-lost-exception? [code error]
+  (or
+   (= code "android.nfc.TagLostException")
+   (= error "Tag was lost.")))
```
Comment (rasom) [inline src/status_im/hardwallet/common.cljs]: `"Tag was lost."` duplication

**Review by rasom — DISMISSED** [review]
In general: is there a particular reason why these changes can't be introduced in separate reviewable PRs? It's a bit hard to read and review, unclear what was added and what was just moved to a different ns and so on.
I will continue review after we sort this out.

File: src/status_im/hardwallet/common.cljs (hunk 5 above)
Comment (Ferossgp) [reply src/status_im/hardwallet/common.cljs]: Yes, If for example, a user wants to sign with the keycard and uses a wrong card, then cancel, then they go to change pin instead of seeing the process to change pin, unauthorized error appear and they can't do anything. This happens because the latest read of the card is stored in DB and we check based on it. But the user's intention is to use a different card, the correct one. IMO ideally this information should not be in DB and only read and passed as parameters to functions that needs it. 
Right now we have a lot of information related to keycard in DB and events work based on that info. This makes it harder to follow how state is passed through the flow. There are more errors like that, like the pin is not cleared in some places, and on some flows redirect is not correct.

File: src/status_im/hardwallet/sign.cljs [hunk 7]
```diff
@@ -66,6 +65,7 @@
   (log/debug "[hardwallet] sign success: " signature)
   (let [transaction (get-in db [:hardwallet :transaction])
         tx-obj      (select-keys transaction [:from :to :value :gas :gasPrice])]
+    (log/debug transaction)
```
Comment (Ferossgp) [inline src/status_im/hardwallet/sign.cljs]:
```suggestion
```

**Comment by vitvly** [comment]
@Ferossgp tested in on my device, all good, except for one error: when trying to login to a multiaccount and using another Keycard, the "Looks like you’ve tapped a wrong keycard" dialog box will be shown. Tapping on a "Okay" button in it throws an error `no event handler registered for keycard.login.ui`.

**Comment by rasom** [comment]
@Ferossgp can you please add some descriptions of changes made in this PR?

**Comment by Ferossgp** [comment]
@rasom updated the PR description

**Comment by rasom** [comment]
@Ferossgp when I create a new account after entering passcode I see "looking for a card" sheet even if card is still tapped and connection hasn't been lost: is that expected? I thought it should appear only if card is not tapped

**Comment by hesterbruikman** [comment]
As discussed on Discord. PR introduced a bug with the 'Looks like you've tapped a wrong Keycard' screen. The button 'Okay, got it' button is unresponsive. The popover can't be dismissed, so the user gets stuck when accidentally tapping the wrong Keycard upon Unlock.

File: src/status_im/ui/screens/events.cljs (hunk 2 above)
Comment (Ferossgp) [reply src/status_im/ui/screens/events.cljs:206]: Mostly they are used to clean up stored in re-frame pin code. To avoid the leak of that pin in other pin screens better to not store it, and pass as an argument to events which will use it.

**Review by rasom — APPROVED** [review]

**Comment by churik** [comment]
#9365,  #9334, #9702, #9660 are fixed.

Generally: card states look amazing!


## Issue 1: can't finish card paring: redirect to 1 step after backing up seed phrase


**Steps:**
- try to reprouduce #9702 
- continue setup

Not possible to finish pairing card - after backing up seed phrase you redirected to 1 step (entering PIN) - like it is mentioned in issue #9704

[Status.log](https://github.com/status-im/status-react/files/4311821/Status.log)

If I start canceling on this screen, it will redirect me again to Step 3 - confirm your seed phrase (word number...)

The same happened after reopening app. So basically there is now way after  #9704 to finish setup with this card.
It blocks verification of #9626.

## Issue 2: still not able to create multiaccount after #9676 

Steps: 
- try to reporoduce #9676 
- try to finish setup

Expected result:
can finish

Actual result:
tried 3 times - once got java exception, and endless spinner in other cases
Logs:
- java exception:
[geth.log](https://github.com/status-im/status-react/files/4312273/geth.log)
[Status.log](https://github.com/status-im/status-react/files/4312274/Status.log)
- endless spinner:
[Status.log](https://github.com/status-im/status-react/files/4312285/Status.log)
Card is dead after that - I can't connect to it using cli:
```
INFO [03-10|14:19:56.770] waiting for a card                       package=status-go/cmd/keycard
INFO [03-10|14:19:56.772] card found                               package=status-go/cmd/keycard index=0

```

**Comment by churik** [comment]
Issue https://github.com/status-im/status-react/issues/9665 is still reproducible

**Comment by rasom** [comment]
@churik I believe we can fix https://github.com/status-im/status-react/issues/9676 and https://github.com/status-im/status-react/issues/9665 separately from this PR

**Comment by churik** [comment]
@rasom yes, we can, but currently according to Issue 2 https://github.com/status-im/status-react/pull/10015#issuecomment-597052779 - user can't finish setup and card is dead (like it is in https://github.com/status-im/status-react/issues/9764)

So maybe it is better to prevent users to use this flow (i.e. leave only "Cancel" for now and add some text for clarification)

#9665 absolutely can fix separately - it is just mentioned in PR as fixed.

**Comment by churik** [comment]
@Ferossgp 
Issue 2 I consider as fixed because it is a consequence of another issue - I tried with 2 other cards and couldn't reproduce.

As for issue 1: in https://github.com/status-im/status-react/issues/9702  workflow is still broken if canceling setup on "Pairing code and PUK" - in builds with https://github.com/status-im/status-react/commit/d110507ff65e0e699415bded1ea7458f99459d08 if you tap on "Cancel", you will be redirected to 1 step (entering PIN) - and can't proceed.

**Logs:**
[geth.log](https://github.com/status-im/status-react/files/4317905/geth.log)
[Status.log](https://github.com/status-im/status-react/files/4317903/Status.log)
App is stucking with endless spinner.

**Comment by churik** [comment]
> As for issue 1: in #9702 workflow is still broken if canceling setup on "Pairing code and PUK" - in builds with d110507 if you tap on "Cancel", you will be redirected to 1 step (entering PIN) - and can't proceed.

It is fixed for happy-path scenario, however if you enter wrong pin after back up seed phrase, workflow  will be broken.
Regardless you can reopen app and complete setup, so issue is not critical and will be reported / fixed separately.

It is huge piece of work, @Ferossgp .
Thanks!
