### PR TITLE
Reduce recording time to 1 minute

### LINKED ISSUE #13914: Long/heavy audio messages are not sent
# Bug Report

## Problem 
Audio messages longer than 1:25 (mostly with silence (no content)) get stuck in a pending state and never reach the recipient, relogin doesn't help. 
Probably the content of the message also affects the maximum length of a message that can be sent.

#### Expected behavior
Can send audio messages of any length (within 2 minutes) 

#### Actual behavior
Screenshot 2022-09-01 at 15 45 11

### Reproduction

1. Start 1-1 chat
2. Record an audio message longer than 1:25
3. Send

### Additional Information

- Status version: RC 1.20
- Operating System: Android, iOS

### Logs 
[geth.log](https://github.com/status-im/status-mobile/files/9470364/geth.log)

### PR DESCRIPTION
**Pull request by audriu**
temporary workaround for #13914

### Summary
Reduced voice message record time to 1 minute.

#### Platforms
- Android
- iOS

##### Functional
- 1-1 chats
- public chats
- group chats

### Steps to test

- Open Status
- [See here](https://github.com/status-im/status-mobile/issues/13914#:~:text=Actual%20behavior-,Reproduction,-Start%201%2D1)
- See if sent ok

status: ready

### CODE REVIEW

File: src/status_im/ui/screens/chat/audio_message/views.cljs [hunk 1]
```diff
@@ -49,7 +48,7 @@
 
 ;; maximum 2 minutes of recordings time
```
Comment (flexsurfer) [inline src/status_im/ui/screens/chat/audio_message/views.cljs]: comment should be 1 as well

File: src/status_im/audio/core.cljs [hunk 2]
```diff
@@ -16,7 +16,7 @@
                                :channels 1
                                :sampleRate 22050
                                :quality "medium" ; ios only
-                               :meteringInterval 50})
+                               :meteringInterval 100})
```
Comment (flexsurfer) [inline src/status_im/audio/core.cljs]: could you elaborate on how its related ?

**Review by jo-mut — APPROVED** [review]

File: src/status_im/ui/screens/chat/audio_message/views.cljs [hunk 3]
```diff
@@ -47,9 +46,8 @@
                    {:filename (str base-filename default-format)
                     :meteringInterval metering-interval}))
 
-;; maximum 2 minutes of recordings time
-;; to keep data under 900k
-(def max-recording-ms (* 2 60 1000))
+;; maximum 1 minutes of recordings time to keep data at certain size
```
Comment (flexsurfer) [inline src/status_im/ui/screens/chat/audio_message/views.cljs]: `minute`  , sorry ;)

**Review by flexsurfer — APPROVED** [review]

File: src/status_im/ui/screens/chat/audio_message/views.cljs (hunk 3 above)
Comment (audriu) [reply src/status_im/ui/screens/chat/audio_message/views.cljs]: ah yes

**Comment by churik** [comment]
@audriu thank you for fixing, please mind my commit while squashing.

**Comment by audriu** [comment]
@churik how exactly should I mind it?

**Comment by churik** [comment]
@audriu take it into squashed commit while squashing, do not delete

**Review by Parveshdhull — APPROVED** [review]
