### PR TITLE
Message input issues

### LINKED ISSUE #14362: Message input: issues, mentions
This is a list of some input field bugs. 

### ISSUE 1 (Android only) Mention list is not shown after typing @

**Steps:**

1. Type @ symbol in the input field
2. See if mention list is shown

**Actual result:** Mention list is not shown

**Expected result:** Mention list appears after typing @

https://user-images.githubusercontent.com/97245802/201714486-a293ae8b-e706-413a-ac26-34452ca593d3.mp4

### ISSUE 2 (Android only) Input field expands to the full heights of the screen after clearing it

**Steps:** 
1. Type some text in the input field
2. Clear text in the input field
3. Observe the result

**Actual result:** input field expands to the full heights of the screen when the keyboard is active

**Expected result:** input field preserves it's original size

https://user-images.githubusercontent.com/97245802/201713244-48d305ea-cf53-4b58-916c-d477262db0a0.mp4

### ISSUE 3 (Android/IOS) Input field containing multiline message scales down when closing keyboard

**Steps:** 

1. Type some multiline message in the input field
2. Close the keyboard
3. Observe the behaviour of the input field

**Actual result:** Input field scales down, the message becomes invisible (only first 2 lines are partially visible). Overall, manual expanding/collapsing of the input field does not work smoothly which is resulting in poor user experience.  

**IOS**

https://user-images.githubusercontent.com/97245802/201721675-7b3c5a6b-031a-4a13-8771-963407b8b26d.mp4

**Android**

https://user-images.githubusercontent.com/97245802/201721583-28fa4c82-19e3-4248-98d0-a4e420d854dd.mp4

### ISSUE 4 The messages and contact requests are not shown if one of the device change his time within settings

**Steps:** 
1. Send contact request as USER_A to USER_B
2. Accept the request
3. Create any chat (1-1, group, public, community)
4.  Change time to +1 within the settings of your device using USER_A
5. Send a message to USER_B in any created chat
6. Send contact request to USER_C

**Actual result:**
- USER_A and USER_B don't see each other messages after the time is changed within device settings
- USER_C does not see a contact request of USER_A

**Expected result:**
- Users see messages and contact requests of each other even if the time for a particular device is changed

**OS** Both Android and IOS

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #14362 

### Summary

Composer doesn't show correctly, And mention list is whited out and other minor issues

#### Platforms
- Android
- iOS

##### Functional

- 1-1 chats
- public chats
- group chats

status: wip

### CODE REVIEW

**Comment by VolodLytvynenko** [comment]
Hi, @ibrkhalil here is some issue related to edit message flow that would be also nice to fix in this PR.
**ISSUE 1. The message is doubled if a user goes back, then reopens chat and tries to edit the message**

**Steps to reproduce:**
1. Open any chat
2. Send the message
3. Open 'edit pop up'
4. Leave the edit pop-up as opened and tap 'back' button
5.  This chat again
6. Close 'edit' pop-up using [x] button
7. Open 'edit' pop-up again for the same message

**Actual result:**
The message is doubled within the input field
https://user-images.githubusercontent.com/52490791/205031376-4241fdfd-62d1-422b-a897-75bf255de7d8.mp4
**Expected result:**
The message is the same as it was set initially

**Comment by ibrkhalil** [comment]
> Hi, @ibrkhalil here is some issue related to edit message flow that would be also nice to fix in this PR. **ISSUE 1. The message is doubled if a user goes back, then reopens chat and tries to edit the message**
> 
> **Steps to reproduce:**
> 
> 1. Open any chat
> 2. Send the message
> 3. Open 'edit pop up'
> 4. Leave the edit pop-up as opened and tap 'back' button
> 5. This chat again
> 6. Close 'edit' pop-up using [x] button
> 7. Open 'edit' pop-up again for the same message
> 
> **Actual result:** The message is doubled within the input field https://user-images.githubusercontent.com/52490791/205031376-4241fdfd-62d1-422b-a897-75bf255de7d8.mp4 **Expected result:** The message is the same as it was set initially

Will fix, Thanks Vlad!

**Comment by ibrkhalil** [comment]
> Hi, @ibrkhalil here is some issue related to edit message flow that would be also nice to fix in this PR. **ISSUE 1. The message is doubled if a user goes back, then reopens chat and tries to edit the message**
> 
> **Steps to reproduce:**
> 
> 1. Open any chat
> 2. Send the message
> 3. Open 'edit pop up'
> 4. Leave the edit pop-up as opened and tap 'back' button
> 5. This chat again
> 6. Close 'edit' pop-up using [x] button
> 7. Open 'edit' pop-up again for the same message
> 
> **Actual result:** The message is doubled within the input field https://user-images.githubusercontent.com/52490791/205031376-4241fdfd-62d1-422b-a897-75bf255de7d8.mp4 **Expected result:** The message is the same as it was set initially


Can you please check if this is still reproducible on latest develop?

**Comment by qoqobolo** [comment]
Hi @ibrkhalil, thanks for working on these issues!
There are a few new ones I've found so far. Take a look, please.

> Can you please check if this is still reproducible on latest develop?

Yes, Issue 1 is still reproducible for me on latest develop

https://user-images.githubusercontent.com/67952253/205661116-b4dbd321-a376-414f-968e-24ad39462cbe.mp4

### ISSUE 2: (iOS only) Can't send a mention without a text after it
The name disappears from the mention on sending, only `@` is displayed in the message. If you add some text after the mention it works fine.

**Steps:**
1. Open any chat
2. Type `@` and select some name from the list
3. Send the message

https://user-images.githubusercontent.com/67952253/205661339-87f711ff-dd94-4799-a1b1-3be84ce9fcbc.MP4

### ISSUE 3: (Android and iOS) The composer is now taller so that the "Jump to" button now overlaps it

**Steps:**
1. Open any chat

Screenshot 2022-12-05 at 15 34 23

This is how it looks like on develop:

Screenshot 2022-12-05 at 15 35 22


### ISSUE 4: (Android and iOS) Can't expand the composer

**Steps:**
1. Open a chat
2. Try to pull up the composer to expand it

https://user-images.githubusercontent.com/67952253/205664257-f2b04c44-e9cf-41de-b85c-930e0d670acd.MP4

**Comment by qoqobolo** [comment]
### ISSUE 5: The composer stops expanding after 13th line

I can see that the original issue (https://github.com/status-im/status-mobile/issues/14362#issuecomment-1326541622) is fixed, but I wanted to let you know that there is a not entirely clear composer behavior in this case.

If you start typing text wrapping it on new lines, then it works fine until the 13th line, then the composer starts to behave not quite as expected. After wrapping to line 14, the keyboard collapses and you can't continue typing normally.

On iOS, the UI freezes completely after line 14.

Android:

https://user-images.githubusercontent.com/67952253/205668680-d2c376e2-205e-4f78-8007-24430b65dffa.mp4

**Comment by du82** [comment]
The text input is invisible in all chats, same with mentions.

https://user-images.githubusercontent.com/65834069/205671595-3a3a7987-d0a4-43a1-8f3e-7d63eb6e2dd5.mp4

**Comment by du82** [comment]
The Jump To button should also be behind the bottom sheet

**Comment by VolodLytvynenko** [comment]
Hi @ibrkhalil here is also one additional issue related to message inputs. How it'll be better, to fix it within this PR, or I can create it as a separate task?

**ISSUE 6 The last message is not visible and input field is not tappable after user goes to the list of chats, then goes back to the 1-1 chat**

**ENV:** Huawei P-20 light. Android version: 9

**Steps to reproduce:**
1. Create a new 1-1 chat or Clear the history of the existing one
2. Open the current chat again
3. Send 1 or 2 messages
4. Tap the 'back' button
5. Open chat again
6. Tap somewhere out to remove the cursor from a text field
7. Try to tap back to the text field and scroll to the bottom

**Actual result:**
https://user-images.githubusercontent.com/52490791/205884960-72ec52fd-aa3f-405a-a6c5-41e7feb96b94.mp4

- The textbox is not tappable
- The last messages are not fully shown even after scrolling down

**Expected result:**
- The textbox is tappable
- The last messages are shown after scrolling down

**Logs:**
[Status.log](https://github.com/status-im/status-mobile/files/10166411/Status.log)
[geth.log](https://github.com/status-im/status-mobile/files/10166413/geth.log)

**Comment by du82** [comment]
The text input is still impossible to read in light mode, although multi-line input seems to be fixed.

https://user-images.githubusercontent.com/65834069/206918811-243e1dfa-9642-4de6-8272-e0fbf5722b0d.mp4

**Comment by du82** [comment]
It would also be great if the keyboard didn't pop up immediately when I open a chat. Signal, Discord, Telegram, and most other apps keep it hidden, and it's expected behavior to tap the chat box if you want to type.

**Comment by ibrkhalil** [comment]
> It would also be great if the keyboard didn't pop up immediately when I open a chat. Signal, Discord, Telegram, and most other apps keep it hidden, and it's expected behavior to tap the chat box if you want to type.

I'll disable auto focus on the input field and ask Andrey about it .. @flexsurfer what do you think ?

**Comment by ibrkhalil** [comment]
> Hi @ibrkhalil, thanks for working on these issues! There are a few new ones I've found so far. Take a look, please.
> 
> > Can you please check if this is still reproducible on latest develop?
> 
> Yes, Issue 1 is still reproducible for me on latest develop
> 
>  video_2022-12-05_15-26-15.mp4 
> ### ISSUE 2: (iOS only) Can't send a mention without a text after it
> The name disappears from the mention on sending, only `@` is displayed in the message. If you add some text after the mention it works fine.
> 
> **Steps:**
> 
> 1. Open any chat
> 2. Type `@` and select some name from the list
> 3. Send the message
> 
>  IMG_1268.MP4 
> ### ISSUE 3: (Android and iOS) The composer is now taller so that the "Jump to" button now overlaps it
> **Steps:**
> 
> 1. Open any chat
> 
> Screenshot 2022-12-05 at 15 34 23
> 
> This is how it looks like on develop:
> 
> Screenshot 2022-12-05 at 15 35 22
> 
> ### ISSUE 4: (Android and iOS) Can't expand the composer
> **Steps:**
> 
> 1. Open a chat
> 2. Try to pull up the composer to expand it
> 
>  IMG_1269.MP4

Hey Diana
I couldn't reproduce issue 1 on my branch, Kindly take a look when you have time

**Comment by flexsurfer** [comment]
> > It would also be great if the keyboard didn't pop up immediately when I open a chat. Signal, Discord, Telegram, and most other apps keep it hidden, and it's expected behavior to tap the chat box if you want to type.
> 
> I'll disable auto focus on the input field and ask Andrey about it .. @flexsurfer what do you think ?

we didn't have auto focus enabled before, so it should be disabled

**Comment by VolodLytvynenko** [comment]
hi @ibrkhalil thanx for your job. ISSUES 2, 4, 5, 6 fixed. 1st is not able to be reproduced due new ISSUE 9. Please, take a look at the the following issues

**ISSUE 7: The input message is expanded to much if long text is pasted and sent**
**Steps to reproduce:**
1. Open 1-1 chat
2. Paste a long text (500 chars at least)
3. Tap 'send' button

**Actual result:**
The textbox is expanded to much if 'send' button is tapped
https://user-images.githubusercontent.com/52490791/207068085-157ef6cd-186c-4c13-868d-075ebc71da8e.mp4

**Expected result:**
The textbox goes back to default expanding after 'send' button is tapped

**Env:** For androids only. In my case Device: Samsung Galaxy S21. OS: Android, v11.0.

**ISSUE 8. The text is not visible for dark mode. @ibrkhalil should it be done within scope of this PR?**
**Steps to reproduce:**
1. Select dark mode
2. Open 1-1 chat
3. Type any text within textbox

**Actual result:**
The text is not visible
image

**Expected result:**
Text input is visible on the dark mode


@ibrkhalil currently this issue is reproducible on the dev branch also.  Can you fix it within current PR or it'll be better to create it separatly?
**ISSUE 9. The text is not saved in textbox after current text is typed, then user taps 'back' button, then reopens the chat** - 

**Steps to reproduce:**
1. Open 1-1 chat
2. Type any text in the textbox
3. Tap 'back' button
4. Reopen the current chat

**Actual result:**
The text is not shown as saved within textbox after chat is reopened
https://user-images.githubusercontent.com/52490791/207077816-c4dbee3c-5a70-43c7-a50d-113863a75b26.mp4

**Expected result:**
Text is shown as saved within textbox after user reopens the chat

**ISSUE 10: The ens is not resolved into the chats after @ is entered** 

**Steps to reproduce:**
1. UserA and UserB are contacts
2. Set ens for UserB
3. Go to 1-1 chat as UserA
4. Type @

**Actual result:**
The 3 random name of userB are shown after @ is typed

**Expected result:**
Ens of UserB is shown and able to be mentioned by his ENS

**Comment by ibrkhalil** [comment]
I don't have an account with ENS to test, Can you provide me with one in a DM please ?
@VladimrLitvinenko

**Comment by du82** [comment]
The other problems I mentioned have been fixed, although if I add lots of lines (or write a long message) then delete it all and minimize the bottom sheet, it stays large

https://user-images.githubusercontent.com/65834069/207104821-9bed42c9-3ff1-48f9-ac88-f1cc5e7ff44f.mp4

**Comment by flexsurfer** [comment]
> The other problems I mentioned have been fixed, although if I add lots of lines (or write a long message) then delete it all and minimize the bottom sheet, it stays large
> 
>  22-12-12-10-50-22.mp4

thats fine because it's a rare case , input component get's bigger but doesn't shrink back, so there is no simple solution for that

**Comment by ibrkhalil** [comment]
> The other problems I mentioned have been fixed, although if I add lots of lines (or write a long message) then delete it all and minimize the bottom sheet, it stays large
> 
>  22-12-12-10-50-22.mp4

Will take a look

**Comment by ibrkhalil** [comment]
> > The other problems I mentioned have been fixed, although if I add lots of lines (or write a long message) then delete it all and minimize the bottom sheet, it stays large
> > 22-12-12-10-50-22.mp4
> 
> Will take a look

I made composer get minimized when it's empty, I hope that helps
I think the better approach was to make the `height` and spacing get calculated when deleting text too

**Comment by flexsurfer** [comment]
@VladimrLitvinenko @ibrkhalil what if we merge this PR and create a new task for the remaining issues? WDYT?

File: src/status_im/ui2/screens/chat/composer/input.cljs [hunk 1]
```diff
@@ -297,7 +301,7 @@
                                 (let [text-input-handle (rn/find-node-handle @text-input-ref)]
                                   (oops/ocall manager :startActionMode text-input-handle))))
 
-      :render
+      :reagent-render
```
Comment (flexsurfer) [inline src/status_im/ui2/screens/chat/composer/input.cljs:304]: could you elaborate?

File: src/status_im/ui2/screens/chat/composer/view.cljs [hunk 2]
```diff
@@ -19,33 +19,42 @@
...
+      (do (swap! context assoc :state :max) max-y)
       (if (< (:y @context) max-y)
         (+ (:y @context) added-value)
-        (do
-          (swap! context assoc :state :max)
-          max-y)))
-    (do
-      (swap! context assoc :state :min)
-      min-y)))
+        (if (<= 5 num-lines)
```
Comment (flexsurfer) [inline src/status_im/ui2/screens/chat/composer/view.cljs:29]: `(> num-lines 5)` more readable no ?

**Review by flexsurfer — APPROVED** [review]

File: src/status_im/ui2/screens/chat/composer/input.cljs (hunk 1 above)
Comment (ibrkhalil) [reply src/status_im/ui2/screens/chat/composer/input.cljs:304]: I think the default is `reagent-render` for class based components
https://github.com/reagent-project/reagent/blob/master/doc/CreatingReagentComponents.md
```
Rookie mistake

In the code sample above, notice that the renderer function is identified via an odd keyword in the map given to reagent/create-class. It's called :reagent-render rather than the shorter, more obvious :render.

Its a trap to mistakenly use :render because you won't get any errors, except the function you supply will only ever be called with one parameter, and it won't be the one you expect. https://github.com/reagent-project/reagent/issues/47#issuecomment-61056999.
```

Comment (ibrkhalil) [reply src/status_im/ui2/screens/chat/composer/input.cljs:304]: > @VladimrLitvinenko @ibrkhalil what if we merge this PR and create a new task for the remaining issues? WDYT?

What's left is the ens mention issue, Can we make it in another GitHub issue?
CC: @VladimrLitvinenko @pavloburykh @churik

**Comment by VolodLytvynenko** [comment]
Hi @flexsurfer, @ibrkhalil . Thank your for your worl. ISSUES 7,8 are fixed. Current PR still contains some issues. Some of them are minor, but because of their number the general usage is not convenient. Reported with medium and high priority. As for me it'll be nice to fix only 11 , 13, 14 in the current PR. Or better to create follow ups? How do you think?

**ISSUE 11 The textbox is too little expanded after the text is pasted and it is hard to expand it manually then**
1. Copy some long text into buffer
2. Open 1-1 chat
3. Paste the text into textbox -> tap ‘send’ button
4. Paste the text into textbox one more time
5. Try to expand textbox manually

**Actual result**
- The textbox is not fully expanded after step 4
- The textbox is not able to be expanded manually. It is luggy after each attempting to expand it
https://user-images.githubusercontent.com/52490791/207575967-3b6b9bc5-cfeb-4fd1-ba3b-e831238d66e7.mp4

**Expected result**
- The textbox is expanded properly related to the size of the pasted text
- Current textbox can be easily to be expanded manually

**ENV:** Samsung Galaxy S20+ v10, Huawei p20 light

**ISSUE 12 Cursor is not able to be located during message editing if several rows are in the message** it is reproducible in 20% of cases. Can be fixed as separate follow up

**Steps to reproduce:**
1. Send the message that contain at least 2 rows
2. Tap on the message -> Tap 'edit message'
3. Try to edit different rows

**Actual result:**
The edit textbox is jumping after trying to tap on the particular row to edit it
https://user-images.githubusercontent.com/52490791/207578821-28d34e47-d140-4ba2-a9b1-f5156198a5a7.mp4

**Expected result:**
The edit textbox tappable and cursor easily appears on the location where the user tap

**ENV:** Samsung Galaxy S20+ v10, Huawei p20 light

**Additional info:**
Reproducible in 20% of cases. If it is not reproduced at first, then do the following steps:
1. Go back to the chat list
2. Open chat again
3. Repeat steps described into the ISSUE

**ISSUE 13 The textbox is shown as focused after chat is opened as result user can't do anything unless message is sent**
**Steps to reproduce:**
1. Create new 1-1 chat with the contact
2. Go to the contacts
3. Tap on the 'chat' icon of the user
image
4. Go to the list of chats
5. Open the 1-1 chat

**Actual result:**
- The textbox is shown as focused after chat is opened
- User can't close it unless some message is sent

https://user-images.githubusercontent.com/52490791/207583532-65ece7e8-f1c4-49d0-aed1-6d42edf67322.mp4
image

**Expected result:** 
The input textbox is not focused
image

**ENV:** Samsung Galaxy S20+ v10, Huawei p20 light

**ADDITIONAL INFO:**
This defect is reproducible in 40% of cases. If it is not reproduced at first, then do the following steps:
1. Tap 'back' button in order to be navigated to the chat list
2. Open chat again

**ISSUE 14 The all rows of text are not shown if 'edit' button is tapped**
**Steps to reproduce:**
1. Send the message with at least 2 rows
2. Tap on it -> tap 'edit' button

**Actual result:**
Only first row is visible. Cursor is located on the end of the first row

https://user-images.githubusercontent.com/52490791/207586645-c3a838ce-315d-4473-92b3-81a9d723872e.mp4


**Expected result:**
Telegram solution: All row are visible. Cursor is located on the last row after edit button is tapped

https://user-images.githubusercontent.com/52490791/207586837-f1e28764-8d16-4a62-8813-74015975a252.mp4



**ISSUE 15 The user is not navigated to the new message after  user scrolls up, then message is sent** - can be fixed separately as follow up

**Steps to reproduce:**
1. Create several long messages into 1-1 chat
7. Scroll to the up
8. Send new message

**Actual result:**
The user is not autoscrolled to the bottom and as a result the sent message is not visible

**Expected result:**
The user autosrolled to the last message after its sending and as result the user sees current message

**Comment by ibrkhalil** [comment]
> VladimrLitvin

Can we make them all as a follow up in another issue, Assign it to me so that we can merge this one as a checkpoint ?
@VladimrLitvinenko

**Comment by VolodLytvynenko** [comment]
> > VladimrLitvin
> 
> Can we make them all as a follow up in another issue, Assign it to me so that we can merge this one as a checkpoint ? @VladimrLitvinenko

Agree. A lot of job has been done in this PR. Lets merge it. All the unfixed issues will be added in follow up issue.

**Comment by J-Son89** [comment]
> > VladimrLitvin
> 
> Can we make them all as a follow up in another issue, Assign it to me so that we can merge this one as a checkpoint ? @VladimrLitvinenko

please check with @flexsurfer before merging as he is refactoring some areas around this. 👍

**Comment by flexsurfer** [comment]
> > > VladimrLitvin
> > 
> > 
> > Can we make them all as a follow up in another issue, Assign it to me so that we can merge this one as a checkpoint ? @VladimrLitvinenko
> 
> please check with @flexsurfer before merging as he is refactoring some areas around this. 👍

thanks, yeah I'm waiting this PR to start moving composer , so lets merge, i'll move, and then continue fixing issues

**Comment by flexsurfer** [comment]
cc @OmarBasem  there will be conflicts with your PRs, @ibrkhalil

**Comment by VolodLytvynenko** [comment]
List of Follow up:
* [x] The textbox is too little expanded after the text is pasted and it is hard to expand it manually then https://github.com/status-im/status-mobile/issues/14534
* [x] Cursor is not able to be located during message editing if several rows are in the message https://github.com/status-im/status-mobile/issues/14535
* [x] The textbox is shown as focused after chat is opened as result user can't close it unless starts typing https://github.com/status-im/status-mobile/issues/14536
* [x] All rows of text are not shown if the 'edit' button is tapped on the created message https://github.com/status-im/status-mobile/issues/14537
* [x] The user is not navigated to the new message after a user scrolls up, the message is sent https://github.com/status-im/status-mobile/issues/14539
* [ ] The ENS is not resolved into the chats after @ is entered https://github.com/status-im/status-mobile/issues/14540
* [x] The input textbox is not tappable if message is typed into buffer of the chat, then current chat is reopened https://github.com/status-im/status-mobile/issues/14542
