### PR TITLE
[#11216] Fix moving cursor after pressing mention suggestion on samsung device

### LINKED ISSUE #11216: Cursor moved in the middle of ENS name when typing message with mentioned user
# Bug Report

## Problem

Mentions can be located by ENS/nickname/three-words name. 
In case user has ENS name set, - in the input field it's mention displays ENS name (disregard it was searched by nickname or three-words name or ENS). But when I continue typing message after selecting user from mention list, - cursor automatically moves in the middle of mention (to the point when I entered several chars before selecting user for mention).
Please see gif below for better understanding. 

Could not reproduced with nicknames/three-word names
Could not reproduce on iOS, but on Android 9 and Android 8 

#### Expected behavior

User continue typing from the place after ENS name in mention used

#### Actual behavior

Note here cursor shifted by itself to the point I stopped typing ENS name

2020_09_23_15_24_03_trim

### Reproduction

- Open Status and create new account
- Add new user by ENS name (e.g. 'statuse2e')
- Put cursor in the input field
- Type `@stat`
- Tap upon 'statuse2e' user from suggested mentions list
- Continue typing text

### Additional Information

- Status version: develop 1.7
- Operating System: Android9, Android8

### PR DESCRIPTION
**Pull request by rasom**
fix #11216

based on https://github.com/nikolaiwarner/react-native-text-input-reset from this discussion https://github.com/facebook/react-native/pull/12462

status: ready

### CODE REVIEW

File: src/status_im/native_module/core.cljs [hunk 1]
```diff
@@ -380,3 +380,7 @@
 (defn deactivate-keep-awake []
   (log/debug "[native-module] deactivateKeepAwake")
   (.deactivateKeepAwake ^js (status)))
+
+(defn reset-keyboard-input [input selection]
+  (log/debug "[native-module] resetKeyboardInput")
+  (.resetKeyboardInputCursor ^js (status) input selection))
```
Comment (flexsurfer) [inline src/status_im/native_module/core.cljs]: we don't have the implementation in objc. ? how will it work on ios ?

Comment (rasom) [reply src/status_im/native_module/core.cljs]: It won't be called in objc as it is not needed there. It is not needed even on all Androids. I will add some comments now

Comment (rasom) [reply src/status_im/native_module/core.cljs]: added comment

**Review by flexsurfer — APPROVED** [review]
