### PR TITLE
[#9446] Resume logging when connection to card is restored

### LINKED ISSUE #9446: Connection with card is not restored if it was lost during login
# Bug Report

## Problem
After interrupting connection with the card during log in it is not restoring after tapping card again, so you need to enter PIN again.
#### Expected behavior
connection is restored

#### Actual behavior
endless spinner 
photo_2019-11-14 11 01 30

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create account with KeyCard
- Log out
- enter PIN to login and put card off from the phone to interrupt connection
- tap card back again

### Additional Information

- Status version: nightly 14/11/2019
- Operating System: Android

### PR DESCRIPTION
**Pull request by rasom**
fix #9446 

Currently there are two ways to initiate logging in with keycard:
- enter PIN code and after that connect card to the phone
- connect card to the phone and enter PIN after that

Before this commit in both cases when connection to the keyacrd was lost
and then restored, logging in didn't resume. In result a user saw a
pop-up with endless spinner.

The reason of this bug was that `:on-card-connected` and `:on-card-read`
actions were not restored in app-db after losing connection to the card.

This commit introduces helper functions for both `:on-card-connected` and
`:on-card-read` which allow to reset these values and stash them until
particular flow of calls to keycard will be finished. In case if
connection was lost before the flow is finished the valueas are restored
so that it can be succesfully resumed on th next connection.

Also a banch of log entries were added to simplify debugging of
interactions with keycard and native module.

status: ready

### CODE REVIEW

**Review by vitvly — APPROVED** [review]

**Comment by churik** [comment]
Tested lost connection to the card during:
- multiaccount creation
- enter PIN code and after that connect card to the phone
- connect card to the phone and enter PIN after that
- canceling login when the connection is lost
Looks good to me.


Device: LG V20
OS: Android 8

File: src/status_im/native_module/core.cljs [hunk 1]
```diff
@@ -14,46 +15,56 @@
 (def adjust-resize 16)
 
 (defn clear-web-data []
+  (log/debug "[native-module] clear-web-data")
```
Comment (flexsurfer) [inline src/status_im/native_module/core.cljs:18]: do you want to merge all these logs ?
