### PR TITLE
fix: display value decimals instead of using exp notation

### LINKED ISSUE #9389: Transaction's amount is shown in exponential notation
# Bug Report

#### Expected behavior

Transaction's amount and fee are shown as regular numbers

[comment]: # (Describe what you expected to happen. Please include designs if possible.)

#### Actual behavior
Transaction's amount is shown in exponential notation.

[comment]: # (Describe what actually happened. Please include screenshots if possible.)

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

Try to send 0.00000000000001 ETH and see values amount value in transaction sheet.

### PR DESCRIPTION
**Pull request by richard-ramos**
fixes #9389

### Summary
Displays the amounts in wallet and chat with decimal values instead of using exponential notation

##### Functional

- 1-1 chats
- wallet / transactions

status: ready

### CODE REVIEW

**Review by jrainville — COMMENTED** [review]
Looks good. Does it make it display 18 decimals or something though?

File: src/status_im/ui/screens/signing/views.cljs [hunk 1]
```diff
@@ -182,7 +182,7 @@
       :error amount-error
       :accessories [[react/view {:style {:flex-direction :row}}
                      [react/nested-text {:style {:color colors/gray}}
-                      [{:style {:color colors/black}} (utils/format-decimals amount 6)]
+                      [{:style {:color colors/black}} (str amount)]
```
Comment (flexsurfer) [inline src/status_im/ui/screens/signing/views.cljs]: we need to keep this

Comment (flexsurfer) [reply src/status_im/ui/screens/signing/views.cljs]: this is by design

**Comment by richard-ramos** [comment]
i.e.: `10200000` wei will be displayed as `0.0000000000102`, which is the value in decimals that the user enter in the send transaction screen. 

Since the amount of decimals that a transaction will have is specified by the user, I think it's okay to show the same decimal precision, otherwise we'll end up with transactions sending 0.00000 eth which is not the real amount. 

Contract interactions will be displayed as usual with fees being limited to 6 decimals (I did not make changes on that regard)

File: src/status_im/ui/screens/signing/views.cljs (hunk 1 above)
Comment (richard-ramos) [reply src/status_im/ui/screens/signing/views.cljs]: so, it's okay if it shows `0.00000` if the number is very small?

Comment (flexsurfer) [reply src/status_im/ui/screens/signing/views.cljs]: mhmh, thats not expected for sure :) @errorists any ideas? we did this with Andrey, but not sure why we missed this case

Comment (richard-ramos) [reply src/status_im/ui/screens/signing/views.cljs]: Screenshot from 2020-04-16 12-03-41
For reference, this is how it currently looks in this PR,   notice how the amount at the top contains all the decimals but the amount+fee below only shows the first 6

**Review by flexsurfer — APPROVED** [review]

**Comment by Serhy** [comment]
@richard-ramos could you please rebase develop here, - iOS fails to build by some reason

**Comment by Serhy** [comment]
I've rebased develop.

**Comment by Serhy** [comment]
Looks good to me! (tested iPhoneX iOS13.3 and Samsung J7 Android 8.1)
Thanks you @richard-ramos

**Comment by flexsurfer** [comment]
@richard-ramos could you pls squash commits

**Comment by richard-ramos** [comment]
@flexsurfer, Done!
