### PR TITLE
Set max decimal places at 6 for signing sheet

### LINKED ISSUE #9235: Amount and Network Fee text overlap in 'Sending' screen when there are long values
# Bug Report

## Problem
Transaction amount and network fee often calculated up to eighteenth digit precision  (in case of 18-decimals asset). In that case the 'Amount' and 'Network Fee' text on the 'Sending...' screen overlapped by it's value. 

#### Expected behavior
Long values of amount and network fee does not overlap the text

`I would ask to truncate … the numeric values at the end so that the entire text label of Amount / Network Fee is visible. Both are already displayed in their entirety in the header of the bottom sheet.`

#### Actual behavior
Screenshot 2019-10-18 at 09 48 49

### Reproduction

- Open Status and create new account
- Navigate to `Wallet` -> `Status account `-> `Send` and select any Recipient
- Enter in Amount field the `0.0848969596969696969` value -> `Sign transaction`
- Tap `Network Fee` and update gas price to 1.0989898

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: develop nightly 0.14.0 (2019171002)
- Operating System: <Android and iOS>

### PR DESCRIPTION
**Pull request by acolytec3**
Fixes #9235 

### Summary

Amount and Network fee values overlap labels on signing sheet.  This resolves the issue by setting a maximum length and truncating any characters/digits in the value that exceed that length

### Review notes
As currently designed, it has the possibility of displaying a 0 in the last position of each value since I'm just trimming the string version of each value to fit in the field without overlapping the label.

#### Platforms
- Android
- iOS

##### Functional

- wallet / transactions

### Steps to test

* Open Status and create new account
* Navigate to Wallet -> Status account -> Send and select any Recipient
* Enter in Amount field the 0.0848969596969696969 value -> Sign transaction
* Tap Network Fee and update gas price to 1.0989898
* Verify that amount and network fee amounts are truncated to 6 digits of precision.

status: ready 
Screenshot_20191115-113012

### CODE REVIEW

**Comment by acolytec3** [comment]
@StatusSceptre @rachelhamlin @errorists Submitted an initial PR.  I'm not 100% sure if this approach will work on all screens or not since I'm picking a maximum number of characters for the amount/network fee values based on when the overlap occurs on my Oneplus 6T.  What I don't know is if the size of the window and therefore the number of characters available for that field always scales exactly or if that maximum # characters will change based on the screen size or not.

**Review by 3esmit — DISMISSED** [review]
The code looks good, but build fails on lint check.

**Comment by rasom** [comment]
It will not work on all screens, for instance on galaxy s9 "Network fee" is truncated now:


imo preferred solution will be to set `:min-width` for these labels (in order to make sure that at least English version fits there) and rearrange ` :accessories` view of these `list-item`s so that the value will be truncated according to [react native's `:ellipsize-mode `property](https://facebook.github.io/react-native/docs/text#ellipsizemode). In this case calculation of length happens on native side and is flexible.

**Comment by acolytec3** [comment]
I wondered about that. I tried setting a minWidth prop on the labels and
setting an `ellipsizemode tail` on the two value fields but it didn't seem
like it did anything. The value fields still ran over the labels on larger
values and never actually ellipsized. Would redefining the title label as a
component with the minWidth solve that?

**Comment by rasom** [comment]
@acolytec3 agree, tried to play with that `list-item` component, and although the solution mentioned in my previous comment is definitely doable it is really hard to implement it using `list-item` and it is not worth efforts almost likely. I think we can just decrease `field-width` for fee field and go with that for now.

**Comment by acolytec3** [comment]
Sorry for slow follow up here. @rasom where are you suggesting to add that field-width prop. I've tried applying it to the labels and the nested text elements but seems like it was ignored by react.   Is it worth just don't something like setting the length of the calls equivalent to some maximum percentage of the screen width? We should be able to calculate the pixel width of the value strings given the font size and just tweak my formatted value component to truncate accordingly, I think anyway.

**Comment by flexsurfer** [comment]
@acolytec3 ,thanks for your effort, after discussion with @andmironov  we decided to go another way, and cut the number to 6 digits after the comma

**Comment by acolytec3** [comment]
Got it. Do you want me to revise my PR to reflect that or are you going to include in a separate commit?

**Comment by flexsurfer** [comment]
if you could revise would be great, thanks!

**Comment by acolytec3** [comment]
@flexsurfer @andmironov  Done.  Renders like this.  Is this what you have in mind?
Screenshot_20191115-113012

**Comment by flexsurfer** [comment]
great thanks @acolytec3 , only we don't need dots in the end anymore

**Comment by acolytec3** [comment]
@flexsurfer Removed the `...` in the latest commit.

File: src/status_im/ui/screens/signing/views.cljs [hunk 1]
```diff
@@ -242,14 +250,14 @@
                      " "
                      (str (:code wallet-currency))]]}]))
 
-(defn fee-item [prices wallet-currency fee-display-symbol fee gas-error]
+(defn fee-item [prices wallet-currency fee-display-symbol fee gas-error window-width]
```
Comment (flexsurfer) [inline src/status_im/ui/screens/signing/views.cljs]: is `window-width` still needed ?

**Comment by Serhy** [comment]
@acolytec3 could you also rebase develop please?

File: src/status_im/ui/screens/signing/views.cljs (hunk 1 above)
Comment (acolytec3) [reply src/status_im/ui/screens/signing/views.cljs]: Nope, removed in my latest commit.

**Comment by acolytec3** [comment]
@Serhy @churik  Squashed and rebased on `develop`.

**Comment by churik** [comment]
@acolytec3 can you please rebase your branch to current `develop`?

File: src/status_im/ui/screens/signing/views.cljs [hunk 2]
```diff
@@ -274,7 +282,8 @@
                   {:keys [amount-error gas-error]} [:signing/amount-errors (:address from)]
                   keycard-multiaccount? [:keycard-multiaccount?]
                   prices                [:prices]
-                  wallet-currency       [:wallet/currency]]
+                  wallet-currency       [:wallet/currency]
+                  window-width [:dimensions/window-width]]
```
Comment (flexsurfer) [inline src/status_im/ui/screens/signing/views.cljs]: @acolytec3 and here we need to remove `window-width`

Comment (acolytec3) [reply src/status_im/ui/screens/signing/views.cljs]: Done.

**Comment by flexsurfer** [comment]
@acolytec3 would be super nice to move this function to utils and write a few unit tests for it, but it's up to you :)

**Comment by acolytec3** [comment]
@flexsurfer So just replace the `formatted-value` component with a function that returns the truncated string set to how ever many units of precision?

**Comment by flexsurfer** [comment]
but `formatted-value-item` function returns a string, so just move it to utils ns and rename probably, also we could parametrize 6, number of digits, smth like `format-decimals [value num]` , `(format-decimals 0.001234552, 6)`

**Comment by acolytec3** [comment]
@flexsurfer Sure, happy to.

**Comment by acolytec3** [comment]
@flexsurfer Done, rebased on `develop` and ready for testing again.

**Review by flexsurfer — APPROVED** [review]
Nice! Thanks!

**Comment by acolytec3** [comment]
These don't feel like issues related to the code in this PR, right?

**Comment by flexsurfer** [comment]
@Serhy  on it

**Comment by Serhy** [comment]
Two e2e test failed occasionally (we have issues in GH which should fix both)
Manually tested with iPhoneX, Galaxy Note 4 (Android 6.0.1), Samsung J7 (Android 8.1)б - Network fee and Amount items on signing transaction views from DApp or Wallet not overlapped by value anymore!
Well there is exceptional case of huge unrealistic amounts (integer value) which could be entered manually only which I consider as very edge case we may skip:

Screenshot 2019-11-21 at 18 12 49


Thanks @acolytec3 !

**Comment by acolytec3** [comment]
@Serhy Yep, this fix will only truncate values when the decimal places extend beyond 6 places.  My original PR would have taken the whole amount/fee into account when truncating but then you could have weird cases where the actual value is something like 123456789123.456 getting truncated to 1234567... which wouldn't be a good representation of the value.  

Glad it's working!
