### PR TITLE
Preserve text-input's default value

### LINKED ISSUE #8910: default value for input fields doesn't work
# Problem

In various input fields across the app, the input fields takes a default value, for instance when adding an account or when editing a custom mailserver. Currently only the placeholder is shown and not the current value if there is any.

### PR DESCRIPTION
**Pull request by vitvly**
Fixes #8910 

This issue was introduced in https://github.com/status-im/status-react/pull/8625. Consider this scenario:
  1. User navigates from Home view to Chat view
  2. Inputs some text into message box, but does not send it
  3. Goes back to Home and then again to Chat
  4. The text entered at step 2 is missing, because it's being set via `default-value` prop, and it is erased in `on-will-blur` navigation events handler.

After adding logging it turns out that text-input's `onRef` handler is invoked before the `onWillBlur` for Home view in step 3. So the default-value gets cleared, as we are not tracking which inputs belong to which views. Restoring `default-value` via `setNativeProps` seems to resolve this issue.

### CODE REVIEW

**Review by yenda — APPROVED** [review]
Awesome thanks!

**Comment by flexsurfer** [comment]
@siphiuel could please add a description, what the problem was and how it was fixed, thx

**Comment by vitvly** [comment]
@flexsurfer yes sure, added a description.

**Comment by yenda** [comment]
@siphiuel can you rebase?

**Comment by vitvly** [comment]
@yenda done

**Comment by churik** [comment]
@siphiuel would you mind to rebase it to check IOS as well?
Can't install previous due to signing problem

**Comment by churik** [comment]
@siphiuel can you please confirm that  it should work only for chat input field?
Consider following scenario:
- tap on + > Join public chat
- enter topic
- switch to wallet 
- switch to home

I would prefer to see input in this case.
It is reproducible for all fields except chat input here.
On 0.13.2 input is preserved.
So I suppose that is an issue.

File: components/src/status_im/ui/components/react.cljs [hunk 1]
```diff
@@ -126,14 +126,14 @@
             [text-class (dissoc options-with-style :nested?)]
             nested-text-elements)))
 
-(def text-input-refs (atom #{}))
+(def text-input-refs (atom {}))
```
Comment (yenda) [inline components/src/status_im/ui/components/react.cljs:133]: please add comment explaining what this is for

File: src/status_im/ui/screens/routing/core.cljs [hunk 2]
```diff
@@ -40,8 +40,8 @@
     :on-will-blur
     (fn []
       (reset! screen-focused? false)
-      (doseq [text-input @react/text-input-refs]
-        (.clear text-input)))}])
+      (doseq [[text-input default-value] @react/text-input-refs]
+        (.setNativeProps text-input (clj->js {:text default-value}))))}])
```
Comment (yenda) [inline src/status_im/ui/screens/routing/core.cljs:46]: explain

File: components/src/status_im/ui/components/react.cljs [hunk 3]
```diff
@@ -143,11 +143,8 @@
              :placeholder-text-color   colors/text-gray
              :placeholder              (i18n/label :t/type-a-message)
              :ref                      (fn [r] 
-                                         (if r
-                                           (when (nil? @input-ref)
-                                             (swap! text-input-refs conj r))
-                                           (when @input-ref
-                                             (swap! text-input-refs disj @input-ref)))
+                                         (when (and r (nil? @input-ref))
+                                           (swap! text-input-refs assoc r (:default-value options)))
```
Comment (yenda) [inline components/src/status_im/ui/components/react.cljs:153]: explain

File: components/src/status_im/ui/components/react.cljs [hunk 4]
```diff
@@ -126,14 +126,14 @@
...
             nested-text-elements)))
 
-(def text-input-refs (atom #{}))
+(def text-input-refs (atom {}))
 
 (defn text-input
   [options text]
   (let [input-ref (atom nil)]
     (reagent/create-class
       {:component-will-unmount #(when @input-ref
```
Comment (yenda) [inline components/src/status_im/ui/components/react.cljs:139]: explain

**Comment by vitvly** [comment]
@churik it must be because the chat title value is not stored in defaut-value property, will fix

File: components/src/status_im/ui/components/react.cljs [hunk 5]
```diff
@@ -126,14 +126,18 @@
             [text-class (dissoc options-with-style :nested?)]
             nested-text-elements)))
 
-(def text-input-refs (atom #{}))
+;; We track all currently mounted text input refs
+;; in a ref-to-defaultValue map
```
Comment (yenda) [inline components/src/status_im/ui/components/react.cljs:130]: put "`" "`" around `ref-to-defaultValue`

File: components/src/status_im/ui/components/react.cljs [hunk 6]
```diff
@@ -126,14 +126,18 @@
...
+;; so that we can clear them (restore their default values)
+;; when global react-navigation's onWillBlur event is invoked
```
Comment (yenda) [inline components/src/status_im/ui/components/react.cljs:132]: `onWillBlur`

Comment (yenda) [reply components/src/status_im/ui/components/react.cljs:132]: `

File: components/src/status_im/ui/components/react.cljs (hunk 5 above)
Comment (yenda) [reply components/src/status_im/ui/components/react.cljs:130]: `

Comment (yenda) [reply components/src/status_im/ui/components/react.cljs:130]: this symbol `

File: components/src/status_im/ui/components/react.cljs [hunk 7]
```diff
@@ -143,11 +147,10 @@
              :placeholder-text-color   colors/text-gray
              :placeholder              (i18n/label :t/type-a-message)
              :ref                      (fn [r] 
-                                         (if r
-                                           (when (nil? @input-ref)
-                                             (swap! text-input-refs conj r))
-                                           (when @input-ref
-                                             (swap! text-input-refs disj @input-ref)))
+                                         ;; Store input and its defaultValue
```
Comment (yenda) [inline components/src/status_im/ui/components/react.cljs:150]: defaultValue `

Comment (vitvly) [reply components/src/status_im/ui/components/react.cljs:150]: Added.

**Comment by vitvly** [comment]
@churik added defaultValue for inputs in `New Chat`/`New Public Chat` views

**Comment by churik** [comment]
Tested that https://github.com/status-im/status-react/issues/8600 is not reproducible and that input is preserved for  `New Chat`/`New Public Chat` views, Dapps, chat input field
