### PR TITLE
[#10312] Blocking user takes ~5-10s, and chats are emtpy during that …

### LINKED ISSUE #10312: Blocking user takes ~5-10s, and chats are emtpy during that time
# Bug Report

## Problem

When blocking user, all chats are empty for ~5-10s

#### Expected behavior

There are messages in the chat then blocking user

https://drive.google.com/file/d/16AK_y1vAKWHArxCnQ87rjsC-wYckNEjV/view

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #10312

### CODE REVIEW

File: src/quo/components/button/view.cljs [hunk 1]
```diff
@@ -81,16 +82,21 @@
...
          (= type :icon)
          [icons/icon icon {:color icon-color}]
 
-         (string? children)
+         (or (keyword? children) (string? children))
          [text/text {:weight          :medium
                      :number-of-lines 1
                      :style           {:color text-color}}
-          children]
+          (utils.label/stringify children)]
```
Comment (Ferossgp) [inline src/quo/components/button/view.cljs:99]: We want to have Quo as an independent library, but this couples the component hardly to the current status implementation of translations. If at some time we will want to separate the lib, or change the implementation of i18n then we will need to refactor Quo for that.

**Review by vitvly — APPROVED** [review]

**Comment by Serhy** [comment]
Tested on Android v8.1, v6.0.1, v9 and iOS13:
- Joined 10 public chats with 500 messages from 5 users
Blocking any users runs an animation an until it finished taps has no effect. Messages are blocked as expected, notifications (and messages) are not received from blocked contact.

Fixed e2e test, another one with send_transaction_with_custom_token known issue in github.
Thanks @flexsurfer , lets merge!
