### PR TITLE
Weak-password disallows confirm code step

### LINKED ISSUE #9453: Can open multiaccount with empty password if tap on "Next" quickly 2 times in a row
# Bug Report

## Problem
If tap quickly several times on the "Next" button on the "Select key storage" screen, one "Create your password" screen will be dismissed and you will be redirected directly to "Confirm your password" screen and can proceed with an empty screen.

#### Expected behavior
will be redirected to "Create your password" screen

#### Actual behavior
redirected "Confirm your password" screen and can proceed with an empty screen.

### Reproduction

- Open Status
- Tap on "Generate new key"
- Proceed to "Select key storage" screen
- tap "Next" quickly 2 times

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 15/11/2019
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by acolytec3**
fixes #9453 

### Summary

When creating a new account in intro-wizard, on "Select Key Storage" screen, there is a race condition where you can double tap "Next" and skip Create Password Screen and get to "Confirm Password" screen with a blank password.

This PR fixes this bug and doesn't allow user to proceed to "Confirm Password" screen until a password is entered and passes the weak password checks.

### Testing notes
Run ADB logs to see console error message that is printed when user double taps "Next" button.

#### Platforms

- Android
- iOS

##### Functional

-new account

##### Non-functional
NA

### Steps to test

* Open Status
* Tap on "Generate new key"
* Proceed to "Select key storage" screen
* tap "Next" quickly 2 times
* Verify that you can't navigate to "Confirm Password" screen and that "Still weak password so not proceeding" appears in ADB logs

status: ready

### CODE REVIEW

**Comment by acolytec3** [comment]
@churik Took a stab at this and seems to have been resolved in my PR.  @yenda @flexsurfer Any thoughts on the best way to throw an error in the logs?  It seems like this shouldn't be something the user is prompted about since it should only be done inadvertently.  Just leave the user on the Create Password screen until they enter something that satisfies the "weak password" check.

File: src/status_im/multiaccounts/create/core.cljs [hunk 1]
```diff
@@ -138,13 +138,17 @@
...
-  (let  [{:keys [step first-time-setup? selected-storage-type processing?]} (:intro-wizard db)]
+  (let  [{:keys [step first-time-setup? selected-storage-type processing? weak-password?]} (:intro-wizard db)]
     (cond (confirm-failure? db)
           (on-confirm-failure cofx)
 
           (= step :generate-key)
           (init-key-generation cofx)
 
+          (and  (= step :create-code)
+                (= (get-in db [:intro-wizard :weak-password?]) true))
```
Comment (flexsurfer) [inline src/status_im/multiaccounts/create/core.cljs]: i can see you destructured weak-password? in let why don't you use it here? and i'm not sure if we need a log so you can do smth like `(and  (= step :create-code) weak-password?) nil`

Comment (acolytec3) [reply src/status_im/multiaccounts/create/core.cljs]: @flexsurfer Just coding on not enough sleep.  Fixed in my latest commit.  I also replaced the logging message with a `nil` so should be ready for final review.

**Review by flexsurfer — APPROVED** [review]

**Review by vitvly — APPROVED** [review]

**Review by yenda — APPROVED** [review]

**Comment by yenda** [comment]
@acolytec3 thanks for another PR! You are killing it. Please make sure you sign your commit with GPG

**Comment by churik** [comment]
@acolytec3 
Couldn't find in logs "Still weak password so not proceeding" (fulladb logcat with `debug` level [logcat.log](https://github.com/status-im/status-react/files/3868903/logcat.log)) - but issue is not reproducible for sure.

Thanks a lot for your effort!

**Comment by acolytec3** [comment]
@churik Per the recommendation of @flexsurfer , I removed the logging in my latest commit.  It just returns a `nil` now when the navigation logic identifies this condition.  In my initial build, it was definitely showing the error log I'd put in there every time I tried to double tap the "Next" button though.  Glad it's working right now!
