### PR TITLE
[fix 8829] fix wrong password behavior on login

### LINKED ISSUE #8829: "Processing" instead of validation message in case if you entered invalid password when sign in
###  Description

*Type*: Bug

*Summary*: no validation error is shown when entering wrong password on login screen. Instead "Wrong password" endless "Processing" screen is shown.
Hopefully, that #8799 has the same cause - but in this case I can normally create account, logout and login after this error

#### Expected behavior
"Wrong password"

#### Actual behavior
Processing 
pr

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create account
- Log out
- Try to login with the wrong password

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 23/08/2019
[comment]: # (Android or iOS.)
- Operating System: Android, iOS

#### Logs

Full video and log: https://app.saucelabs.com/tests/6a640091d97947509e3d454ac7b07f90?auth=48fb9d4eafc80590ab1fb9b48178798c#58

### PR DESCRIPTION
**Pull request by yenda**
fix #8829

Use error field from login signal to check if an error occurred during login

### Steps to test
Tested on Android emulator

Try login with wrong password, then login with correct password

status: ready

### CODE REVIEW

File: src/status_im/signals/core.cljs [hunk 1]
```diff
@@ -1,20 +1,25 @@
...
 
 (fx/defn status-node-started
-  [{db :db :as cofx} event]
-  (login/multiaccount-login-success cofx))
+  [{db :db :as cofx} {:keys [error]}]
+  (if (empty? error)
+    (login/multiaccount-login-success cofx)
+    {:db (-> db
+             (update :multiaccounts/login dissoc :processing)
+             (assoc-in [:multiaccounts/login :error] (if (= error "file is not a database")
```
Comment (flexsurfer) [inline src/status_im/signals/core.cljs]: hm, is it temporary?

**Review by flexsurfer — APPROVED** [review]

File: src/status_im/signals/core.cljs (hunk 1 above)
Comment (yenda) [reply src/status_im/signals/core.cljs]: what do you mean? that is the error that status-go returns when there is a wrong password. I am not aware of possible other errors at the moment so I figured in case this happens we should just show them

**Comment by asemiankevich** [comment]
checked:

1. valid login attempt
2. invalid login attempt 
3. login with invalid -> valid password
4. same for adding ethereum address to multiaccount
5. transactions
6. force logout
7. save password

Looks okay to me, however not sure why iOS is not created:
i see this in logs 

```
8:47:51  [16:47:36]: ▸ Check dependencies
18:47:51  [16:47:36]: ▸ Code Signing Error: No signing certificate "iOS Distribution" found:  No "iOS Distribution" signing certificate matching team ID "DTX7Z4U3YA" with a private key was found.
```

https://ci.status.im/job/status-react/job/prs/job/ios/view/change-requests/job/PR-8894/6/execution/node/125/log/

@jakubgs maybe you can clarify?

**Comment by flexsurfer** [comment]
@yenda there is a change after this issue was tested, could you elaborate on this change? cc @asemiankevich

**Comment by yenda** [comment]
@flexsurfer it was a rebase

**Comment by asemiankevich** [comment]
@yenda @flexsurfer still looks good! Apart this iOS stuff %(
