### PR TITLE
[14429] Fix mentions

### LINKED ISSUE #14429: "Objects are not valid as a React child..." error when trying to mention chat member
**Steps:**
1. Start any chat
2. Try to mention another chat member (start typing @). In case of Android, after typing @ you should close chat and then try to open it again to reproduce a bug. In case of IOS - error will appear just after typing @ in chat input field
3. Observe the error

**Actual result:** Objects are not valid as a React child error appears

**Expected result:** no error

photo_2022-11-23 13 51 09

https://user-images.githubusercontent.com/97245802/203540920-6b2e0e00-000f-4a52-a9fa-731ba631499c.mp4

https://user-images.githubusercontent.com/97245802/203540944-d2b49c11-f9d4-4d22-becf-c7aabb965e1a.mp4

[Android logs.zip](https://github.com/status-im/status-mobile/files/10075189/Android.logs.zip)

### Additional Information

- Status version: nightly 
- Operating System: Android, iOS

[comment]: # (Please, add logs/notes if necessary)

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #14429
status: ready

### CODE REVIEW

File: src/status_im/ui2/screens/chat/composer/input.cljs [hunk 1]
```diff
@@ -172,21 +172,21 @@
...
-                            (if mentions-enabled
-                              (for [[index [type text]] (map-indexed
-                                                         (fn [idx item]
-                                                           [idx item])
-                                                         (<sub [:chat/input-with-mentions]))]
-                                ^{:key (str index "_" type "_" text)}
-                                [rn/text (when (= type :mention) {:style {:color colors/primary-50}})
-                                 text])
-                              (get @input-texts chat-id)))]
+        children          (reagent/as-element
```
Comment (flexsurfer) [inline src/status_im/ui2/screens/chat/composer/input.cljs]: just wondering what is the reason, because it worked fine before

File: src/status_im/ui2/screens/chat/composer/input.cljs [hunk 2]
```diff
@@ -172,21 +172,21 @@
...
+                           (if mentions-enabled
+                             (for [[index [type text]] (map-indexed
```
Comment (ilmotta) [inline src/status_im/ui2/screens/chat/composer/input.cljs]: I know you don't want to change the original implementation much, but the `for` macro surrounding the `map-indexed` seems unnecessary, i.e. we're looping twice.

```clojure
(map-indexed (fn [index [type text]]
               ^{:key (str index "_" type "_" text)}
               [rn/text (when (= type :mention) {:style {:color colors/primary-50}})
                text])
             (<sub [:chat/input-with-mentions]))
```

File: src/status_im/ui2/screens/chat/composer/input.cljs (hunk 1 above)
Comment (ibrkhalil) [reply src/status_im/ui2/screens/chat/composer/input.cljs]: Simply removing `[]` from `children` fixes the issue but I wanted to convert it to a reagent element instead
It was working before the PR that added RN selectable text input
https://github.com/status-im/status-mobile/commit/32d85d505986495190f05f7ea007c22dd48f88a3#r91057798

File: src/status_im/ui2/screens/chat/composer/input.cljs (hunk 2 above)
Comment (ibrkhalil) [reply src/status_im/ui2/screens/chat/composer/input.cljs]: Wow, I don't how I didn't notice this
Thanks Icaro!

**Review by flexsurfer — APPROVED** [review]

**Comment by ibrkhalil** [comment]
Oops my bad, I merged without waiting for QA
What should I do ?
@flexsurfer @pavloburykh

**Comment by churik** [comment]
It's fine if it is a fix and you verified it. No worries, next time better to test: bugfixes - up to dev, features/flows - required.
