### PR TITLE
Fix sticker pack installation buttons

### LINKED ISSUE #8936: Fix installation buttons for sticker packs
# Problem

There is a Status icon shown for a stickerpack which was bought with SNT. It is not shown for free stickerpack.

image

Align the icons with statuses using figma:

image

## Steps

1. recover `husband rough hotel obey annual you member reopen struggle air evoke taxi`
2. join public chat -> tap Stickers icon

## Build

nightly 6 Sep 2019, device - Samsung S10 Android 9

### PR DESCRIPTION
**Pull request by marcusrbrown**
Fixes #8936

### Summary

- Removes extra margin on SNT icon
- Fixes SNT icon display on owned sticker packs
- Distinguishes between free and owned sticker packs and displays appropriate label

### Steps to test

- Open Status
- Recover wallet with `husband rough hotel obey annual you member reopen struggle air evoke taxi`
- Join public chat
- Open Stickers
- View Sticker Packs

status: ready

### CODE REVIEW

**Comment by ghost** [comment]
Hey @igetgames, and thank you so much for making your first pull request in status-react! :heart: Please help us make your experience better by filling out this brief questionnaire https://goo.gl/forms/uWqNcVpVz7OIopXg2

**Comment by ghost** [comment]
### Pull Request Checklist
- [ ] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://docs.status.im/docs/build_status.html))?

File: src/status_im/ui/screens/stickers/views.cljs [hunk 1]
```diff
@@ -33,17 +33,16 @@
                                                    (or no-snt? not-enough-snt?) nil
                                                    :else (re-frame/dispatch [:stickers/buy-pack id price]))}
        [react/view (styles/price-badge (and (not (or owned (zero? price))) (or no-snt? not-enough-snt?)))
-        (when (and (not (zero? price))) ;(not no-snt?))
-          [icons/icon :icons/price {:color colors/white :container-style {:margin-right 8}}])
+        (when (and (not (zero? price)) (not owned))
```
Comment (yenda) [inline src/status_im/ui/screens/stickers/views.cljs]: rename it `owned?` please since it is a predicate

**Comment by yenda** [comment]
@errorists does it fix the issue?

IMG_0028
IMG_0030
IMG_0029
IMG_0027

File: translations/en.json [hunk 2]
```diff
@@ -314,7 +314,8 @@
     "mailserver-automatic": "Automatic selection",
     "currency-display-name-kzt": "Kazakhstan Tenge",
     "no-recent-chats": "There are no recent chats here yet. \nUse the (+) button to discover people \nto chat with",
-    "install": "Install",
+    "install": "↓ Install",
```
Comment (flexsurfer) [inline translations/en.json]: i'm not sure if we should use an image here @errorists ?

Comment (errorists) [reply translations/en.json]: image you mean the downward arrow? I think we should, why not?

Comment (yenda) [reply translations/en.json]: @flexsurfer means that here the arrow is an emoticon char not an image

**Comment by errorists** [comment]
So, on the buttons with the icon and SNT, the left margin is still too large, I believe that's caused by the left padding on the button. Would it help if I'd export the image asset without any padding? The alternative would be a conditional 0 left padding if there is an image inside or something to that effect.

File: translations/en.json (hunk 2 above)
Comment (flexsurfer) [reply translations/en.json]: downward arrow yes, do we have an image we can use ? i found only this one 
image

Comment (errorists) [reply translations/en.json]: if we have the choice it's actually better to use a character in the font, since it will ideally match the weight and size of the text next to it, producing a more visually pleasing and consistent look. It's actually what Apple did in iOS13, all icons were replaced by unicode characters in font files. [Apple Developer](https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview/)

Comment (errorists) [reply translations/en.json]: currently, we're limited to arrows as that's what provided in the font, but it's open source and we could expand it with all of our own icons if we'd wanted to. 
To sum up, if we're about to place any of these ← → ↙ ↘ ↖ ↗ ↑ ↓ ↪ ↩ ✓ ✗ next to text, it's better to just use a character and not an image :)

File: src/status_im/ui/screens/stickers/views.cljs (hunk 1 above)
Comment (marcusrbrown) [reply src/status_im/ui/screens/stickers/views.cljs]: I apologize since I'm new to Clojure, but where is it declared as a predicate? If I change it to `owned?` I get:

```sh
Figwheel: Compile Warning - Use of undeclared Var status-im.ui.screens.stickers.views/owned? in file src/status_im/ui/screens/stickers/views.cljs at line 36, column 45
```

**Comment by marcusrbrown** [comment]
> So, on the buttons with the icon and SNT, the left margin is still too large, I believe that's caused by the left padding on the button. Would it help if I'd export the image asset without any padding? The alternative would be a conditional 0 left padding if there is an image inside or something to that effect.

If the price icon is intended to be used in other places, reexporting it would be best. Let me know if you'd like me to add the conditional padding inside the price badge.

**Comment by yenda** [comment]
@errorists the message above was addressed to you, please provide the icon without padding

**Comment by rachelhamlin** [comment]
@igetgames just so you're in the know, we're currently at our team offsite in Istanbul and responding a bit more slowly than usual this week. We'll get you the icon and I'll pay the bounty as soon as this is merged. Thanks for your patience!

**Comment by marcusrbrown** [comment]
@rachelhamlin Understood, thanks for the heads up!

**Comment by errorists** [comment]
@igetgames hey, sorry once again for the delay. [Here's the updated asset](https://www.dropbox.com/sh/u582cr8zfcxhm0w/AAA5KFuG_Y6HLzYuUEsjMlMsa?dl=0), it's 16 by 16 in size without the added padding. 

This is how the button's padding should look like, basically 6px horizontally and align in the middle vertically.
Screenshot 2019-09-23 at 08 19 53

File: src/status_im/ui/screens/stickers/views.cljs (hunk 1 above)
Comment (yenda) [reply src/status_im/ui/screens/stickers/views.cljs]: @igetgames my bad I didn't see you answered, you have to rename it everywhere in the scope, the scope here is the whole function because owned is one of the arguments, so it means you rename owned to owned? everywhere within `price-badge` function here.

there is no such thing as declaring it as a predicate, by predicate I mean that it is a value that we expect to be truthy or falsy (false or nil in clojure). and by convention they are named with a `?` at the end to emphasize that.

**Comment by yenda** [comment]
Hey @igetgames ! Are you still planning on completing the issue?

**Comment by marcusrbrown** [comment]
> @igetgames hey, sorry once again for the delay. [Here's the updated asset](https://www.dropbox.com/sh/u582cr8zfcxhm0w/AAA5KFuG_Y6HLzYuUEsjMlMsa?dl=0), it's 16 by 16 in size without the added padding.
> 

@errorists Could you provide the icon in 24x24 and 64x64 for Android hdpi and xxxdpi?

**Comment by marcusrbrown** [comment]
> Hey @igetgames ! Are you still planning on completing the issue?

Yes, this PR is good to go except for the missing hdpi and xxxhdpi versions of `tiny_snt.png`.

File: src/status_im/ui/screens/stickers/views.cljs (hunk 1 above)
Comment (marcusrbrown) [reply src/status_im/ui/screens/stickers/views.cljs]: Understood, completed in c37c9aa.

**Comment by errorists** [comment]
@igetgames afaik we don't provide those and use only 1x 2x 3x resources in the app, [React Native will choose the closest appropriate option](https://facebook.github.io/react-native/docs/images).

**Comment by marcusrbrown** [comment]
@errorists Ah, ok.

In that case this PR is ready to roll.

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
@igetgames would you mind to rebase your PR to latest develop?
Seems that can be the reason why Android can't be built

**Comment by marcusrbrown** [comment]
> @igetgames would you mind to rebase your PR to latest develop?
> Seems that can be the reason why Android can't be built

I've rebased against latest develop.

**Comment by jakubgs** [comment]
Your android build works, but the CI job fails due to a test failure:
```
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'create-react-class'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.hookedLoader [as _load] (/home/jenkins/workspace/status-react_prs_android_PR-8985/target/test/test.js:14:10)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /home/jenkins/workspace/status-react_prs_android_PR-8985/target/test/reagent/impl/util.js:22:168
    at Object.<anonymous> (/home/jenkins/workspace/status-react_prs_android_PR-8985/target/test/reagent/impl/util.js:28:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
Error encountered performing task 'doo' with profile(s): 'test'
Subprocess failed
```

**Comment by churik** [comment]
@errorists would you mind to take a look?

**Comment by Serhy** [comment]
Tested with iOS12.4.1 and Android 8.1
&#8595; Free  &#8595; Install, Blue/Grey colour, green checkmark when sticker installed are aligned and displayed respectively between Sticker marked view and particular sticker view (sticker detail screen)

@errorists if you are OK with current state then lets merge PR?

**Comment by errorists** [comment]
✅ just tested, looks good. thanks @igetgames

**Comment by jakubgs** [comment]
Please first squash all the commits into one. I won't merge this as 6 different commits.

**Comment by flexsurfer** [comment]
thanks @igetgames , could you please squash commits please

**Comment by marcusrbrown** [comment]
I was at work earlier and couldn't respond. Here's the squashed commit as requested.

**Comment by rachelhamlin** [comment]
Hey, thanks so much @igetgames! Awesome work. I just paid this one out. Let me know if you'd like to take on any other issues.

**Comment by marcusrbrown** [comment]
> Hey, thanks so much @igetgames! Awesome work. I just paid this one out. Let me know if you'd like to take on any other issues.

Thanks! It was fun diving into Status, and I definitely will be applying to work on other issues.
