### PR TITLE
keycard bugfixes

### LINKED ISSUE #8989: "Keycard" is shown in profile for users who created account without keycard
###  Description
*Type*: Bug
*Summary*: was found during testing #8764 
no "Keycard" is expected for accounts, that are not created with keycard.
sdsdfsdfsdf

### Reproduction

- Open Status
- Create or restore account without keycard
- Open profile 

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: develop after merging #8764 
- Operating System: Android

### LINKED ISSUE #9023: Redirect to blank Unlock screen if tap "Cancel" during onboarding flow
###  Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug
*Summary*: app redirects to screen without accounts if tap "Cancel" during sign up or recovery flow. Reproducible for all flows with a keycard that should redirect to the initial state of app (during recovery and sign-in flow)

#### Expected behavior
main screen with carousel 

#### Actual behavior
photo_2019-09-23 13 28 11

### Reproduction

- Open Status
- Proceed to "Create a 6 digit passcode" screen
- Tap Cancel

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 23/09/2019
- Operating System: Android

### LINKED ISSUE #9028: Crash at attempt to use second multiaccount with keycard
###  Description

*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: if you have several keycards, at attempt to create a second account with keycard Status will crash.

#### Expected behavior
can use 2 accounts with keycard

#### Actual behavior
crash on "finishing up" stage and at attempt to login

### Reproduction

**Prerequisites:** have several keycards with pre-installed keycard applet

- Open Status
- Create account with keycard
- Log out
- Create second account with another keycard

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 24/09/2019
- Operating System: Android

#### Logs

Full logcat: [second_account.log](https://github.com/status-im/status-react/files/3647426/second_account.log)

### PR DESCRIPTION
**Pull request by dmitryn**
fixes #8989
fixes #9023
fixes #9028

### Summary

* Hide keycard option from profile settings for regular users
* Temporary hide "Add new account" option in Wallet for keycard users (it doesn't for keycard now #9019)
* Fix redirect when Cancel keycard setup pressed #9023
* Fix setting up 2 keycards on 1 phone #9028

status: ready

### CODE REVIEW

File: src/status_im/ui/screens/profile/user/views.cljs [hunk 1]
```diff
@@ -212,9 +216,11 @@
 
           ;; flatlist contents
           header               (header multiaccount)
+          keycard-account?   (boolean (get-in multiaccounts [address :keycard-key-uid]))
```
Comment (yenda) [inline src/status_im/ui/screens/profile/user/views.cljs]: is it mandatory to cast to boolean here?

File: src/status_im/ui/screens/wallet/accounts/views.cljs [hunk 2]
```diff
@@ -149,13 +149,17 @@
...
 (views/defview accounts []
-  (views/letsubs [{:keys [accounts]} [:multiaccount]]
-    [react/scroll-view {:horizontal true}
-     [react/view {:flex-direction :row :padding-top 11 :padding-bottom 12}
-      (for [account accounts]
-        ^{:key account}
-        [account-card account])
-      [add-card]]]))
+  (views/letsubs [{:keys [accounts address]} [:multiaccount]
+                  multiaccounts [:multiaccounts/multiaccounts]]
```
Comment (yenda) [inline src/status_im/ui/screens/wallet/accounts/views.cljs]: once login you should never rely on this subscription, it should even be dissoc at login in theory, why isn't keycard-key-uid stored in multiaccount as well?

Comment (dmitryn) [reply src/status_im/ui/screens/wallet/accounts/views.cljs]: @yenda right, i'd rather pull `keycard-key-uid` from `multiaccount`, but it's not there. Do you think we should add that once data arrives from status-go side in `get-config-callback`?

Comment (yenda) [reply src/status_im/ui/screens/wallet/accounts/views.cljs]: There is two options:
- it should be passed through `:multiaccount/login` which is dissoced in `multiaccount-login-success`
- or as you said, which is done for other stuff that is duplicated from multiaccounts/multiaccounts in the multiaccount settings but it's not correct, I have thought about fixing that for a while but didn't had time

File: src/status_im/ui/screens/profile/user/views.cljs (hunk 1 above)
Comment (dmitryn) [reply src/status_im/ui/screens/profile/user/views.cljs]: @yenda not mandatory as this value could be either truthy string or nil

File: src/status_im/ui/screens/wallet/accounts/views.cljs (hunk 2 above)
Comment (dmitryn) [reply src/status_im/ui/screens/wallet/accounts/views.cljs]: @yenda I just checked and there is `keycard-key-uid` value in `multiaccount` once you login. So i'm just getting that value from there, not from `multiaccounts/multiaccounts`

File: src/status_im/ui/screens/profile/user/views.cljs [hunk 3]
```diff
@@ -212,9 +216,11 @@
 
           ;; flatlist contents
           header               (header multiaccount)
+          keycard-account?   (boolean keycard-key-uid)
```
Comment (yenda) [inline src/status_im/ui/screens/profile/user/views.cljs]: if it doesn't need to be casted don't cast it

**Comment by yenda** [comment]
lgtm squash and rebase before we test it please

**Review by flexsurfer — APPROVED** [review]
