### PR TITLE
[#9350] fix back button on keycard login screen

### LINKED ISSUE #9350: Replace "Cancel" with "<" and remove extra screen if only one key
_Part of #9264 keycard sign in epic (mark as checked there, when closing this issue)_

There is currently a `Cancel` button in the sign in flow. This should be replaced with a `<`. 

When there's only one key, the `<` button should be present from step 2 onward, so users re-enter the passcode or just come back for whatever reason.

Image:

back

Figma:
https://www.figma.com/file/dEIljL7UPbXgsZUA0Q4qlE5E/Onboarding?node-id=4566%3A12

### PR DESCRIPTION
**Pull request by rasom**
fix #9350 

status: ready

### CODE REVIEW

File: src/status_im/subs.cljs [hunk 1]
```diff
@@ -482,6 +482,12 @@
  (fn [[macc acc]]
    (some #(when (= (:address %) (:address acc)) %) (:accounts macc))))
 
+(re-frame/reg-sub
+ :multiaccounts-count
```
Comment (yenda) [inline src/status_im/subs.cljs]: maybe it could be a predicate `multiple-multiaccounts?` here since that is the only usage of this sub

**Review by yenda — APPROVED** [review]

File: src/status_im/subs.cljs (hunk 1 above)
Comment (rasom) [reply src/status_im/subs.cljs]: ok, sounds reasonable

Comment (rasom) [reply src/status_im/subs.cljs]: done
