### PR TITLE
[#9709] Empty gas when transacting leads to bug

### LINKED ISSUE #9709: Empty gas when transacting leads to bug
# Bug Report

## Problem

Triggering a transaction from the ENS registration flow has an empty gas amount.
When manually entering GWEI, ETH does not fill out automatically. Must fill out both fields manually.
Attempt to complete transaction.
Get bug. 

#### Expected behavior

Gas estimate is included with transaction. Can complete transaction even if I alter gas amount.

#### Actual behavior

I am blocked from completing Tx.

IMG_6388
IMG_6389
IMG_6390

### Reproduction

- Open ENS names
- Type in a name you own
- Attempt to claim the name by signing Tx

### Additional Information

iOS 19/12/19 nightly
Emailed logs via bug report

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #9709

Prevented entering decimals gas, added loading indicator for gas and gasprice

### CODE REVIEW

File: src/status_im/ui/screens/signing/views.cljs [hunk 1]
```diff
@@ -221,30 +221,35 @@
...
+                             :ios   {:size  :small}
+                             :android {:size :16}}])
+
+(views/defview fee-item [prices wallet-currency fee-display-symbol fee gas-error]
+  (views/letsubs [{:keys [gas-price-loading? gas-loading?]} [:signing/edit-fee]]
+    (let [converted-fee-value (* fee (get-in prices [(keyword fee-display-symbol) (keyword (:code wallet-currency)) :price]))]
+      [list-item/list-item
+       {:type        :small
+        :title       :t/network-fee
+        :error       (when-not (or gas-price-loading? gas-loading?) gas-error)
```
Comment (vitvly) [inline src/status_im/ui/screens/signing/views.cljs:235]: Would be nice to let-bind `(or gas-price-loading? gas-loading?)` as it's repeated thrice.

**Review by vitvly — APPROVED** [review]
