### PR TITLE
Disallow recovering of an existing multiaccount

### LINKED ISSUE #10002: Can't login to account `sql: no rows in result set`
# Bug Report

## Problem

No clear reproduction so far but I keep here some notes for now:

I've got this state while testing RC11. And at the same time on both iOS and Android, can't reproduce now on Android (kept logcat and kept the build with such 'sick' account on iOS)
Last actions before issue occured:

- I had ~4 accounts already existing in apps (both Android and iOS)

1) Android created new account (UserA). Back up seed phrase (it was  this one `cloud mesh pyramid kidney rubber winner lounge system reject weird picnic ride`). Android switch to Ropsten and received ETHro and XLS from different account
2) iOS creates one more new account (UserB). Back up seed phrase (it was `system remain polar salad couch dwarf churn tourist depend answer intact minute`). iOS switched to Ropsten and received XLS from different account
3) iOS recovers UserA
4) Android recovers UserB
5) iOS recovers UserB and Android recovers UserA (their first accounts they back up)

Now when I login to account which was recovered in 3rd and 4th steps on respective device, - I get `sql: no rows in result set` error.
If I try to login to any other account - I get the same error, until I restart the app. In that case I can login to "healthy" accounts.

#### Expected behavior

Can login to account

#### Actual behavior

Can't login to account `sql: no rows in result set` 

Screenshot 2020-02-07 at 22 26 54

### Additional Information

- Status version: RC11
- Operating System: Android and iOS

#### Logs

[logcatNoRowsInResultSet.log](https://github.com/status-im/status-react/files/4172851/logcatNoRowsInResultSet.log)

 of device when I try to login to sick account

``` 
02-07 20:14:17.518 27678 27718 D StatusModule: clearCookies
02-07 20:14:17.519 27678 27718 D StatusModule: clearStorageAPIs
02-07 20:14:17.520 27678 27718 D StatusModule: login
02-07 20:14:17.521 27678 27729 D StatusModule: Signal event: {"type":"node.login","event":{"error":"sql: no rows in result set"}}
02-07 20:14:17.522 27678 27718 D StatusModule: Login result: {"error":""}

```

### PR DESCRIPTION
**Pull request by rasom**
fix #10002

status: ready

### CODE REVIEW

**Review by flexsurfer — APPROVED** [review]

File: src/status_im/multiaccounts/recover/core.cljs [hunk 1]
```diff
@@ -20,7 +20,7 @@
 
 (defn existing-account?
   [root-key multiaccounts]
-  (contains? multiaccounts (:key-uid root-key)))
+  (contains? multiaccounts (:keyUid root-key)))
```
Comment (flexsurfer) [inline src/status_im/multiaccounts/recover/core.cljs:23]: why do we have this key mess?

Comment (flexsurfer) [reply src/status_im/multiaccounts/recover/core.cljs:23]: i mean why don't we store and use in clojure only kebab ?

Comment (rasom) [reply src/status_im/multiaccounts/recover/core.cljs:23]: @flexsurfer i din't check when and why it was changed, can't answer

Comment (yenda) [reply src/status_im/multiaccounts/recover/core.cljs:23]: Can't we fix the case rather than this? Especially since the bug must have been introduced somewhere else it wasn't there before

**Comment by Serhy** [comment]
@rasom When I recover the same multiaccount there is a `This multiaccount already exists. You just need to unlock it.` pop up with `Cancel` and `Unlock` options. 

And there is  'Your keys have been successfully recovered' view on background **(1)**
Tapping upon `Unlock` I appear on empty account login screen and if I type valid password I get `sql: no rows in result set` **(2)**

Screenshot 2020-02-10 at 13 09 24


But all fine if I navigate back to list of accounts via `Cancel`, - then I can login fine to any account including the one I was about to re-recover.

If it's easy fix to redirect user to login view of the account which was re-recovered then it would solve both **(1)** and **(2)** issues above. 
Otherwise let's hide `Unlock` button in the pop-up and fix after V1

File: src/status_im/multiaccounts/recover/core.cljs (hunk 1 above)
Comment (rasom) [reply src/status_im/multiaccounts/recover/core.cljs:23]: @flexsurfer it didn't work properly at least 10 weeks ago, bisection is a nightmare

**Comment by rasom** [comment]
@Serhy should be fixed now

**Comment by Serhy** [comment]
Thanks a lot @rasom! latest builds https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-200210-120919-49d6e0-pr.ipa and https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-200210-120918-49d6e0-pr-universal.apk looks good to me on iOS and Android 8 / 9 
Can create new account and back up seed phrase. When recover the seed phrase of this new account (or recovering twice the same account):
- "Unlock" button navigates to appropriate account supposed to be recovered
- "Cancel" button navigates to 'Unlock' view with the list of account.

**Comment by yenda** [comment]
Dammit my review was pending I thought I submitted
