### PR TITLE
fix(multiaccounts/login): ensure log-level is updated correctly

### LINKED ISSUE #10127: Log level is not applied
# Bug Report

## Problem

By default we set log level in DISABLED state in profile setting. However changing it to DEBUG/TRACE does not make any effect. In logcat (Status.log for iOS) there are no DEBUG/TRACE records anyway. 

It's fine with develop (nightly/PR) builds.

#### Expected behavior

Log level setting applies and reflected in logs for release builds

#### Actual behavior

Log level setting change from Profile is not reflected in logs for release builds

### Reproduction

- Instal release build
- Create new account
- Navigate to `Profile` ->  `Advanced` -> `Log level`
- Set TRACE value
- Re-login to account, navigate between different screens and check logcat has DEBUG/TRACE/INFO records (also sending bug report from `Profile` -> `Need help?` -> `Submit bug`  to your email should has Status.log in package with the similar results: DEBUG/TRACE logs should be there) 

### Additional Information
- Status version: Release 1.1 (and Release 1.0.2)
- Operating System: Android and iOS

#### Logs

Logcat with TRACE log level setting in 1.1.x release build:

[logcatTRACErelease.log](https://github.com/status-im/status-react/files/4288656/logcatTRACErelease.log)

### PR DESCRIPTION
**Pull request by 0x-r4bbit**
As reported in #10127 there's an issue that the log level isn't properly
applied when changed through log settings UI.

Turned out that we're setting the log-level only once in the entire
lifetime of the application and that is during bootstrap.
When the log level is changed through the UI, we never actually update
the log level in the logger module.

To fix this, we just need to ensure that, whenever the log-level is changed,
we also call `log/set-level!` with the new level.

It should also be noted that, every time the log level is changed through
the UI, the user is logged out, so one place to update the logger is
after very successful login.

Fixes #10127

### CODE REVIEW

File: src/status_im/multiaccounts/login/core.cljs [hunk 1]
```diff
@@ -190,6 +191,11 @@
         (data-store.settings/rpc->settings settings)
         multiaccount (dissoc settings :networks/current-network :networks/networks)
         network-id (str (get-in networks [current-network :config :NetworkId]))]
+    (log/set-level! (if-let [log-level (get multiaccount :log-level)]
+                      (-> (if (string/blank? log-level) "ERROR" log-level)
+                          string/lower-case
+                          keyword)
+                      config/log-level))
```
Comment (0x-r4bbit) [inline src/status_im/multiaccounts/login/core.cljs]: Alright, couple things to note here:

- When logging in, there's a possibility that the account in question doesn't have an actual `log-level` yet. In that case, we're going with `config/log-level` which is also what's being set during app bootstrap
- If there is a log-level, there's a possibility that it's an empty string. This is the case when logging was set to "DISABLED". I couldn't find a way to actually disable the logger so I'm defaulting to "ERROR" here

File: src/status_im/subs.cljs [hunk 2]
```diff
@@ -484,7 +484,9 @@
  :<- [:multiaccount]
  (fn [multiaccount]
    (or (get multiaccount :log-level)
-       config/log-level-status-go)))
+       (-> config/log-level
+           name
+           string/upper-case))))
```
Comment (0x-r4bbit) [inline src/status_im/subs.cljs]: The log-settings view has a subscription to this function here and previously tried to read from `:multiaccount :log-level`. If there's no log-level in the current multi account, it would fallback to`status-go-log-level`.

^ This is an issue because it would always result in the UI showing a different log level than what is actually configured. That's why I decided to fallback to `config/log-level` instead because that's the same value that's set during app bootstrap.

**Review by 0x-r4bbit — COMMENTED** [review]
Just tested this again and there's still an issue (would like some feedback on that):

- Generally it tends to be hard to keep `multiaccount :log-level `and `log/log-level` in sync
- When logging in for the first time, the log-level is set to `INFO` in the app state, that's why we're hooking into `get-settings-callback` to update `log/log-level`
- That callback is only called when logging in from an existing account though. When creating a brand new account, it just happened that the log-level in app state is also set to `INFO` but I can't find the place where that happens.
- The latter, again, results in `log/log-level` and app state log-level to be out of sync.

I find that managing state of log-level is quite inconsistent and was wondering if there's a way to subscribe to changes in `multiaccount :log-level` and set `log/set-log-level!` based on that as a reaction.

@yenda said that subscriptions are only possible within views, but maybe there's another reframe-y way to do this?

File: src/status_im/multiaccounts/login/core.cljs (hunk 1 above)
Comment (yenda) [reply src/status_im/multiaccounts/login/core.cljs]: Since this is a side-effect, you should create a set-level! effect in logging.core with reg-event-fx and use that effect here.
Also as a default you should probably use `config/log-level-status-go` and assoc the log-level in the db here so that you don't need to change the subscription. You simplify the subscription by simply returning `(get multiaccount :log-level)` since it will then always have a log-level.
Would also be nice to put a default log-level for newly created accounts since it seems it is not the case otherwise you would always have a log-level here.

File: src/status_im/subs.cljs [hunk 3]
```diff
@@ -483,8 +483,7 @@
  :log-level/current-log-level
  :<- [:multiaccount]
  (fn [multiaccount]
-   (or (get multiaccount :log-level)
-       config/log-level-status-go)))
+   (get multiaccount :log-level)))
```
Comment (0x-r4bbit) [inline src/status_im/subs.cljs:490]: `multiaccount :log-level` is now always set because it'll always be initialised during login

File: src/status_im/utils/logging/core.cljs [hunk 4]
```diff
@@ -41,6 +42,21 @@
...
+(re-frame/reg-fx
+ :logs/set-level
+ (fn [log-level]
+   (log/set-level! log-level)))
+
+(fx/defn set-log-level
+  [{:keys [db]}  multiaccount]
+  (let [log-level (if-let [level (get multiaccount :log-level)]
+                    (if (clojure.string/blank? level) "ERROR" level)
+                    config/log-level-status-go)]
```
Comment (0x-r4bbit) [inline src/status_im/utils/logging/core.cljs:54]: I'm pretty sure there's a "nicer" way of doing this.

**Review by 0x-r4bbit — COMMENTED** [review]
@yenda thanks for all the feedback and help. This should now do the trick!

File: src/status_im/utils/logging/core.cljs (hunk 4 above)
Comment (flexsurfer) [reply src/status_im/utils/logging/core.cljs:54]: @PascalPrecht could you please elaborate why if its nil we set log-level-status-go?

**Comment by flexsurfer** [comment]
@PascalPrecht could you please resolve conflicts, thanks

File: src/status_im/utils/logging/core.cljs (hunk 4 above)
Comment (0x-r4bbit) [reply src/status_im/utils/logging/core.cljs:54]: @flexsurfer Yes sir! This was requested here: https://github.com/status-im/status-react/pull/10438#discussion_r415635013

Comment (flexsurfer) [reply src/status_im/utils/logging/core.cljs:54]: i knew that, thanks :)

**Comment by 0x-r4bbit** [comment]
@flexsurfer done!

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
Checked on Android and IOS:
- log level by default
- setting to DEBUG, TRACE, disabling.

Looks good to me!
