### PR TITLE
[#10557] "TypeError: Network request failed" crash on sticker market

### LINKED ISSUE #10557: "TypeError: Network request failed" crash on sticker market
# Bug Report

## Problem

User reported about errors and crashes, apparently related to infura and requests to it for stickers: 

Screenshot 2020-05-04 at 15 05 53
Screenshot 2020-05-04 at 15 06 11

App version: 1.3.1 (20200502104447)
OS: ios
Node version: StatusIM/v0.52.2/darwin-arm64/go1.13.4
Mailserver: mail-01.ac-cn-hongkong-c.eth.prod

#### Expected behavior

No errors

#### Actual behavior

"TypeError: Network request failed" crash on sticker market

### Reproduction

- Open Status and create new account
- Join public chat and add stickers in sticker markets
- (Optional) Send several stickers in chat 

### Additional Information
App version: 1.3.1 (20200502104447)
OS: ios

#### Logs
[Status.log](https://github.com/status-im/status-react/files/4574519/Status.log)

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #10557

### CODE REVIEW

File: src/status_im/utils/http.cljs [hunk 1]
```diff
@@ -130,9 +130,7 @@
                   (on-error response)
 
                   :else false)))
-       (.catch (or on-error
-                   (fn [error]
-                     (utils/show-popup "Error" url (str error))))))))
+       (.catch (or on-error #())))))
```
Comment (vitvly) [inline src/status_im/utils/http.cljs:133]: Let's add some logging here inside the anonymous fn.

**Review by vitvly — APPROVED** [review]

**Comment by churik** [comment]
nothing to check actually, e2e tests are passed - so stickerpack that was bought earlier can be installed and used.
Consider it as ready to merge
