### PR TITLE
Edit message issues

### LINKED ISSUE #14621: Editing message issues
**ISSUE 1. [Send] button is not visible during message editing**
**Steps to reproduce:**
1. Go to 1-1 chat
2. Send the message
3. Long tap on it
4. Add some additional text into the editing textbox
5. Try to tap 'send' button

**Actual result:**

[Send] button is not visible

https://user-images.githubusercontent.com/52490791/209150399-d16e00cd-5ffa-4c01-ac58-6527bd1216a9.mp4

**Expected result:**
[Send] button is visible

**ENV:** Android devices

**ISSUE 2. [Only for IOS devices] The initial message is not shown into the input textbox if 'edit message' option is selected**

**Steps to reproduce:**
1. Create 1-1 chat
2. Send a message
3. Long tap on the message
4. Tap 'edit message'

**Actual result:**
https://user-images.githubusercontent.com/52490791/209154631-c8e00d73-aa94-4e8d-b8b1-dcf4aac73f7a.MP4

The initial message that intended to be edited is disappeared
**Expected result:**
The initial text is shown after 'edit message' option is tapped

**ISSUE 3: Mark that the message is edited should be shown**

**Steps to reproduce:**
1. Go to 1-1 chat
2. Send the message
3. Long tap the message -> tap 'edit  message' option
4. Make some changes -> tap 'send' button

**Actual result:**
The changed message is not  marked as 'changed'

**Expected result:**
image

### PR DESCRIPTION
**Pull request by ibrkhalil**
fixes #14621 
status: ready

### CODE REVIEW

File: src/status_im/ui2/screens/chat/composer/view.cljs [hunk 1]
```diff
@@ -243,20 +241,27 @@
...
-                  (when (seq images)
-                    (input/show-send refs))
-                  (reset! keyboard-was-shown? keyboard-shown)
-                  (if (#{:max :custom-chat-unavailable} (:state @context))
-                    (set-bg-opacity 1)
-                    (set-bg-opacity 0))
-                  (reanimated/set-shared-value translate-y (reanimated/with-timing (- y)))
-                  (reanimated/set-shared-value shared-height
-                                               (reanimated/with-timing (min y max-height)))))
+                  (let [edited? (-> (rf/sub [:chat/inputs])
```
Comment (ilmotta) [inline src/status_im/ui2/screens/chat/composer/view.cljs]: This is a tad too difficult to understand to me, besides @ibrkhalil, you could consider having another subscription to keep the UI dumb.

```clojure
(let [input-text (get-in (rf/sub [:chat/inputs])
                         [chat-id :input-text])
      edited?    (not= input-text (-> edit :content :text))])
```

File: src/status_im/ui2/screens/chat/composer/view.cljs [hunk 2]
```diff
@@ -243,20 +241,27 @@
...
+                                    (get chat-id)
+                                    :input-text
+                                    (not= (-> edit
+                                              :content
+                                              :text)))]
+                    (when (and @keyboard-was-shown? (not keyboard-shown))
+                      (swap! context assoc :state :min)
+                      (set-bg-opacity 0))
+                    (when (and blank-composer? (not (seq images)) (not edit))
```
Comment (ilmotta) [inline src/status_im/ui2/screens/chat/composer/view.cljs]: You can use `empty?` instead of `(not (seq ...))`

File: src/status_im2/contexts/chat/messages/pin/banner/view.cljs [hunk 3]
```diff
@@ -5,7 +5,15 @@
 (defn banner
   [chat-id]
   (let [pinned-messages (rf/sub [:chats/pinned chat-id])
-        latest-pin-text (get-in (last (vals pinned-messages)) [:content :text])
+
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/messages/pin/banner/view.cljs]: Extra line.

File: src/status_im2/contexts/chat/messages/pin/banner/view.cljs [hunk 4]
```diff
@@ -5,7 +5,15 @@
...
+        latest-pin-id   (-> pinned-messages
+                            vals
+                            last
+                            (get :message-id))
+        latest-pin-text (-> [:chats/chat-messages chat-id]
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/messages/pin/banner/view.cljs]: The thread first macro here makes the code more difficult to comprehend. You can just use get-in once, and as usual, consider having a separate subscription to keep the UI dumb.

```clojure
(get-in (rf/sub [:chats/chat-messages chat-id])
        [latest-pin-id :content :text])
```

File: src/status_im2/contexts/chat/messages/pin/list/view.cljs [hunk 5]
```diff
@@ -10,22 +10,26 @@
...
-    :public?             public?
-    :community?          community?
-    :current-public-key  current-public-key
-    :show-input?         show-input?
-    :message-pin-enabled true
-    :in-pinned-view?     true
-    :pinned              true
-    :timestamp-str       (time/timestamp->time whisper-timestamp)
-    :edit-enabled        edit-enabled}])
+  (let [message-content-sub (-> [:chats/chat-messages chat-id]
```
Comment (ilmotta) [inline src/status_im2/contexts/chat/messages/pin/list/view.cljs]: Same as another comment I made in this PR, you can avoid the thread first macro with multiple calls to get and use only one get-in.

```clojure
(get-in (rf/sub [:chats/chat-messages chat-id])
        [message-id :content])
```

File: src/status_im/ui2/screens/chat/composer/view.cljs [hunk 6]
```diff
@@ -243,20 +241,27 @@
                                                             set-bg-opacity)]
               (quo.react/effect!
                #(do
```
Comment (ilmotta) [inline src/status_im/ui2/screens/chat/composer/view.cljs]: FYI: I know it's not the responsibility of this PR, but this usage of `#()` is a total anti-pattern in long, multi-line anonymous functions. In many occasions, it forces the reader to scan the entire code looking for a `%` sign that either doesn't exist or it's not supported by the anonymous function.

**Review by ilmotta — APPROVED** [review]
Non-blocking comments.

**Comment by VolodLytvynenko** [comment]
@ibrkhalil could you resolve conflicts and. rebase in the current PR, please?

**Comment by ibrkhalil** [comment]
> @ibrkhalil could you resolve conflicts and. rebase in the current PR, please?

Done, Kindly take a look

**Comment by pavloburykh** [comment]
Thanx @ibrkhalil Issues are fixed. PR is ready to be merged.
