### PR TITLE
Disable back button when migrating to a keycard 📱➡️ 💳.

### LINKED ISSUE #13943: Crash during onboarding / migration from regular account to Keycard after password confirmation and returning back
# Bug Report

## Problem 

There are several ways to reproduce the issue. Also, the app behaves differently on iOS and Android. 

### 1. New account creation on Android

**STR:**
1. Install Status
2. `Generate a new key` > Choose device as key storage > Create a password > Tap `Next` and quickly tap `Back`while processing is in progress
3. Choose device as key storage and create a password again
4. Tap `Next`

**Actual result:** app crashes with `java.lang.NullPointerException`

https://user-images.githubusercontent.com/67952253/188643626-526b50ab-0287-47bb-a74d-bc32cc132b20.mp4

### 2. Migration from a regular account to Keycard on Android

**STR:**
1. Install Status
2. Recover/create a regular account
3. `Profile` > `Privacy and security` > `Manage keys and storage` > `Log out`
4. Put a tick `Move keystore file` > `Enter seed phrase` > `Choose a storage` > `Keycard` > `Confirm`
5. Enter password to move your data > `Confirm`
6. Tap `Back` on the `Store your keys on Keycard` screen
7. Select `Keycard` and enter the password again > `Confirm` > Complete the onboarding flow

**Actual result:** app crashes with `java.lang.NullPointerException` after Keycard passcode confirmation

### 3. Migration from a regular account to Keycard on iOS
Most problematic one

There are the same steps to reproduce as in the previous scenario but the resulting behavior is different.
You can finish the migration process, but if you log out of the app once and try to log in again, you will get `Looks like you've tapped a wrong keycard` message.
The `lost or frozen card?` flow doesn't help either - when you try to log in after recovery, the multi-account "loses" the username and changes the user's picture (see video below). Thus, login is not possible until the application is reinstalled.

https://user-images.githubusercontent.com/67952253/188650692-bae1873a-2036-47ec-a597-af27af01c9c8.MP4

### Additional Information

- Status version: nightly 1.19
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by audriu**
fixes #13943

### Summary
Disable the back button when migrating to keycard on android.

#### Platforms
- Android
- iOS

##### Functional
- account recovery
- new account

### Steps to test
- Open Status
- follow [these steps](https://github.com/status-im/status-mobile/issues/13943#:~:text=Keycard%20on%20Android-,STR%3A,-Install%20Status)
- see how it all works perfectly

status: ready

### CODE REVIEW

**Comment by flexsurfer** [comment]
could you elaborate on why only partially fix?

**Comment by audriu** [comment]
Because it only fixes case 2 of that ticket. I can't reproduce case 1 and for case 3 I need an iPhone - which is nowhere around me. Maybe someone with an iPhone can continue...

File: src/status_im/navigation/core.cljs [hunk 1]
```diff
@@ -192,7 +192,7 @@
                                               :keycard-pairing]))]
     {:init-root-fx (if keycard-account? :multiaccounts-keycard :multiaccounts)}))
 
-(defonce rset-app-launched
+(defonce reset-app-launched
```
Comment (flexsurfer) [inline src/status_im/navigation/core.cljs]: it should be `reg` or `register`, also `rset-lazy-reg` should be `set-lazy-reg`

**Review by flexsurfer — COMMENTED** [review]
im not sure i understand how this PR fixes the issue, issue says you need to press back button, not a hardware ? could you elaborate on changes in this PR please @audriu

File: src/status_im/navigation/core.cljs (hunk 1 above)
Comment (audriu) [reply src/status_im/navigation/core.cljs]: Maybe we can leave as it is as it functions the same.

**Comment by audriu** [comment]
Back button is also considered to be Hardware back button

**Comment by audriu** [comment]
The back button is also considered to be a Hardware back button in navigations documentation:
https://reactnative.dev/docs/backhandler
So I assumed that those terms are equal...

**Comment by flexsurfer** [comment]
i mean the back button in topbar and hardware back button have different handlers , so i still not sure how this fix works

**Comment by audriu** [comment]
This will only fix for hardware button. This only fixes for Android.

**Comment by audriu** [comment]
ah yes, just realized that I could use the simulator. since this could be solved without using the keycard in this case.

**Comment by flexsurfer** [comment]
so it won't solve case 2 ? or @qoqobolo replicated it only for hardware button ?

**Comment by qoqobolo** [comment]
>  or @qoqobolo replicated it only for hardware button ?

No, case 2 is replicated with the app `Back` button. So PR should fix it as well.

**Comment by audriu** [comment]
@flexsurfer do you think that code is ok so it could be manually tested?

**Comment by qoqobolo** [comment]
Smoke tested case 2 of [the issue](https://github.com/status-im/status-mobile/issues/13943) on Android device - the error has not been completely fixed; only the hardware back button has been disabled, the issue is still reproducible when using the app back button.

@audriu please, bring this PR back for review as soon as case 2 is fully fixed.
Thanks.

**Comment by cammellos** [comment]
@audriu makes sense to fix both cases, just one won't provide much benefits, I agree with @qoqobolo , thank you

**Comment by audriu** [comment]
I know but this requires a physical iPhone to use with a keycard. But maybe this will fix both cases because the back button is disabled now.

**Comment by audriu** [comment]
I think it now fixes both cases.

**Comment by flexsurfer** [comment]
hey @audriu i still can't see how the back button in UI is fixed , no related changes in the code

**Comment by qoqobolo** [comment]
@flexsurfer not sure how it should look like in the code, but in fact, the back button is disabled 

Screenshot 2022-09-20 at 10 49 22

**Comment by audriu** [comment]
@flexsurfer The back button is disabled. 
Screenshot 2022-09-20 at 11 46 25
by this code https://github.com/status-im/status-mobile/blob/13943-crash-during-onboarding-migration-from-regular-account-to-keycard-after-password-confirmation-and-returning-back/src/status_im/ui/screens/screens.cljs#L751

So if it is not possible to go back - the bug does not happen.
It was done like that in the original keycard migration implementation https://github.com/status-im/status-mobile/pull/11526/files

**Review by flexsurfer — APPROVED** [review]

**Comment by flexsurfer** [comment]
oh now i get it, thanks, so there were native topbar but we don't need to show it

**Comment by qoqobolo** [comment]
Thanks @audriu, PR is tested and can be merged.
E2e failures are not related to PR.
