### PR TITLE
[#8239] App crash when submit cryptokitties with different than it's …

### LINKED ISSUE #8239: App crash when submit cryptokitties with different than it's valid domain
**_Type_**: Bug

**_Summary_**: Status crashes when requesting in Status app browser cryptokitties with different than `.co` domain name (e.g. of domain name values are `.com`/`.io`/`.blarandom` etc)
Could not get example with several other Dapps.

#### Expected behavior
`Unable to load page` page in Status browser app when open `https://www.cryptokitties` with different than `.co` domain name

#### Actual behavior
App crash when open `https://www.cryptokitties` with different than `.co` domain name

### Reproduction 1

* Open Status and create new account
* Navigate to `Dapps` -> enter `https://www.cryptokitties.domainname` in URL box
* Submit URL

### Reproduction 2

* Open Status and create new account
* Navigate to `Dapps` -> enter `https://www.cryptokitties.co` in URL box
* After Dapp loaded edit `.co` domain in URL box to `.com` and submit

### Additional Information

* Status version: Nightly develop 0.13/release 0.12
* Operating System: Android and iOS

#### Logs
Logcat of the issue:
[logcat_with_crash.log](https://github.com/status-im/status-react/files/3197771/CrashCryptoCatURLEdit.log)

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #8239

### CODE REVIEW

**Comment by flexsurfer** [comment]
@Serhy @antdanchenko would be nice to cover by autotests

File: src/status_im/ui/screens/browser/site_blocked/views.cljs [hunk 1]
```diff
@@ -21,14 +16,16 @@
     [vector-icons/icon :main-icons/info {:color colors/red}]
     [react/text {:style styles/title-text}
      (i18n/label :t/browsing-site-blocked-title)]
-    [react/text {:style styles/description-text}
-     (i18n/label :t/browsing-site-blocked-description1)
-     [chat-link]
-     [react/text (i18n/label :t/browsing-site-blocked-description2)]]
+    [react/view {:align-items :center}
+     [react/text {:style styles/description-text} (i18n/label :t/browsing-site-blocked-description1)]
+     [react/touchable-highlight {:on-press #(.openURL react/linking "status-im://chat/public/status")}
```
Comment (yenda) [inline src/status_im/ui/screens/browser/site_blocked/views.cljs]: I think you can still have the link creation in a function just check how nested-text component works, here you probably just want the style to be returned with the on-press attribute. However I am not 100% sure it is supported though it is worth testing I think it is done somewhere else

Comment (flexsurfer) [reply src/status_im/ui/screens/browser/site_blocked/views.cljs]: `nested-text` didn't work so i decided to go this way, just to fix this for release, and it's not great that `react/text` crashes the app, should be handled properly for sure

Comment (yenda) [reply src/status_im/ui/screens/browser/site_blocked/views.cljs]: It crashed the app because it was code that never got reached so far. This is a leftover from typography pr that got missed, nested test has to be explicit.

How did you do the nested-text component? It takes strings or tuples of style+string as inputs

Comment (yenda) [reply src/status_im/ui/screens/browser/site_blocked/views.cljs]: https://github.com/status-im/status-react/blob/496f3f1cc78703c3d629f9f458a0e966b04e5c61/src/status_im/ui/screens/privacy_policy/views.cljs#L8-L13

It works I've done it

Comment (flexsurfer) [reply src/status_im/ui/screens/browser/site_blocked/views.cljs]: @yenda  yeah that works, updated

**Review by yenda — APPROVED** [review]

**Review by jeluard — APPROVED** [review]

**Comment by churik** [comment]
Issue is not reproducible.
Also rechecked tapping on invalid URL - behavior is the same as in current nightly.
Tested on IOS 11.4.1 (IPhone 7), Android 8 (LG V20). 
Waiting for e2e.

**Comment by churik** [comment]
failed e2e is known https://github.com/status-im/status-react/issues/8161
