### PR TITLE
[#10115] Trim address/name on adding 1-1 chat

### LINKED ISSUE #10115: Trim address in input field (New chat screen)
# Bug Report

## Problem

When copying chat key or typing ENS with space in the end/start of the string, better to trim user input

#### Expected behavior
can add contact

#### Actual behavior
validation error
photo_2020-03-02 11 00 36

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Tap on + > Start new chat
- Type `autotester ` (with space in the end)

### Additional Information

- Status version: nightly 02/03/2020
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by rasom**
fix #10115 

status: ready

### CODE REVIEW

File: src/status_im/ui/screens/add_new/new_chat/events.cljs [hunk 1]
```diff
@@ -28,25 +29,27 @@
 
 (handlers/register-handler-fx
  :new-chat/set-new-identity
- (fn [{db :db} [_ new-identity new-ens-name id]]
+ (fn [{db :db} [_ new-identity-raw new-ens-name-raw id]]
    (when (or (not id) (= id @resolve-last-id))
-     (let [is-public-key? (and (string? new-identity)
+     (let [new-identity   (utils/safe-trim new-identity-raw)
+           new-ens-name   (utils/safe-trim new-ens-name-raw)
```
Comment (flexsurfer) [inline src/status_im/ui/screens/add_new/new_chat/events.cljs]: `new-ens-name-raw` is `new-identity`, so it's already trimmed

**Review by flexsurfer — APPROVED** [review]
