### PR TITLE
Move chats to status-go

### LINKED ISSUE #8670: Multiaccount's and realm db passwords  doesn't match at attempt to create third account (quickly)
###  Description

*Type*: Bug

*Summary*: when creating several accounts one by one, on third getting an error "Multiaccount's and realm db passwords doesn't match" and after this can't create and restore accounts anymore.
In log: "failed to initialize messages db: file is not a database"
Found during testing https://github.com/status-im/status-react/pull/8601 , but also can be replicated in nightly.

#### Expected behavior
can create account

#### Actual behavior
photo_2019-07-30 11 18 36

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create account
- Log out
- Create account
- Log out
- Create account

### Additional Information

- Status version: nightly 30/09/19
- Operating System: Android, iOS

#### Logs

**Geth.log:** [geth (5).log](https://github.com/status-im/status-react/files/3446207/geth.5.log)
**Logcat:**
```
07-30 11:44:07.395  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :multiaccounts.recover.ui/sign-in-button-pressed
07-30 11:44:07.415  8146  8188 I ReactNativeJS: INFO [status-im.node.core:173] - Node config:  {"ClusterConfig":{"Enabled":true,"Fleet":"eth.beta","BootNodes":["enode://e8a7c03b58911e98bbd66accb2a55d57683f35b23bf9dfca89e5e244eb5cc3f25018b4112db507faca34fb69ffb44b362f79eda97a669a8df29c72e654416784@47.91.224.35:443","enode://43947863cfa5aad1178f482ac35a8ebb9116cded1c23f7f9af1a47badfc1ee7f0dd9ec0543417cc347225a6e47e46c6873f647559e43434596c54e17a4d3a1e4@47.52.74.140:443","enode://436cc6f674928fdc9a9f7990f2944002b685d1c37f025c1be425185b5b1f0900feaf1ccc2a6130268f9901be4a7d252f37302c8335a2c1a62736e9232691cc3a@174.138.105.243:443","enode://ebefab39b69bbbe64d8cd86be765b3be356d8c4b24660f65d493143a0c44f38c85a257300178f7845592a1b0332811542e9a58281c835babdd7535babb64efc1@35.202.99.224:443"],"TrustedMailServers":["enode://da61e9eff86a56633b635f887d8b91e0ff5236bbc05b8169834292e92afb92929dcf6efdbf373a37903da8fe0384d5a0a8247e83f1ce211aa429200b6d28c548@47.91.156.93:443","enode://7de99e4cb1b3523bd26ca212369540646607c721ad4f3e5c821ed9148150ce6ce2e72631723002210fac1fd52dfa8bbdf3555e05379af79515e1179da37cc3db@35.188.19.210:443","enode://8a64b3c349a2e0ef4a32ea49609ed6eb3364be1110253c20adc17a3cebbc39a219e5d3e13b151c0eee5d8e0f9a8ba2cd026014e67b41a4ab7d1d5dd67ca27427@206.189.243.168:443","enode://744098ab6d3308af5cd03920aea60c46d16b2cd3d33bf367cbaf1d01c2fcd066ff8878576d0967897cd7dbb0e63f873cc0b4f7e4b0f1d7222e6b3451a78d9bda@47.89.20.15:443","enode://531e252ec966b7e83f5538c19bf1cde7381cc7949026a6e499b6e998e695751aadf26d4c98d5a4eabfb7cefd31c3c88d600a775f14ed5781520a88ecd25da3c6@35.225.227.79:443","enode://015e22f6cd2b44c8a51bd7a23555e271e0759c7d7f52432719665a74966f2da456d28e154e836bee6092b4d686fe67e331655586c57b718be3997c1629d24167@35.226.21.19:443"],"StaticNodes":["enode://66ba15600cda86009689354c3a77bdf1a97f4f4fb3ab50ffe34dbc904fac561040496828397be18d9744c75881ffc6ac53729ddbd2cdbdadc5f45c400e2622f7@206.189.243.176:443","enode://0440117a5bc67c2908fad94ba29c7b7f2c1536e96a9df950f3265a9566bf3a7306ea8ab5a1f9794a0a641dcb1e4951ce7c093c61c0d255f4ed5d2ed02c8fce23@35.224.15.65:443"],"RendezvousNodes":["/ip4/206.189.243.57/tcp/30703/ethv4/16Uiu2HAmLqTXuY4Sb6G28HNooaFUXUKzpzKXCcgyJxgaEE2i5vnf","/ip4/174.138.105.243/tcp/30703/ethv4/16Uiu2HAmRHPzF3rQg55PgYPcQkyvPVH9n2hWsYPhUJBZ6kVjJgdV"]},"DataDir":"/ethereum/mainnet_rpc","LogLevel":"INFO","Rendezvous":true,"WhisperConfig":{"Enabled":true,"LightClient":true,"MinimumPoW":0.001,"EnableNTPSync":true},"LogEnabled":true,"BrowsersConfig":{"Enabled":true},"RequireTopics":{"whisper":{"Min":2,"Max":2}},"UpstreamConfig":{"Enabled":true,"URL":"https://mainnet.infura.io/v3/f315575765b14720b32382a61a89341a"},"PermissionsConfig":{"Enabled":true},"NetworkId":1,"Name":"StatusIM","NoDiscovery":false,"ShhextConfig":{"BackupDisabledDataDir":"/data/user/0/im.status.ethereum.pr/files/../no_backup","InstallationID":"78e6acf5-f335-5481-a91f-5baac48db74d","MaxMessageDeliveryAttempts":6,"MailServerConfirmations":true,"PFSEnabled":true},"WalletConfig":{"Enabled":true},"StatusAccountsConfig":{"Enabled":true}}
07-30 11:44:07.423  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :multiaccounts.recover.ui/password-input-blured
07-30 11:44:07.437  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :show-tab-bar
07-30 11:44:07.439  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :set
07-30 11:44:07.557  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :signals/signal-received
07-30 11:44:07.558  8146  8188 D ReactNativeJS: DEBUG [status-im.events:858] - :event-str {"type":"node.started","event":null}
07-30 11:44:07.560  8146  8188 D ReactNativeJS: DEBUG [status-im.signals.core:87] - Event  node.started  not handled nil
07-30 11:44:07.587  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :signals/signal-received
07-30 11:44:07.588  8146  8188 D ReactNativeJS: DEBUG [status-im.events:858] - :event-str {"type":"node.ready","event":null}
07-30 11:44:07.602  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :signals/signal-received
07-30 11:44:07.604  8146  8188 D ReactNativeJS: DEBUG [status-im.events:858] - :event-str {"type":"discovery.started","event":null}
07-30 11:44:07.605  8146  8188 D ReactNativeJS: DEBUG [status-im.signals.core:87] - Event  discovery.started  not handled nil
07-30 11:44:07.675  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :signals/signal-received
07-30 11:44:07.676  8146  8188 D ReactNativeJS: DEBUG [status-im.events:858] - :event-str {"type":"discovery.summary","event":[{"enode":"enode://66ba15600cda86009689354c3a77bdf1a97f4f4fb3ab50ffe34dbc904fac561040496828397be18d9744c75881ffc6ac53729ddbd2cdbdadc5f45c400e2622f7@206.189.243.176:443","id":"0e969556ca4bf2a0266aed93582ea55f01c09f2431fe84d22d2b7acdf2acb592","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:46482","remoteAddress":"206.189.243.176:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}}]}
07-30 11:44:07.714  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :signals/signal-received
07-30 11:44:07.716  8146  8188 D ReactNativeJS: DEBUG [status-im.events:858] - :event-str {"type":"discovery.summary","event":[{"enode":"enode://66ba15600cda86009689354c3a77bdf1a97f4f4fb3ab50ffe34dbc904fac561040496828397be18d9744c75881ffc6ac53729ddbd2cdbdadc5f45c400e2622f7@206.189.243.176:443","id":"0e969556ca4bf2a0266aed93582ea55f01c09f2431fe84d22d2b7acdf2acb592","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:46482","remoteAddress":"206.189.243.176:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://887cbd92d95afc2c5f1e227356314a53d3d18855880ac0509e0c0870362aee03939d4074e6ad31365915af41d34320b5094bfcc12a67c381788cd7298d06c875@206.189.243.177:30305?discport=0","id":"410f5dcad03a883948d31aaa04887df5c5281d1473751ef5a89396cdcd2751e2","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:48829","remoteAddress":"206.189.243.177:30305","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}}]}
07-30 11:44:07.854  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :signals/signal-received
07-30 11:44:07.855  8146  8188 D ReactNativeJS: DEBUG [status-im.events:858] - :event-str {"type":"discovery.summary","event":[{"enode":"enode://66ba15600cda86009689354c3a77bdf1a97f4f4fb3ab50ffe34dbc904fac561040496828397be18d9744c75881ffc6ac53729ddbd2cdbdadc5f45c400e2622f7@206.189.243.176:443","id":"0e969556ca4bf2a0266aed93582ea55f01c09f2431fe84d22d2b7acdf2acb592","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:46482","remoteAddress":"206.189.243.176:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://887cbd92d95afc2c5f1e227356314a53d3d18855880ac0509e0c0870362aee03939d4074e6ad31365915af41d34320b5094bfcc12a67c381788cd7298d06c875@206.189.243.177:30305?discport=0","id":"410f5dcad03a883948d31aaa04887df5c5281d1473751ef5a89396cdcd2751e2","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:48829","remoteAddress":"206.189.243.177:30305","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://0440117a5bc67c2908fad94ba29c7b7f2c1536e96a9df950f3265a9566bf3a7306ea8ab5a1f9794a0a641dcb1e4951ce7c093c61c0d255f4ed5d2ed02c8fce23@35.224.15.65:443","id":"c022fb911a856f7eb6c383d5914b9b3b5418d63dd5abe147af62ab98a7d80214","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:33259","remoteAddress":"35.224.15.65:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}}]}
07-30 11:44:07.876  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :signals/signal-received
07-30 11:44:07.878  8146  8188 D ReactNativeJS: DEBUG [status-im.events:858] - :event-str {"type":"discovery.summary","event":[{"enode":"enode://66ba15600cda86009689354c3a77bdf1a97f4f4fb3ab50ffe34dbc904fac561040496828397be18d9744c75881ffc6ac53729ddbd2cdbdadc5f45c400e2622f7@206.189.243.176:443","id":"0e969556ca4bf2a0266aed93582ea55f01c09f2431fe84d22d2b7acdf2acb592","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:46482","remoteAddress":"206.189.243.176:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://887cbd92d95afc2c5f1e227356314a53d3d18855880ac0509e0c0870362aee03939d4074e6ad31365915af41d34320b5094bfcc12a67c381788cd7298d06c875@206.189.243.177:30305?discport=0","id":"410f5dcad03a883948d31aaa04887df5c5281d1473751ef5a89396cdcd2751e2","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:48829","remoteAddress":"206.189.243.177:30305","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://552942cc4858073102a6bcd0df9fe4de6d9fc52ddf7363e8e0746eba21b0f98fb37e8270bc629f72cfe29e0b3522afaf51e309a05998736e2c0dad5288991148@130.211.215.133:30305?discport=0","id":"b3db5b57ddc03be24094603a073b407ceaafc5b78dd6ffb55d4d8d3f5e9cc034","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:57097","remoteAddress":"130.211.215.133:30305","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://0440117a5bc67c2908fad94ba29c7b7f2c1536e96a9df950f3265a9566bf3a7306ea8ab5a1f9794a0a641dcb1e4951ce7c093c61c0d255f4ed5d2ed02c8fce23@35.224.15.65:443","id":"c022fb911a856f7eb6c383d5914b9b3b5418d63dd5abe147af62ab98a7d80214","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:33259","remoteAddress":"35.224.15.65:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}}]}
07-30 11:44:07.956  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :signals/signal-received
07-30 11:44:07.960  8146  8188 D ReactNativeJS: DEBUG [status-im.events:858] - :event-str {"type":"discovery.summary","event":[{"enode":"enode://66ba15600cda86009689354c3a77bdf1a97f4f4fb3ab50ffe34dbc904fac561040496828397be18d9744c75881ffc6ac53729ddbd2cdbdadc5f45c400e2622f7@206.189.243.176:443","id":"0e969556ca4bf2a0266aed93582ea55f01c09f2431fe84d22d2b7acdf2acb592","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:46482","remoteAddress":"206.189.243.176:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://19872f94b1e776da3a13e25afa71b47dfa99e658afd6427ea8d6e03c22a99f13590205a8826443e95a37eee1d815fc433af7a8ca9a8d0df7943d1f55684045b7@35.238.60.236:30305?discport=0","id":"10841e6db5c02fc331bf36a8d2a9137a1696d9d3b6b1f872f780e02aa8ec5bba","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:60408","remoteAddress":"35.238.60.236:30305","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://887cbd92d95afc2c5f1e227356314a53d3d18855880ac0509e0c0870362aee03939d4074e6ad31365915af41d34320b5094bfcc12a67c381788cd7298d06c875@206.189.243.177:30305?discport=0","id":"410f5dcad03a883948d31aaa04887df5c5281d1473751ef5a89396cdcd2751e2","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:48829","remoteAddress":"206.189.243.177:30305","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://552942cc4858073102a6bcd0df9fe4de6d9fc52ddf7363e8e0746eba21b0f98fb37e8270bc629f72cfe29e0b3522afaf51e309a05998736e2c0dad5288991148@130.211.215.133:30305?discport=0","id":"b3db5b57ddc03be24094603a073b407ceaafc5b78dd6ffb55d4d8d3f5e9cc034","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:57097","remoteAddress":"130.211.215.133:30305","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://0440117a5bc67c2908fad94ba29c7b7f2c1536e96a9df950f3265a9566bf3a7306ea8ab5a1f9794a0a641dcb1e4951ce7c093c61c0d255f4ed5d2ed02c8fce23@35.224.15.65:443","id":"c022fb911a856f7eb6c383d5914b9b3b5418d63dd5abe147af62ab98a7d80214","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:33259","remoteAddress":"35.224.15.65:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}}]}
07-30 11:44:07.971  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :signals/signal-received
07-30 11:44:07.973  8146  8188 D ReactNativeJS: DEBUG [status-im.events:858] - :event-str {"type":"discovery.summary","event":[{"enode":"enode://66ba15600cda86009689354c3a77bdf1a97f4f4fb3ab50ffe34dbc904fac561040496828397be18d9744c75881ffc6ac53729ddbd2cdbdadc5f45c400e2622f7@206.189.243.176:443","id":"0e969556ca4bf2a0266aed93582ea55f01c09f2431fe84d22d2b7acdf2acb592","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:46482","remoteAddress":"206.189.243.176:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://887cbd92d95afc2c5f1e227356314a53d3d18855880ac0509e0c0870362aee03939d4074e6ad31365915af41d34320b5094bfcc12a67c381788cd7298d06c875@206.189.243.177:30305?discport=0","id":"410f5dcad03a883948d31aaa04887df5c5281d1473751ef5a89396cdcd2751e2","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:48829","remoteAddress":"206.189.243.177:30305","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://552942cc4858073102a6bcd0df9fe4de6d9fc52ddf7363e8e0746eba21b0f98fb37e8270bc629f72cfe29e0b3522afaf51e309a05998736e2c0dad5288991148@130.211.215.133:30305?discport=0","id":"b3db5b57ddc03be24094603a073b407ceaafc5b78dd6ffb55d4d8d3f5e9cc034","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:57097","remoteAddress":"130.211.215.133:30305","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://0440117a5bc67c2908fad94ba29c7b7f2c1536e96a9df950f3265a9566bf3a7306ea8ab5a1f9794a0a641dcb1e4951ce7c093c61c0d255f4ed5d2ed02c8fce23@35.224.15.65:443","id":"c022fb911a856f7eb6c383d5914b9b3b5418d63dd5abe147af62ab98a7d80214","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:33259","remoteAddress":"35.224.15.65:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}}]}
07-30 11:44:08.304  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :signals/signal-received
07-30 11:44:08.306  8146  8188 D ReactNativeJS: DEBUG [status-im.events:858] - :event-str {"type":"discovery.summary","event":[{"enode":"enode://66ba15600cda86009689354c3a77bdf1a97f4f4fb3ab50ffe34dbc904fac561040496828397be18d9744c75881ffc6ac53729ddbd2cdbdadc5f45c400e2622f7@206.189.243.176:443","id":"0e969556ca4bf2a0266aed93582ea55f01c09f2431fe84d22d2b7acdf2acb592","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:46482","remoteAddress":"206.189.243.176:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://887cbd92d95afc2c5f1e227356314a53d3d18855880ac0509e0c0870362aee03939d4074e6ad31365915af41d34320b5094bfcc12a67c381788cd7298d06c875@206.189.243.177:30305?discport=0","id":"410f5dcad03a883948d31aaa04887df5c5281d1473751ef5a89396cdcd2751e2","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:48829","remoteAddress":"206.189.243.177:30305","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://960777f01b7dcda7c58319e3aded317a127f686631b1702a7168ad408b8f8b7616272d805ddfab7a5a6bc4bd07ae92c03e23b4b8cd4bf858d0f74d563ec76c9f@47.52.58.213:30305?discport=0","id":"781b904d6468f2c996ed15d4a16a7b7d248e995b03e6b98bdd4fb62a444ec8a0","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:44656","remoteAddress":"47.52.58.213:30305","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://552942cc4858073102a6bcd0df9fe4de6d9fc52ddf7363e8e0746eba21b0f98fb37e8270bc629f72cfe29e0b3522afaf51e309a05998736e2c0dad5288991148@130.211.215.133:30305?discport=0","id":"b3db5b57ddc03be24094603a073b407ceaafc5b78dd6ffb55d4d8d3f5e9cc034","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:57097","remoteAddress":"130.211.215.133:30305","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://0440117a5bc67c2908fad94ba29c7b7f2c1536e96a9df950f3265a9566bf3a7306ea8ab5a1f9794a0a641dcb1e4951ce7c093c61c0d255f4ed5d2ed02c8fce23@35.224.15.65:443","id":"c022fb911a856f7eb6c383d5914b9b3b5418d63dd5abe147af62ab98a7d80214","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:33259","remoteAddress":"35.224.15.65:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}}]}
07-30 11:44:08.320  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :signals/signal-received
07-30 11:44:08.322  8146  8188 D ReactNativeJS: DEBUG [status-im.events:858] - :event-str {"type":"discovery.summary","event":[{"enode":"enode://66ba15600cda86009689354c3a77bdf1a97f4f4fb3ab50ffe34dbc904fac561040496828397be18d9744c75881ffc6ac53729ddbd2cdbdadc5f45c400e2622f7@206.189.243.176:443","id":"0e969556ca4bf2a0266aed93582ea55f01c09f2431fe84d22d2b7acdf2acb592","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:46482","remoteAddress":"206.189.243.176:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://887cbd92d95afc2c5f1e227356314a53d3d18855880ac0509e0c0870362aee03939d4074e6ad31365915af41d34320b5094bfcc12a67c381788cd7298d06c875@206.189.243.177:30305?discport=0","id":"410f5dcad03a883948d31aaa04887df5c5281d1473751ef5a89396cdcd2751e2","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:48829","remoteAddress":"206.189.243.177:30305","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://aa97756bc147d74be6d07adfc465266e17756339d3d18591f4be9d1b2e80b86baf314aed79adbe8142bcb42bc7bc40e83ee3bbd0b82548e595bf855d548906a1@47.52.188.241:30305?discport=0","id":"a681612c0a4b3321926dfe00af7bb5891d07a512a24b5ba6b05e11703d66aec3","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:35948","remoteAddress":"47.52.188.241:30305","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://552942cc4858073102a6bcd0df9fe4de6d9fc52ddf7363e8e0746eba21b0f98fb37e8270bc629f72cfe29e0b3522afaf51e309a05998736e2c0dad5288991148@130.211.215.133:30305?discport=0","id":"b3db5b57ddc03be24094603a073b407ceaafc5b78dd6ffb55d4d8d3f5e9cc034","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:57097","remoteAddress":"130.211.215.133:30305","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://0440117a5bc67c2908fad94ba29c7b7f2c1536e96a9df950f3265a9566bf3a7306ea8ab5a1f9794a0a641dcb1e4951ce7c093c61c0d255f4ed5d2ed02c8fce23@35.224.15.65:443","id":"c022fb911a856f7eb6c383d5914b9b3b5418d63dd5abe147af62ab98a7d80214","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:33259","remoteAddress":"35.224.15.65:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}}]}
07-30 11:44:08.327  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :signals/signal-received
07-30 11:44:08.335  8146  8188 D ReactNativeJS: DEBUG [status-im.events:858] - :event-str {"type":"discovery.summary","event":[{"enode":"enode://66ba15600cda86009689354c3a77bdf1a97f4f4fb3ab50ffe34dbc904fac561040496828397be18d9744c75881ffc6ac53729ddbd2cdbdadc5f45c400e2622f7@206.189.243.176:443","id":"0e969556ca4bf2a0266aed93582ea55f01c09f2431fe84d22d2b7acdf2acb592","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:46482","remoteAddress":"206.189.243.176:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://887cbd92d95afc2c5f1e227356314a53d3d18855880ac0509e0c0870362aee03939d4074e6ad31365915af41d34320b5094bfcc12a67c381788cd7298d06c875@206.189.243.177:30305?discport=0","id":"410f5dcad03a883948d31aaa04887df5c5281d1473751ef5a89396cdcd2751e2","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:48829","remoteAddress":"206.189.243.177:30305","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://552942cc4858073102a6bcd0df9fe4de6d9fc52ddf7363e8e0746eba21b0f98fb37e8270bc629f72cfe29e0b3522afaf51e309a05998736e2c0dad5288991148@130.211.215.133:30305?discport=0","id":"b3db5b57ddc03be24094603a073b407ceaafc5b78dd6ffb55d4d8d3f5e9cc034","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:57097","remoteAddress":"130.211.215.133:30305","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://0440117a5bc67c2908fad94ba29c7b7f2c1536e96a9df950f3265a9566bf3a7306ea8ab5a1f9794a0a641dcb1e4951ce7c093c61c0d255f4ed5d2ed02c8fce23@35.224.15.65:443","id":"c022fb911a856f7eb6c383d5914b9b3b5418d63dd5abe147af62ab98a7d80214","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:33259","remoteAddress":"35.224.15.65:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}}]}
07-30 11:44:08.339  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :signals/signal-received
07-30 11:44:08.341  8146  8188 D ReactNativeJS: DEBUG [status-im.events:858] - :event-str {"type":"discovery.summary","event":[{"enode":"enode://66ba15600cda86009689354c3a77bdf1a97f4f4fb3ab50ffe34dbc904fac561040496828397be18d9744c75881ffc6ac53729ddbd2cdbdadc5f45c400e2622f7@206.189.243.176:443","id":"0e969556ca4bf2a0266aed93582ea55f01c09f2431fe84d22d2b7acdf2acb592","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:46482","remoteAddress":"206.189.243.176:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://887cbd92d95afc2c5f1e227356314a53d3d18855880ac0509e0c0870362aee03939d4074e6ad31365915af41d34320b5094bfcc12a67c381788cd7298d06c875@206.189.243.177:30305?discport=0","id":"410f5dcad03a883948d31aaa04887df5c5281d1473751ef5a89396cdcd2751e2","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:48829","remoteAddress":"206.189.243.177:30305","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://552942cc4858073102a6bcd0df9fe4de6d9fc52ddf7363e8e0746eba21b0f98fb37e8270bc629f72cfe29e0b3522afaf51e309a05998736e2c0dad5288991148@130.211.215.133:30305?discport=0","id":"b3db5b57ddc03be24094603a073b407ceaafc5b78dd6ffb55d4d8d3f5e9cc034","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:57097","remoteAddress":"130.211.215.133:30305","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}},{"enode":"enode://0440117a5bc67c2908fad94ba29c7b7f2c1536e96a9df950f3265a9566bf3a7306ea8ab5a1f9794a0a641dcb1e4951ce7c093c61c0d255f4ed5d2ed02c8fce23@35.224.15.65:443","id":"c022fb911a856f7eb6c383d5914b9b3b5418d63dd5abe147af62ab98a7d80214","name":"Statusd/v0.29.0-beta.2/linux-amd64/go1.12.5","caps":["shh/6"],"network":{"localAddress":"192.168.1.38:33259","remoteAddress":"35.224.15.65:443","inbound":false,"trusted":false,"static":true},"protocols":{"shh":"unknown"}}]}
07-30 11:44:08.415  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :multiaccounts.recover.callback/recover-multiaccount-success
07-30 11:44:08.425  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.keychain.core:191] - initializing realm encryption key...
07-30 11:44:08.426  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.keychain.core:173] - PERF initializing realm encryption key... 1564479848425
07-30 11:44:08.481  8146  8188 D ReactNativeJS: DEBUG [status-im.data-store.core:28] - changing multiaccount to:  0xcf2272205cc0cf96Cfbb9Dd740BD681D1E86901E
07-30 11:44:08.483  8146  8188 D ReactNativeJS: DEBUG [status-im.data-store.realm.core:194] - closing account realm
07-30 11:44:08.492  8146  8188 I ReactNativeJS: INFO [status-im.data-store.realm.core:245] - try to encrypt with password
07-30 11:44:08.503  8146  8188 I ReactNativeJS: INFO [status-im.data-store.realm.core:247] - try to encrypt with password success
07-30 11:44:08.507  8146  8188 I ReactNativeJS: INFO [status-im.data-store.realm.core:274] - open-account
07-30 11:44:08.509  8146  8188 I ReactNativeJS: INFO [status-im.data-store.realm.core:177] - migrate-realm
07-30 11:44:08.514  8146  8188 I ReactNativeJS: INFO [status-im.data-store.realm.core:147] - migrate schemas -1
07-30 11:44:08.516  8146  8188 D ReactNativeJS: DEBUG [status-im.data-store.realm.core:46] - Opening realm at  /data/user/0/im.status.ethereum.pr/files/../no_backup/realm/accounts/0xeeb570494d442795235589284100812e4176e9c29d151a81df43b6286ef66c49 ...
07-30 11:44:08.523  8146  8188 D ReactNativeJS: DEBUG [status-im.data-store.realm.core:48] - Using encryption key...
07-30 11:44:08.564  8146  8188 I ReactNativeJS: INFO [status-im.data-store.realm.core:277] - account-realm  false
07-30 11:44:08.569  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :init.callback/multiaccount-change-success
07-30 11:44:08.596  8146  8188 D ReactNativeJS: DEBUG [status-im.ui.screens.navigation:80] - :navigate-to :home nil
07-30 11:44:09.315  8146  8188 D ReactNativeJS: DEBUG [status-im.ui.screens.routing.core:32] - :on-will-focus :home
07-30 11:44:09.342  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :screens/on-will-focus
07-30 11:44:09.349  8146  8188 D ReactNativeJS: DEBUG [status-im.ui.screens.views:133] - :main-component-did-update :home
07-30 11:44:09.374  8146  8188 D ReactNativeJS: DEBUG [status-im.notifications.core:194] - get-fcm-token: eevCsfyaV5Q:APA91bF0Z06D59k1PHoHuuSl2FJ6WDWLh3xKwMkjvl0jcU7D3ogPxLOw7giHI4J-8rPcDL28eBTyLl4o0rstzqEYOM8PV-Ghacrx5K2eQHvCvtz8HHDcWABDWMSnFH-eh1CugLcFH7Fk
07-30 11:44:09.377  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :notifications.callback/get-fcm-token-success
07-30 11:44:09.380  8146  8188 D ReactNativeJS: DEBUG [status-im.notifications.core:39] - notifications-granted
07-30 11:44:09.382  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :notifications.callback/request-notifications-permissions-granted
07-30 11:44:09.398  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :init-rest-of-chats
07-30 11:44:09.400  8146  8188 D ReactNativeJS: DEBUG [status-im.events:122] - PERF :init-rest-of-chats 1564479849399
07-30 11:44:09.449  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :set-once
07-30 11:44:09.578  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :multiaccounts.login.callback/login-success
07-30 11:44:09.583  8146  8188 E ReactNativeJS: ERROR [status-im.multiaccounts.login.core:126] - failed to login failed to initialize messages db: file is encrypted or is not a database
07-30 11:44:09.613  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :multiaccounts.logout.ui/logout-confirmed
07-30 11:44:09.618  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :multiaccounts.logout/filters-removed
07-30 11:44:09.664  8146  8188 W ReactNativeJS: Unable to symbolicate stack trace: Bundle was not loaded from the packager
07-30 11:44:09.811  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :multiaccounts.login.callback/get-user-password-success
07-30 11:44:09.813  8146  8188 D ReactNativeJS: DEBUG [status-im.ui.screens.navigation:80] - :navigate-to :login nil
07-30 11:44:09.918  8146  8188 D ReactNativeJS: DEBUG [status-im.ui.screens.routing.core:32] - :on-will-focus :login
07-30 11:44:09.923  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :screens/on-will-focus
07-30 11:44:09.926  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :signals/signal-received
07-30 11:44:09.928  8146  8188 D ReactNativeJS: DEBUG [status-im.events:858] - :event-str {"type":"discovery.stopped","event":null}
07-30 11:44:09.929  8146  8188 D ReactNativeJS: DEBUG [status-im.signals.core:87] - Event  discovery.stopped  not handled nil
07-30 11:44:09.932  8146  8188 D ReactNativeJS: DEBUG [status-im.ui.screens.views:133] - :main-component-did-update :login
07-30 11:44:09.935  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :keychain.callback/can-save-user-password?-success
07-30 11:44:10.056  8146  8188 D ReactNativeJS: DEBUG [status-im.utils.handlers:32] - Handling re-frame event:  :signals/signal-received
07-30 11:44:10.058  8146  8188 D ReactNativeJS: DEBUG [status-im.events:858] - :event-str {"type":"node.stopped","event":null}
```

### PR DESCRIPTION
**Pull request by cammellos**
This commit moves chats to status-go.

I have changed the logic to load all chats in one go for simplicity and
while that might have a performance impact, I think it's premature to
  optimize this flow as there will be more changes to the login flow.

Also currently this is likely to be slower as we need to wait for the
 status-service to be initialized, as well as realm.

No migration is provided as we are past the point of no return, so by
installing this version you will lose your chats.

### Testing
* Creating public/one-to-one/group chats
* Login/logout check chats are persisted
* Clear history/block contacts/delete chat

Currently there's a potential issue, as now updates are asynchronous, if two updates are made at the same time, last one wins, which might not be desirable. I don't think it's a big issue for now, but I will address separately (probably the easiest solution is to carry a version back from status-go, and discard updates with version < storedVersion, a queue is also a solution, but that relies on the clients to be well behaved).

No migration is provided as we are past the point of no return, so by
installing this version you will lose your chats, so no clear upgrade path has been taken care for.

Fixes: #8670 (probably, haven't tested it properly, but the bug should be gone)

status: ready

### CODE REVIEW

**Review by yenda — APPROVED** [review]
lgtm, just as a note I think we should homogenize the API, maybe we can do that after the main job is done. For instance for accounts we use kebab syntax so that we don't have to rename keys

File: src/status_im/contact/block.cljs [hunk 1]
```diff
@@ -32,8 +34,9 @@
               (chat.models/upsert-chat
                {:chat-id                      chat-id
                 :unviewed-messages-count
-                (- (get-in db [:chats chat-id :unviewed-messages-count])
-                   removed-unseen-count)})
+                (if (pos? unviewed-messages-count)
```
Comment (yenda) [inline src/status_im/contact/block.cljs:37]: is there some cases where it comes out negative? that would be weird?

File: src/status_im/ethereum/json_rpc.cljs [hunk 2]
```diff
@@ -32,6 +32,8 @@
    "shhext_loadFilters" {}
    "shhext_loadFilter" {}
    "shhext_removeFilters" {}
+   "shhext_chats" {}
```
Comment (yenda) [inline src/status_im/ethereum/json_rpc.cljs:35]: what was the difference between shhext_chats and status_chats?

File: src/status_im/contact/block.cljs (hunk 1 above)
Comment (cammellos) [reply src/status_im/contact/block.cljs:37]: it definitely did (we use an uint so it was throwing an error saving the chat), I could look more into the causes but I might address separately, although I will make sure it's not introduced in this PR

File: src/status_im/ethereum/json_rpc.cljs (hunk 2 above)
Comment (cammellos) [reply src/status_im/ethereum/json_rpc.cljs:35]: `status_chats` was just a stub endpoint, no logic, just hardcoded chats

**Review by flexsurfer — APPROVED** [review]

**Comment by Serhy** [comment]
@cammellos with the latest build: 
**Issue**: Blocked contact re-appears after next app re-launch. If user sent to blocked contact message(s) - those messages (user own messages) reappear too. If no messages - only chat with blocked contact re-appears on Chats view.

**To reproduce:**
1) Create a new account (UserA)
2) UserB sends a text message to UserA (don't matter if you added or not user in contacts)
3) UserA blocks UserB
4) UserA re-opens Status, logins and stays on Chats view

There were a couple of other bugs found during testing but I reconfirmed they are in develop build as well (like issue with PN: if user receives Push Notification - he stuck on the login screen when trying to login)

Also, as you noted, it takes noticeably more time for Chats screen to load after login. I'll measure the difference between the develop build at the end (it's like 1.5-2 times more with empty Chats view)

**Comment by cammellos** [comment]
@Serhy it should be fixed in the latest build (the chat was not deleted on `blocking` a user).

> those messages (user own messages) reappear too.

That's expected I believe, it's the current behavior on develop, so if you 
1) Send some messages to user B 
2) Block user B
3) Unblock user B
4) Open chat with user B again.

You will see your own messages, but not B's message unblocking (you might fetch some again post-unblocking). In this case we were simply not deleting the chat, which made it more apparent.

In terms of speed of login, there's not much we can do in the scope of this PR, as we need to wait for the login process in status-go to finish before we pull chats (before they  were pulled from realm so we did not have to wait for it). This is something that we will work on making faster.

It is also to be noted that although chats before were displayed earlier you were not able to interact with them until the login process was finished (i.e the blue `+` icon was not spinning anymore), so a fairer comparison would be to time between `+` finishes spinning and the chats are displayed. But I understand that before it gave the impression that it was loading faster, as chats were visible much earlier.

**Comment by churik** [comment]
Tested on IOS 11.4.1. and Android 6 (Galaxy S7, browser stack device):
- can create and restore account 
- can't reproduce https://github.com/status-im/status-react/issues/8670
- device pairing & sync (contacts, public chats, group chats, 1-1, fetching own messages from offline) 
- the profile image is not syncing (can you confirm @cammellos )?

Good to go from my side.

**Comment by cammellos** [comment]
> the profile image is not syncing (can you confirm @cammellos )?

Mhh, this should not be the case, is it possible that is also present in develop? I might address separately if introduced in this PR, if that's ok

**Comment by churik** [comment]
> Mhh, this should not be the case, is it possible that is also present in develop? I might address separately if introduced in this PR, if that's ok

Yeah, it is the same on nightly, I'm just wondering if it should be synced now (we already removed editing \ sync of profile name, so not sure about profile picture).
If it is an issue I'll create new one

**Comment by Serhy** [comment]
Looks good to me (tested with Android 6.0.1, Android 8.1, iOS 12.3)
* Creating public/one-to-one/group chats and messaging in them
* Confirmed after login/logout that chats are persisted 
* With clear history / block contacts / delete chat no message history reappears after re-login. 
* Cross-network messaging (Mainnet<->POA<->Ropsten works OK)
