### PR TITLE
wallet favourites

### LINKED ISSUE #10185: Keyboard is jumping on and off in "Send transaction"  screen in case of changing recipient
# Bug Report

## Problem
When enter recipient address or scanning valid QR on "Send transaction"  screen focus for a moment is set on amount field  (so the keyboard is opened, and then it is hidden)

#### Expected behavior
Keyboard is not hidden

#### Actual behavior
Keyboard appears for a moment and hides
ezgif com-video-to-gif (3)

#### Notes

For the developer who will be investigating. Is it related to another PR? Tips on where to start? 

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status > Wallet
- Tap on Send transaction
- Choose > Scan QR in "Choose recipient"
- Scan valid QR

### Additional Information

- Status version: nightly 19/03/2019
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by flexsurfer**
wallet favourites

fixes #10185

### CODE REVIEW

**Comment by errorists** [comment]
@flexsurfer is it ready for review?

**Comment by flexsurfer** [comment]
@errorists yes, but i had to cut some parts, because of lack of time :(

File: src/status_im/subs.cljs [hunk 1]
```diff
@@ -1228,6 +1254,21 @@
  (fn [currency-id]
    (get constants/currencies currency-id)))
 
+(defn filter-recipient-favs
```
Comment (rasom) [inline src/status_im/subs.cljs:1313]: same as `filter-recipient-accounts`?

File: src/status_im/ui/screens/wallet/recipient/views.cljs [hunk 2]
```diff
@@ -0,0 +1,286 @@
...
+  (let [search-filter @(re-frame/subscribe [:search/recipient-filter])]
+    [react/view {:padding-horizontal 16
+                 :padding-vertical   10}
+     [search-input/search-input
+      {:search-active? search-active?
+       :search-filter  search-filter
+       :on-cancel      #(re-frame/dispatch [:search/recipient-filter-changed nil])
+       :on-change      (fn [text]
+                         (re-frame/dispatch [:search/recipient-filter-changed text])
+                         (re-frame/dispatch [:set-in [:contacts/new-identity :state] :searching])
```
Comment (rasom) [inline src/status_im/ui/screens/wallet/recipient/views.cljs:51]: can we just do this at `:search/recipient-filter-changed`?

File: src/status_im/ui/screens/wallet/recipient/views.cljs [hunk 3]
```diff
@@ -0,0 +1,286 @@
...
+(defn section [_ _ _]
+  (let [opened? (reagent/atom false)]
+    (fn [title cnt content]
+      [react/view {:padding-vertical 8}
+       [quo/list-item
+        {:title    title
+         :on-press #(swap! opened? not)
+         :accessory
+         [react/view {:flex-direction :row :align-items :center}
+          (when (> cnt 0)
```
Comment (rasom) [inline src/status_im/ui/screens/wallet/recipient/views.cljs]: `(pos? cnt)`

File: src/status_im/ui/screens/wallet/recipient/views.cljs [hunk 4]
```diff
@@ -0,0 +1,286 @@
...
+        (for [{:keys [data]} txs]
+          [render-recent (first data)])]
+       [empty-items :main-icons/history (i18n/label :t/recent-empty)])]))
+
+(defn render-fav [{:keys [address name]}]
+  (let [noname? (string/blank? name)
+        short-address (utils/get-shortened-checksum-address address)]
+    [quo/list-item
+     {:title    (if noname? [quo/text {:monospace true}
+                             short-address] name)
```
Comment (rasom) [inline src/status_im/ui/screens/wallet/recipient/views.cljs]: can we move `name` to the next line here? imo this formatting makes it a bit hard to read

File: src/status_im/ui/screens/wallet/recipient/views.cljs [hunk 5]
```diff
@@ -0,0 +1,286 @@
...
+            [status-im.ethereum.stateofus :as stateofus])
+  (:require-macros [status-im.utils.views :as views]))
+
+(defn- recipient-topbar []
+  [topbar/topbar
+   {:navigation    {:on-press
+                    #(do
+                       (re-frame/dispatch [:wallet/recipient-modal-closed])
+                       (re-frame/dispatch [:search/recipient-filter-changed nil])
+                       (re-frame/dispatch [:set-in [:wallet/prepare-transaction :modal-opened?] false])
```
Comment (rasom) [inline src/status_im/ui/screens/wallet/recipient/views.cljs]: That concerns all `:set-in`'s, i won't repeat it in other places. I bet we discussed it many times already. imo that's not a big deal if we keep using it, but still a tiny dedicated handler instead would look abit better. Or if we can merge it into some neighbouring event.

**Review by rasom — APPROVED** [review]

File: src/status_im/ui/screens/wallet/recipient/views.cljs (hunk 2 above)
Comment (flexsurfer) [reply src/status_im/ui/screens/wallet/recipient/views.cljs:51]: unfortinatelly no , because we have `:search/recipient-filter-changed` in other places, but we need to set search only here

File: src/status_im/subs.cljs (hunk 1 above)
Comment (flexsurfer) [reply src/status_im/subs.cljs:1313]: just a coincidence, one may change in the future

File: src/status_im/ui/screens/wallet/recipient/views.cljs (hunk 4 above)
Comment (flexsurfer) [reply src/status_im/ui/screens/wallet/recipient/views.cljs]: sure

File: src/status_im/ui/screens/wallet/recipient/views.cljs (hunk 5 above)
Comment (flexsurfer) [reply src/status_im/ui/screens/wallet/recipient/views.cljs]: agree

**Comment by churik** [comment]
@flexsurfer 
### ISSUE 1: Status account is deleted after relogin
**Steps:**
- create new account
- relogin
IMAGE 2020-09-15 16:44:04

### ISSUE / question 2: what for we need search on the Recipient screen?
IMAGE 2020-09-15 16:52:05

**Comment by flexsurfer** [comment]
thanks , issues 1 should be fixes, question 2 : it should filter all sections except recent

**Comment by errorists** [comment]
tested on an empty wallet:

- [x] The 'Add to favourites` - 'Done' toolbar should only be visible on focusing the Address / ENS name input and disappear entirely when it's not focused
- [x] if you have the `0x…or username…` input currently focused, tapping outside or interacting with other elements should dismiss the keyboard and focus. As it is now, I can't dismiss it on iOS.
- [x] search is working in a peculiar way, it should show an empty screen if there are no matching results, and return a flat list of matching results if there are any
- [ ] in favourites we should show the 'Add to favourites' button even if the list is empty, I overlooked that sorry. [Figma](https://www.figma.com/file/XUehMnhyD1FGcWzvGz6SXqvh/Wallet?node-id=10220%3A38980)
- [x] favourites are missing the same initial letter icon treatment we do for public/group chats

@Ferossgp can you pls look into our Top Bar component implementation and make sure that nested search bars are available as a prop so we have consistency between them?

the collapsible list works really nicely 👏 , some implementations out there only display a single list opened at a time and hide the others, though I think ours is fine if there are no objections

**Comment by errorists** [comment]
also unrelated but this 'button' is triggering me each time I have to use it, can we please replace this 

Screenshot 2020-09-15 at 17 42 37

…with this…

Screenshot 2020-09-15 at 17 43 21

just have it use the nice button component, purple text, icon so it looks like you can press it
🙏

**Comment by flexsurfer** [comment]
thanks @errorists , yeah i was each time triggered , but couldn't realize whats wrong with this button :)

**Comment by flexsurfer** [comment]
hey @johnlea-quiup @errorists wdyt if i change jumpy bottom panel to modal screen in this PR as well? in that case it won't jump anymore, and it doesn't change anything besides that, because when keyboard is opened it fills full screen anyway, i remember that we did it as a panel with Andrey because we wanted in chat when you send tx part of chat should be visible but because pannel got so big it doesn't make sense anymore and it can be modal screen  , also before it wasn't possible to open two mosdals in a row, now its possible

**Comment by errorists** [comment]
@flexsurfer 👍 you have my axe. we should do it, I leave it up to you and QA in which PR.

**Comment by flexsurfer** [comment]
@churik  thanks, fixed all comments except ` in favourites we should show the 'Add to favourites' button even if the list is empty, I overlooked that sorry. Figma` can be addressed in separate PR
also now send /request transactions are modal screens

**Comment by churik** [comment]
Thanks a lot @flexsurfer 
awesome work!
#### ISSUE 3:  Done button is not visible when scanning QR code

So in order to proceed user needs to set focus to address input which is not obvious
IMAGE 2020-09-16 13:15:49

#### ISSUE 4: Exclude pending transactions from Recent
It may cause a situation when the user accidentally sends money to contract address, as before token transaction didn't get enough confirmations 'To' is populated with contract address

#### ISSUE 5: Sign and send button in 1-1 chat is not working
Monosnap 2020-09-16 14-49-40
On tap on this button nothing happens

#### ISSUE 6: "Select account" bottom sheet layout is broken

*Steps:*
- user A: send ETH to 1-1 chat to user B (no ENS)
- user B: Accept and share address


BAACAgQAAxkBAAErXW5fYgyGVVyZsRnvsNjFKHwUQOWrvQACcAgAAvOhEFMDAAG6bSX7HfMbBA_1600261280 97

**Comment by errorists** [comment]
re: issue 3, yes after populating the input with data, in this case a QR scanner, it should become focused

**Comment by flexsurfer** [comment]
thanks @churik all fixed

**Comment by churik** [comment]
@flexsurfer 
Keyboard is jumping on issue 3 (Android only)
BAACAgQAAxkBAAErXd5fYhiBSb7wAAGD6-G55KFY26CGQboAAsAHAAKONhBTvEcghni1T-AbBA_1600264395 91
All other issues are fixed.

**Comment by flexsurfer** [comment]
thanks @churik hope it fixed now

**Comment by churik** [comment]
@flexsurfer yes, it is fixed!
I'm on process of updating e2e and final testing, hopefully tomorrow will finish

**Comment by qoqobolo** [comment]
#### ISSUE 7: Add button is overlayed on the input field on on "Add to favourites" flow. On LG V20 (Android 8) only.

_Steps:_

- Select address
- Tap Add to favourites
- Set focus to input field

Screenshot 2020-09-17 at 13 04 03


#### ISSUE 8: "Done" button disappears after adding to favorites, until putting the focus in the address input field. Reproducible on Android devices only.

_Steps:_

- Paste address
- Tap Add to favourites
- Tap Add
- Check the screen
- Put the focus to the input field

ezgif com-resize (21)

#### ISSUE 9: Recipient search field is not cleared after transaction was sent.

_Steps:_

- Add to contacts user with ENS 
- Open wallet -> Tap Send transaction -> Enter valid amount of ETH -> Tap Choose Recipient
- Start to type ENS name of Recipient
- Select the value in the list
- Tap Send -> Sing transaction
- In opened Wallet screen tap Send again 
- Tap Choose Recipient 
- Check search field

ezgif com-resize (22)

**Comment by churik** [comment]
@flexsurfer  please let us know what issues will be fixed here and what are separately later, thanks!
IMO would be good to have at least issue 8 fixed.

**Comment by qoqobolo** [comment]
#### ISSUE 10: If firstly scan QR with scanner on the Choose Recipient screen, and after scan it with Universal scanner on the Home screen, then after the second scan the Send transaction screen isn't opened, just the Home screen is shown.

_Steps:_

- Open Choose Recipient screen
- Open QR scanner
- Scan valid QR code
- Navigate to Home screen -> + -> Tap QR scanner icon to open it
- Scan the same QR code

ezgif com-resize (23)

**Comment by churik** [comment]
Tests are fixed in https://github.com/status-im/status-react/pull/11183

**Comment by flexsurfer** [comment]
thanks @qoqobolo and @churik , all should be fixed now

**Comment by qoqobolo** [comment]
@flexsurfer  still can reproduce Issue 8. After adding an address to favourites "Address or ENS name" field is filled. Probably, in this case the "Done" button is expected to be on the screen without putting the focus to the field.
Screenshot 2020-09-21 at 11 27 46

**Comment by flexsurfer** [comment]
@qoqobolo probably it was fixed only on ios, didn't test on Android

**Comment by rasom** [comment]
@qoqobolo do you mean @flexsurfer?

**Comment by qoqobolo** [comment]
@rasom sure, sorry! :)

**Comment by qoqobolo** [comment]
@flexsurfer the issue was originally only reproduced on Android

**Comment by flexsurfer** [comment]
ok @qoqobolo pushed a fix, hope its fixed now , thanks

**Comment by qoqobolo** [comment]
#### ISSUE 11: Crash at attempt to scan QR-code via Universal scanner after scanning via scanner in "Choose Recipient" view. 
Reproduced time to time and on Android devices only (checked on Pixel 2 and Xiaomi mi note 9).

_Steps:_

- Open Choose Recipient screen
- Open QR scanner
- Scan some address, e.g. 0x835a70ee39a88aFFCf153642992326066afA7C8e
Screenshot 2020-09-21 at 17 02 22
- Navigate to Home view -> + -> Tap Universal scanner icon
- Scan the same QR


[Logs](https://github.com/status-im/status-react/files/5256169/qr.log)


Screenshot 2020-09-21 at 16 52 08

**Comment by churik** [comment]
@flexsurfer 
please when merging this Pr, merge also https://github.com/status-im/status-react/pull/11183 - otherwise tests will be broken
