### PR TITLE
Fix android tabbar animation

### LINKED ISSUE #10211: Screen is jumping when switching between tabs with open tabbar with and without text
# Bug Report

## Problem
Video: https://drive.google.com/file/d/1sKznc9AMSDEAouq_-PLEI4DLFy8paXoy/view?usp=sharing
Added to release, because issue is extremely visible. 

#### Expected behavior
navigation is smooth

#### Actual behavior
screen is jumping

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Join to any chat (leave in chat screen)
- Switch tab

### Additional Information

- Status version: nightly 24/03/2020
- Operating System: Android

### PR DESCRIPTION
**Pull request by Ferossgp**
Fixes #10211

### CODE REVIEW

File: src/status_im/ui/components/tabbar/core.cljs [hunk 1]
```diff
@@ -12,14 +12,13 @@
    [re-frame.core :as re-frame]))
 
 (defonce visible? (animation/create-value 0))
-
-(defonce minimized-state (reagent/atom nil))
+(defonce visible?' (animation/create-value 0))
```
Comment (flexsurfer) [inline src/status_im/ui/components/tabbar/core.cljs]: could we name it differently? self explained

**Review by flexsurfer — APPROVED** [review]

**Comment by errorists** [comment]
what does it do? I can't recall what was wrong with android tab bar previously in my limited use

File: src/status_im/ui/components/tabbar/styles.cljs [hunk 2]
```diff
@@ -115,11 +108,21 @@
...
+                                                       {:inputRange  [0 1]
+                                                        :outputRange [0 tabs-height]})}]}
          (when keyboard
-           {:position :absolute
-            :bottom   (- tabs-height)})))
+           {:position :absolute})))
+
+(defn space-handler [visible inset]
+  {:height     (+ inset minimized-tabs-height)
+   :margin-top (animation/interpolate visible
```
Comment (Ferossgp) [inline src/status_im/ui/components/tabbar/styles.cljs]: Because of react-native animation does not support layout changes (margin-top), this animation value should be on js thread. Keeping 2 animation values allows us to animate this invisible block and make space for the native animation which uses translate.

This also solves the problem that touchable inside translate move do not receive touches https://github.com/facebook/react-native/pull/26374

Comment (flexsurfer) [reply src/status_im/ui/components/tabbar/styles.cljs]: could you add this comment in the code ? would be useful

**Comment by Ferossgp** [comment]
@errorists this PR fixes the problem on android which makes the text in tabbar opened state not touchable, now press zone is the icon and space around it at a height of the minimised state

**Comment by errorists** [comment]
beautiful

**Comment by flexsurfer** [comment]
@Ferossgp should it also fix not smooth animation of the screen when switching between tabs?

**Comment by Ferossgp** [comment]
@flexsurfer, unfortunately, no, I will do that when I will connect the animation value of the bar with the animation progress of the screen. To do that I will need to use reanimated cause the screen uses it. This will fix the smooth transition cause reanimated allows the usage of native driver for layout. At the moment I integrate that library here: https://github.com/status-im/status-react/pull/10131

**Comment by flexsurfer** [comment]
@Ferossgp @churik but we can't release v.1.2 without the fix, can we find a quick temporary solution?

**Comment by churik** [comment]
Failed e2e are not related to PR.
Tested tabbar with and in minimized state (in ENS, in chat screen).

Tested on Android 10.

**Review by errorists — APPROVED** [review]

**Comment by churik** [comment]
> @Ferossgp @churik but we can't release v.1.2 without the fix, can we find a quick temporary solution?

created separate issue https://github.com/status-im/status-react/issues/10211

**Comment by churik** [comment]
Fixes #10211 
Tested on Android 10, Android 8 with minimized tabbar on Profile and on Chat tabs - no more jumping on switching.
Just in case tested IOS build.
