### PR TITLE
Show search cancel on android

### LINKED ISSUE #10807: Input is search fields on Android is not aligned and  cancel is not shown
# Bug Report

## Problem
Text is cut, cancel doesn't appear after input some text.
All fine with IOS.
photo_2020-06-12 16 01 08

#### Expected behavior
Search field is the same

#### Actual behavior
Text is cut; no Cancle button

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
- Create multiaccount
- Join several chats
- Open chat search

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 12/06/2020
- Operating System: Android

### PR DESCRIPTION
**Pull request by Ferossgp**
Fixes #10807

### CODE REVIEW

File: src/quo/components/text_input.cljs [hunk 1]
```diff
@@ -66,9 +66,9 @@
       false)))
 
 ;; TODO(Ferossgp): Check performance for android layout animations
-;; (when (and platform/android?
-;;            (aget rn/ui-manager "setLayoutAnimationEnabledExperimental"))
-;;   (ocall rn/ui-manager "setLayoutAnimationEnabledExperimental" true))
+(when (and platform/android?
```
Comment (flexsurfer) [inline src/quo/components/text_input.cljs:69]: hows this related to this PR ?

File: src/quo/components/text_input.cljs [hunk 2]
```diff
@@ -152,11 +152,14 @@
...
                  monospace]
-          :or   {cancel-label "Cancel"
-                 show-cancel  true}
+          :or   {cancel-label "Cancel"}
           :as   props}]
       {:pre [(check-spec ::text-input props)]}
-      (let [after (cond
+      (let [show-cancel (if (nil? show-cancel)
+                          ;; Enabled by default on iOs and disabled on Android
+                          (boolean platform/ios?)
```
Comment (flexsurfer) [inline src/quo/components/text_input.cljs]: isn't it already boolean ?

**Review by flexsurfer — APPROVED** [review]

File: src/quo/components/text_input.cljs (hunk 1 above)
Comment (Ferossgp) [reply src/quo/components/text_input.cljs:69]: Here I used Layout animation to animate the cancel button on iOs, to use the same animation on android, it should be enabled like that. I commented that code because at some point I thought that we will never show cancel on android (forgot about the search input)

**Review by flexsurfer — APPROVED** [review]

**Comment by churik** [comment]
Tested on IOS and Android - cancel is shown and working as expected.
There are several more issues with the search input, but they are reproducible with nightly as well, so will be reported separately
