### PR TITLE
[#9061] fix fetching balances for keycard acc

### LINKED ISSUE #9061: Account balance is not fetched when multiaccount is created with keycard
###  Description

*Type*: Bug

*Summary*: if multi-account is created with the keycard, the balance of account is not fetched.
It remains with "..." instead of converted value regardless of network.
Is reproducible for me every time and only with accounts, created with keycard.

However, the overall balance of the whole multiaccount is updated after relogin - but balance of separate account remains unchanged.

#### Expected behavior
"0 USD"

#### Actual behavior
... USD
Screenshot_20190927-164648_Status

### Reproduction

- Open Status
- Create account with keycard
- Wait several minutes and check account balance
- Relogin

### Additional Information

[comment]: # (Please do your best to fill this out.)
- Status version: nightly 27/09/2019
- Operating System: Android

### PR DESCRIPTION
**Pull request by rasom**
fix #9061 

status: ready

### CODE REVIEW

File: src/status_im/multiaccounts/login/core.cljs [hunk 1]
```diff
@@ -128,6 +129,16 @@
    current-network
    (types/deserialize networks)])
 
+(defn convert-multiaccounts-addresses
+  [multiaccount]
+  (-> multiaccount
```
Comment (vitvly) [inline src/status_im/multiaccounts/login/core.cljs]: Nitpicking: maybe it's nicer to let-bind update-fn:
```
(let [update-fn #(update % :address eip55/address->checksum)]
    (-> multiaccount
        update-fn
        (update :accounts #(mapv update-fn %))))
```

**Review by vitvly — APPROVED** [review]

File: src/status_im/multiaccounts/login/core.cljs (hunk 1 above)
Comment (rasom) [reply src/status_im/multiaccounts/login/core.cljs]: done

**Comment by Serhy** [comment]
Tested with Android 8.1 and Android 9. Account with keycard updates fiat currency on multiaccount as well as on 'status account' wallet view. 
The same kept for non-ketcard accounts
