### PR TITLE
[#9573] Fix some password saving bugs

### LINKED ISSUE #9573: Enabling biometric on signin issues
# Bug Report

## Problem

1) It says keycard for regular accounts without keycard
image

2) Clitical security issue
  - check "save password"
  - enable biometric
 - press "save password"
 - press "cancel"

save password still selected, and biometric should be enabled, sig in, check biometric, biometric is off

3)select "save passord", cancel biometric, deselect "save password" , select "save password" - no popup with biometric

### PR DESCRIPTION
**Pull request by rasom**
fix #9573

status: ready

### CODE REVIEW

File: src/status_im/subs.cljs [hunk 1]
```diff
@@ -513,6 +513,11 @@
  (fn [multiaccounts]
    (> (count multiaccounts) 1)))
 
+(re-frame/reg-sub
+ :multiaccounts.login/keycard-account?
+ :<- [:multiaccounts/login]
+ (fn [{:keys [keycard-pairing]}] keycard-pairing))
```
Comment (flexsurfer) [inline src/status_im/subs.cljs]:
```suggestion
 (fn [{:keys [keycard-pairing]}] (boolean keycard-pairing)))
```

**Review by flexsurfer — APPROVED** [review]

File: src/status_im/subs.cljs (hunk 1 above)
Comment (rasom) [reply src/status_im/subs.cljs]: As I wrote the code which uses this sub, this is definitely unnecessary here. I will extract this code to a separate function once have a free time, that's in my todo list, so that we will not need to think about this kinda boolean value...

**Comment by churik** [comment]
@rasom no difference if tapping on "Save password" or "Don't ask for card to sign in" popup is the same:
photo_2019-12-10 17 21 25
Expected that "biometric-enable-keycard" will be used in case of checking "Don't ask for card to sign in"

**Comment by rasom** [comment]
@churik fixed
