### PR TITLE
[#10233] Web-page splits in 2 frames when contains errors

### LINKED ISSUE #10233: Web-page splits in 2 frames when contains errors
# Bug Report

## Problem

photo_2020-03-27 14 43 45
photo_2020-03-27 14 43 43

#### Expected behavior
Nicely-handled error

### Reproduction

[comment]: # (Describe how we can replicate the bug step by step.)

- Open Status
-  Go to Webview
-  Type non-existing URL -> Enter

### Additional Information

- Status version: nightly 27/03/2020
- Operating System: Android, iOS

### PR DESCRIPTION
**Pull request by flexsurfer**
fixes #10233

### CODE REVIEW

**Review by rasom — APPROVED** [review]

File: src/status_im/ui/screens/browser/views.cljs [hunk 1]
```diff
@@ -59,12 +60,13 @@
                        (re-frame/dispatch [:browser.ui/remove-browser-pressed browser-id]))))]
    [toolbar-content url url-original browser url-editing?]])
 
-(defn- web-view-error [_ code desc]
+(defn- web-view-error [_ _ desc]
   (reagent/as-element
    [react/view styles/web-view-error
+    [react/image {:style  {:width 140 :height 140 :margin-bottom 16}
+                  :source {:uri (contenthash/url
+                                 "e3010170122001bbe2f5bfba0305a3bdc2047fddc47ee595a591bdee61de6040ffc2456624e1")}}]
```
Comment (vitvly) [inline src/status_im/ui/screens/browser/views.cljs:68]: Cool, this helps with https://github.com/status-im/status-react/pull/10799#issuecomment-644071944 :). But what is the url here?

**Review by vitvly — APPROVED** [review]

**Comment by churik** [comment]
failed e2e are network-related

**Comment by churik** [comment]
Really nice pic, love it!
Thanks @flexsurfer 
Checked on IOS and Android
