### PR TITLE
Pending stickers status maintains after app restart

### LINKED ISSUE #9754: User can double purchase a sticker pack while Tx is pending
# Bug Report

## Problem

- Paid sticker packs require Tx mined to install
- No indication of pending Tx in Status wallet
- If user refreshes app, sticker pack no longer shows spinning loader (indicating Tx mining)
- User can then purchase sticker pack again—nothing stops them from making two Txs for the same pack

#### Expected behavior

Pending sticker purchase persists even after app is closed and reopened.

#### Actual behavior

If app is restarted, sticker store forgets that a Tx is pending for a purchase pack. User can pay for the same the pack again.

Tested on iOS nightly.

### PR DESCRIPTION
**Pull request by vkjr**
fixes #9754

### Summary
If stickers purchase wasn't confirmed yet, user will see waiting spinner even after restart

**NOTE**: `status-go` [PR](https://github.com/status-im/status-go/pull/1830) should be merged first and `status-go-version.json` updated before merge of this one.

### Review notes
When user purchases a stickerpack, new`pending-stickers` record added to multiaccount to survive restart (Related changes in status-go: https://github.com/status-im/status-go/pull/1830).
After app start we run `set-pending-timeout-fx` again to make sure that pending stickers will be processed

#### Platforms
- Android
- iOS

#### Areas that maybe impacted
Stickers purchasing

### Steps to test
- Open Status
- open available stickers
- sign transaction to purchase Tozemoon stickerpack and immediately switch off the internet
- restart the app 
- turn on the internet and quickly open available stickers page
- Tozemoon stickerpack should be pending and will change to available in a few seconds (current timeout for checking pending stickers is 10s)

status: ready

### CODE REVIEW

**Comment by vkjr** [comment]
Tested on ios that stickers can be purchased and pending status remains between app restarts.

File: src/status_im/data_store/settings.cljs [hunk 1]
```diff
@@ -31,6 +31,9 @@
              {}
              stickers-packs))
 
+(defn rpc->pending-packs [pending-packs]
```
Comment (rasom) [inline src/status_im/data_store/settings.cljs]: Can we just use `set` instead?

File: src/status_im/stickers/core.cljs [hunk 2]
```diff
@@ -86,11 +86,16 @@
...
+  [{:keys [db] :as cofx}]
+  (let [sticker-packs (get-in db [:multiaccount :stickers/packs-installed])
+        pending-packs (get-in db [:multiaccount :stickers/packs-pending] #{})]
+    (fx/merge cofx
+              {:db (assoc db
+                          :stickers/packs-installed sticker-packs
+                          :stickers/packs sticker-packs
+                          :stickers/packs-pending pending-packs)}
+              #(when (not-empty pending-packs)
+                 {:stickers/set-pending-timeout-fx nil}))))
```
Comment (rasom) [inline src/status_im/stickers/core.cljs]: It could be just
```clojure
(cond-> {:db (assoc db
                    :stickers/packs-installed sticker-packs
                    :stickers/packs sticker-packs
                    :stickers/packs-pending pending-packs)}
  (not-empty pending-packs)
  (assoc :stickers/set-pending-timeout-fx nil))
```

**Comment by flexsurfer** [comment]
i think it will be better to implement saving pending transactions, in that case we could just check that we have pending transaction for stickers

**Comment by vkjr** [comment]
@rasom, thanks for your notes, addressed.

**Comment by vkjr** [comment]
@flexsurfer, yesterday we discussed that it is possible to commit this PR and create a separate issue to support pending transactions. If you still don't mind to make it this way, could you please comment/review? Thanks.

**Review by flexsurfer — APPROVED** [review]

**Comment by Serhy** [comment]
Tested with iOS13 and Android (8.1),  - all items from #9754 are fixed! Eventually transaction is mined and Tozemoon available for use. Well done, @vkjr !

**Comment by vkjr** [comment]
@Serhy, thank you for testing! `status-go` changes merged, this PR updated to include newer version of `status-go`, so will merge it now.
